name = "LisiSabatini"
version = "0.1.0"
keywords = ["mathematics", "group-theory", "sylow"]
defaultTargets = ["LisiSabatini"]

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.29.1"

[[lean_lib]]
name = "LisiSabatini"
