module

public import LisiSabatini.FiniteCertificates.CodedIndexedTable
public import LisiSabatini.FiniteCertificates.PermutationCodeArithmetic

/-!
# Indexed finite Sylow certificates for A8

Generated by generate_a8_rows.py from A8Data.json. Python supplies
candidate literals. All permutation, product, inverse and cardinality
acceptance proofs are checked by the Lean kernel.
-/

@[expose] public section

namespace LisiSabatini.FiniteCertificates.A8Rows

abbrev G := alternatingGroup (Fin 8)

local instance : DecidableEq G := alternatingCodeDecidableEq_fin8

set_option maxRecDepth 100000

/-- The injective arithmetic code used only while checking row tables. -/
def rowCode (g : G) : ℕ := permutationCode g.val

theorem rowCode_injective : Function.Injective rowCode := by
  intro g h heq
  exact Subtype.ext (permutationCode_injective_fin8 heq)

theorem rowCode_mul (g h : G) :
    rowCode (g * h) = composeCode8 (rowCode g) (rowCode h) :=
  permutationCode_mul_fin8 g.val h.val

theorem rowCode_one : rowCode 1 = 342391 := by decide +kernel

theorem card_G : Nat.card G = 20160 := by
  rw [nat_card_alternatingGroup]
  norm_num
  decide +kernel

local instance : Fact (Nat.Prime 2) := ⟨by decide⟩

def p2e0Perm : Equiv.Perm (Fin 8) where
  toFun := ![0, 1, 2, 3, 4, 5, 6, 7]
  invFun := ![0, 1, 2, 3, 4, 5, 6, 7]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p2e0 : G := ⟨p2e0Perm, by
  change Equiv.Perm.sign p2e0Perm = 1
  decide +kernel⟩

def p2e1Perm : Equiv.Perm (Fin 8) where
  toFun := ![0, 1, 2, 3, 5, 4, 7, 6]
  invFun := ![0, 1, 2, 3, 5, 4, 7, 6]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p2e1 : G := ⟨p2e1Perm, by
  change Equiv.Perm.sign p2e1Perm = 1
  decide +kernel⟩

def p2e2Perm : Equiv.Perm (Fin 8) where
  toFun := ![0, 1, 2, 3, 6, 7, 4, 5]
  invFun := ![0, 1, 2, 3, 6, 7, 4, 5]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p2e2 : G := ⟨p2e2Perm, by
  change Equiv.Perm.sign p2e2Perm = 1
  decide +kernel⟩

def p2e3Perm : Equiv.Perm (Fin 8) where
  toFun := ![0, 1, 2, 3, 7, 6, 5, 4]
  invFun := ![0, 1, 2, 3, 7, 6, 5, 4]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p2e3 : G := ⟨p2e3Perm, by
  change Equiv.Perm.sign p2e3Perm = 1
  decide +kernel⟩

def p2e4Perm : Equiv.Perm (Fin 8) where
  toFun := ![0, 1, 3, 2, 4, 5, 7, 6]
  invFun := ![0, 1, 3, 2, 4, 5, 7, 6]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p2e4 : G := ⟨p2e4Perm, by
  change Equiv.Perm.sign p2e4Perm = 1
  decide +kernel⟩

def p2e5Perm : Equiv.Perm (Fin 8) where
  toFun := ![0, 1, 3, 2, 5, 4, 6, 7]
  invFun := ![0, 1, 3, 2, 5, 4, 6, 7]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p2e5 : G := ⟨p2e5Perm, by
  change Equiv.Perm.sign p2e5Perm = 1
  decide +kernel⟩

def p2e6Perm : Equiv.Perm (Fin 8) where
  toFun := ![0, 1, 3, 2, 6, 7, 5, 4]
  invFun := ![0, 1, 3, 2, 7, 6, 4, 5]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p2e6 : G := ⟨p2e6Perm, by
  change Equiv.Perm.sign p2e6Perm = 1
  decide +kernel⟩

def p2e7Perm : Equiv.Perm (Fin 8) where
  toFun := ![0, 1, 3, 2, 7, 6, 4, 5]
  invFun := ![0, 1, 3, 2, 6, 7, 5, 4]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p2e7 : G := ⟨p2e7Perm, by
  change Equiv.Perm.sign p2e7Perm = 1
  decide +kernel⟩

def p2e8Perm : Equiv.Perm (Fin 8) where
  toFun := ![1, 0, 2, 3, 4, 5, 7, 6]
  invFun := ![1, 0, 2, 3, 4, 5, 7, 6]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p2e8 : G := ⟨p2e8Perm, by
  change Equiv.Perm.sign p2e8Perm = 1
  decide +kernel⟩

def p2e9Perm : Equiv.Perm (Fin 8) where
  toFun := ![1, 0, 2, 3, 5, 4, 6, 7]
  invFun := ![1, 0, 2, 3, 5, 4, 6, 7]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p2e9 : G := ⟨p2e9Perm, by
  change Equiv.Perm.sign p2e9Perm = 1
  decide +kernel⟩

def p2e10Perm : Equiv.Perm (Fin 8) where
  toFun := ![1, 0, 2, 3, 6, 7, 5, 4]
  invFun := ![1, 0, 2, 3, 7, 6, 4, 5]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p2e10 : G := ⟨p2e10Perm, by
  change Equiv.Perm.sign p2e10Perm = 1
  decide +kernel⟩

def p2e11Perm : Equiv.Perm (Fin 8) where
  toFun := ![1, 0, 2, 3, 7, 6, 4, 5]
  invFun := ![1, 0, 2, 3, 6, 7, 5, 4]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p2e11 : G := ⟨p2e11Perm, by
  change Equiv.Perm.sign p2e11Perm = 1
  decide +kernel⟩

def p2e12Perm : Equiv.Perm (Fin 8) where
  toFun := ![1, 0, 3, 2, 4, 5, 6, 7]
  invFun := ![1, 0, 3, 2, 4, 5, 6, 7]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p2e12 : G := ⟨p2e12Perm, by
  change Equiv.Perm.sign p2e12Perm = 1
  decide +kernel⟩

def p2e13Perm : Equiv.Perm (Fin 8) where
  toFun := ![1, 0, 3, 2, 5, 4, 7, 6]
  invFun := ![1, 0, 3, 2, 5, 4, 7, 6]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p2e13 : G := ⟨p2e13Perm, by
  change Equiv.Perm.sign p2e13Perm = 1
  decide +kernel⟩

def p2e14Perm : Equiv.Perm (Fin 8) where
  toFun := ![1, 0, 3, 2, 6, 7, 4, 5]
  invFun := ![1, 0, 3, 2, 6, 7, 4, 5]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p2e14 : G := ⟨p2e14Perm, by
  change Equiv.Perm.sign p2e14Perm = 1
  decide +kernel⟩

def p2e15Perm : Equiv.Perm (Fin 8) where
  toFun := ![1, 0, 3, 2, 7, 6, 5, 4]
  invFun := ![1, 0, 3, 2, 7, 6, 5, 4]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p2e15 : G := ⟨p2e15Perm, by
  change Equiv.Perm.sign p2e15Perm = 1
  decide +kernel⟩

def p2e16Perm : Equiv.Perm (Fin 8) where
  toFun := ![2, 3, 0, 1, 4, 5, 6, 7]
  invFun := ![2, 3, 0, 1, 4, 5, 6, 7]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p2e16 : G := ⟨p2e16Perm, by
  change Equiv.Perm.sign p2e16Perm = 1
  decide +kernel⟩

def p2e17Perm : Equiv.Perm (Fin 8) where
  toFun := ![2, 3, 0, 1, 5, 4, 7, 6]
  invFun := ![2, 3, 0, 1, 5, 4, 7, 6]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p2e17 : G := ⟨p2e17Perm, by
  change Equiv.Perm.sign p2e17Perm = 1
  decide +kernel⟩

def p2e18Perm : Equiv.Perm (Fin 8) where
  toFun := ![2, 3, 0, 1, 6, 7, 4, 5]
  invFun := ![2, 3, 0, 1, 6, 7, 4, 5]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p2e18 : G := ⟨p2e18Perm, by
  change Equiv.Perm.sign p2e18Perm = 1
  decide +kernel⟩

def p2e19Perm : Equiv.Perm (Fin 8) where
  toFun := ![2, 3, 0, 1, 7, 6, 5, 4]
  invFun := ![2, 3, 0, 1, 7, 6, 5, 4]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p2e19 : G := ⟨p2e19Perm, by
  change Equiv.Perm.sign p2e19Perm = 1
  decide +kernel⟩

def p2e20Perm : Equiv.Perm (Fin 8) where
  toFun := ![2, 3, 1, 0, 4, 5, 7, 6]
  invFun := ![3, 2, 0, 1, 4, 5, 7, 6]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p2e20 : G := ⟨p2e20Perm, by
  change Equiv.Perm.sign p2e20Perm = 1
  decide +kernel⟩

def p2e21Perm : Equiv.Perm (Fin 8) where
  toFun := ![2, 3, 1, 0, 5, 4, 6, 7]
  invFun := ![3, 2, 0, 1, 5, 4, 6, 7]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p2e21 : G := ⟨p2e21Perm, by
  change Equiv.Perm.sign p2e21Perm = 1
  decide +kernel⟩

def p2e22Perm : Equiv.Perm (Fin 8) where
  toFun := ![2, 3, 1, 0, 6, 7, 5, 4]
  invFun := ![3, 2, 0, 1, 7, 6, 4, 5]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p2e22 : G := ⟨p2e22Perm, by
  change Equiv.Perm.sign p2e22Perm = 1
  decide +kernel⟩

def p2e23Perm : Equiv.Perm (Fin 8) where
  toFun := ![2, 3, 1, 0, 7, 6, 4, 5]
  invFun := ![3, 2, 0, 1, 6, 7, 5, 4]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p2e23 : G := ⟨p2e23Perm, by
  change Equiv.Perm.sign p2e23Perm = 1
  decide +kernel⟩

def p2e24Perm : Equiv.Perm (Fin 8) where
  toFun := ![3, 2, 0, 1, 4, 5, 7, 6]
  invFun := ![2, 3, 1, 0, 4, 5, 7, 6]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p2e24 : G := ⟨p2e24Perm, by
  change Equiv.Perm.sign p2e24Perm = 1
  decide +kernel⟩

def p2e25Perm : Equiv.Perm (Fin 8) where
  toFun := ![3, 2, 0, 1, 5, 4, 6, 7]
  invFun := ![2, 3, 1, 0, 5, 4, 6, 7]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p2e25 : G := ⟨p2e25Perm, by
  change Equiv.Perm.sign p2e25Perm = 1
  decide +kernel⟩

def p2e26Perm : Equiv.Perm (Fin 8) where
  toFun := ![3, 2, 0, 1, 6, 7, 5, 4]
  invFun := ![2, 3, 1, 0, 7, 6, 4, 5]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p2e26 : G := ⟨p2e26Perm, by
  change Equiv.Perm.sign p2e26Perm = 1
  decide +kernel⟩

def p2e27Perm : Equiv.Perm (Fin 8) where
  toFun := ![3, 2, 0, 1, 7, 6, 4, 5]
  invFun := ![2, 3, 1, 0, 6, 7, 5, 4]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p2e27 : G := ⟨p2e27Perm, by
  change Equiv.Perm.sign p2e27Perm = 1
  decide +kernel⟩

def p2e28Perm : Equiv.Perm (Fin 8) where
  toFun := ![3, 2, 1, 0, 4, 5, 6, 7]
  invFun := ![3, 2, 1, 0, 4, 5, 6, 7]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p2e28 : G := ⟨p2e28Perm, by
  change Equiv.Perm.sign p2e28Perm = 1
  decide +kernel⟩

def p2e29Perm : Equiv.Perm (Fin 8) where
  toFun := ![3, 2, 1, 0, 5, 4, 7, 6]
  invFun := ![3, 2, 1, 0, 5, 4, 7, 6]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p2e29 : G := ⟨p2e29Perm, by
  change Equiv.Perm.sign p2e29Perm = 1
  decide +kernel⟩

def p2e30Perm : Equiv.Perm (Fin 8) where
  toFun := ![3, 2, 1, 0, 6, 7, 4, 5]
  invFun := ![3, 2, 1, 0, 6, 7, 4, 5]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p2e30 : G := ⟨p2e30Perm, by
  change Equiv.Perm.sign p2e30Perm = 1
  decide +kernel⟩

def p2e31Perm : Equiv.Perm (Fin 8) where
  toFun := ![3, 2, 1, 0, 7, 6, 5, 4]
  invFun := ![3, 2, 1, 0, 7, 6, 5, 4]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p2e31 : G := ⟨p2e31Perm, by
  change Equiv.Perm.sign p2e31Perm = 1
  decide +kernel⟩

def p2e32Perm : Equiv.Perm (Fin 8) where
  toFun := ![4, 5, 6, 7, 0, 1, 2, 3]
  invFun := ![4, 5, 6, 7, 0, 1, 2, 3]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p2e32 : G := ⟨p2e32Perm, by
  change Equiv.Perm.sign p2e32Perm = 1
  decide +kernel⟩

def p2e33Perm : Equiv.Perm (Fin 8) where
  toFun := ![4, 5, 6, 7, 1, 0, 3, 2]
  invFun := ![5, 4, 7, 6, 0, 1, 2, 3]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p2e33 : G := ⟨p2e33Perm, by
  change Equiv.Perm.sign p2e33Perm = 1
  decide +kernel⟩

def p2e34Perm : Equiv.Perm (Fin 8) where
  toFun := ![4, 5, 6, 7, 2, 3, 0, 1]
  invFun := ![6, 7, 4, 5, 0, 1, 2, 3]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p2e34 : G := ⟨p2e34Perm, by
  change Equiv.Perm.sign p2e34Perm = 1
  decide +kernel⟩

def p2e35Perm : Equiv.Perm (Fin 8) where
  toFun := ![4, 5, 6, 7, 3, 2, 1, 0]
  invFun := ![7, 6, 5, 4, 0, 1, 2, 3]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p2e35 : G := ⟨p2e35Perm, by
  change Equiv.Perm.sign p2e35Perm = 1
  decide +kernel⟩

def p2e36Perm : Equiv.Perm (Fin 8) where
  toFun := ![4, 5, 7, 6, 0, 1, 3, 2]
  invFun := ![4, 5, 7, 6, 0, 1, 3, 2]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p2e36 : G := ⟨p2e36Perm, by
  change Equiv.Perm.sign p2e36Perm = 1
  decide +kernel⟩

def p2e37Perm : Equiv.Perm (Fin 8) where
  toFun := ![4, 5, 7, 6, 1, 0, 2, 3]
  invFun := ![5, 4, 6, 7, 0, 1, 3, 2]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p2e37 : G := ⟨p2e37Perm, by
  change Equiv.Perm.sign p2e37Perm = 1
  decide +kernel⟩

def p2e38Perm : Equiv.Perm (Fin 8) where
  toFun := ![4, 5, 7, 6, 2, 3, 1, 0]
  invFun := ![7, 6, 4, 5, 0, 1, 3, 2]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p2e38 : G := ⟨p2e38Perm, by
  change Equiv.Perm.sign p2e38Perm = 1
  decide +kernel⟩

def p2e39Perm : Equiv.Perm (Fin 8) where
  toFun := ![4, 5, 7, 6, 3, 2, 0, 1]
  invFun := ![6, 7, 5, 4, 0, 1, 3, 2]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p2e39 : G := ⟨p2e39Perm, by
  change Equiv.Perm.sign p2e39Perm = 1
  decide +kernel⟩

def p2e40Perm : Equiv.Perm (Fin 8) where
  toFun := ![5, 4, 6, 7, 0, 1, 3, 2]
  invFun := ![4, 5, 7, 6, 1, 0, 2, 3]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p2e40 : G := ⟨p2e40Perm, by
  change Equiv.Perm.sign p2e40Perm = 1
  decide +kernel⟩

def p2e41Perm : Equiv.Perm (Fin 8) where
  toFun := ![5, 4, 6, 7, 1, 0, 2, 3]
  invFun := ![5, 4, 6, 7, 1, 0, 2, 3]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p2e41 : G := ⟨p2e41Perm, by
  change Equiv.Perm.sign p2e41Perm = 1
  decide +kernel⟩

def p2e42Perm : Equiv.Perm (Fin 8) where
  toFun := ![5, 4, 6, 7, 2, 3, 1, 0]
  invFun := ![7, 6, 4, 5, 1, 0, 2, 3]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p2e42 : G := ⟨p2e42Perm, by
  change Equiv.Perm.sign p2e42Perm = 1
  decide +kernel⟩

def p2e43Perm : Equiv.Perm (Fin 8) where
  toFun := ![5, 4, 6, 7, 3, 2, 0, 1]
  invFun := ![6, 7, 5, 4, 1, 0, 2, 3]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p2e43 : G := ⟨p2e43Perm, by
  change Equiv.Perm.sign p2e43Perm = 1
  decide +kernel⟩

def p2e44Perm : Equiv.Perm (Fin 8) where
  toFun := ![5, 4, 7, 6, 0, 1, 2, 3]
  invFun := ![4, 5, 6, 7, 1, 0, 3, 2]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p2e44 : G := ⟨p2e44Perm, by
  change Equiv.Perm.sign p2e44Perm = 1
  decide +kernel⟩

def p2e45Perm : Equiv.Perm (Fin 8) where
  toFun := ![5, 4, 7, 6, 1, 0, 3, 2]
  invFun := ![5, 4, 7, 6, 1, 0, 3, 2]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p2e45 : G := ⟨p2e45Perm, by
  change Equiv.Perm.sign p2e45Perm = 1
  decide +kernel⟩

def p2e46Perm : Equiv.Perm (Fin 8) where
  toFun := ![5, 4, 7, 6, 2, 3, 0, 1]
  invFun := ![6, 7, 4, 5, 1, 0, 3, 2]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p2e46 : G := ⟨p2e46Perm, by
  change Equiv.Perm.sign p2e46Perm = 1
  decide +kernel⟩

def p2e47Perm : Equiv.Perm (Fin 8) where
  toFun := ![5, 4, 7, 6, 3, 2, 1, 0]
  invFun := ![7, 6, 5, 4, 1, 0, 3, 2]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p2e47 : G := ⟨p2e47Perm, by
  change Equiv.Perm.sign p2e47Perm = 1
  decide +kernel⟩

def p2e48Perm : Equiv.Perm (Fin 8) where
  toFun := ![6, 7, 4, 5, 0, 1, 2, 3]
  invFun := ![4, 5, 6, 7, 2, 3, 0, 1]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p2e48 : G := ⟨p2e48Perm, by
  change Equiv.Perm.sign p2e48Perm = 1
  decide +kernel⟩

def p2e49Perm : Equiv.Perm (Fin 8) where
  toFun := ![6, 7, 4, 5, 1, 0, 3, 2]
  invFun := ![5, 4, 7, 6, 2, 3, 0, 1]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p2e49 : G := ⟨p2e49Perm, by
  change Equiv.Perm.sign p2e49Perm = 1
  decide +kernel⟩

def p2e50Perm : Equiv.Perm (Fin 8) where
  toFun := ![6, 7, 4, 5, 2, 3, 0, 1]
  invFun := ![6, 7, 4, 5, 2, 3, 0, 1]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p2e50 : G := ⟨p2e50Perm, by
  change Equiv.Perm.sign p2e50Perm = 1
  decide +kernel⟩

def p2e51Perm : Equiv.Perm (Fin 8) where
  toFun := ![6, 7, 4, 5, 3, 2, 1, 0]
  invFun := ![7, 6, 5, 4, 2, 3, 0, 1]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p2e51 : G := ⟨p2e51Perm, by
  change Equiv.Perm.sign p2e51Perm = 1
  decide +kernel⟩

def p2e52Perm : Equiv.Perm (Fin 8) where
  toFun := ![6, 7, 5, 4, 0, 1, 3, 2]
  invFun := ![4, 5, 7, 6, 3, 2, 0, 1]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p2e52 : G := ⟨p2e52Perm, by
  change Equiv.Perm.sign p2e52Perm = 1
  decide +kernel⟩

def p2e53Perm : Equiv.Perm (Fin 8) where
  toFun := ![6, 7, 5, 4, 1, 0, 2, 3]
  invFun := ![5, 4, 6, 7, 3, 2, 0, 1]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p2e53 : G := ⟨p2e53Perm, by
  change Equiv.Perm.sign p2e53Perm = 1
  decide +kernel⟩

def p2e54Perm : Equiv.Perm (Fin 8) where
  toFun := ![6, 7, 5, 4, 2, 3, 1, 0]
  invFun := ![7, 6, 4, 5, 3, 2, 0, 1]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p2e54 : G := ⟨p2e54Perm, by
  change Equiv.Perm.sign p2e54Perm = 1
  decide +kernel⟩

def p2e55Perm : Equiv.Perm (Fin 8) where
  toFun := ![6, 7, 5, 4, 3, 2, 0, 1]
  invFun := ![6, 7, 5, 4, 3, 2, 0, 1]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p2e55 : G := ⟨p2e55Perm, by
  change Equiv.Perm.sign p2e55Perm = 1
  decide +kernel⟩

def p2e56Perm : Equiv.Perm (Fin 8) where
  toFun := ![7, 6, 4, 5, 0, 1, 3, 2]
  invFun := ![4, 5, 7, 6, 2, 3, 1, 0]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p2e56 : G := ⟨p2e56Perm, by
  change Equiv.Perm.sign p2e56Perm = 1
  decide +kernel⟩

def p2e57Perm : Equiv.Perm (Fin 8) where
  toFun := ![7, 6, 4, 5, 1, 0, 2, 3]
  invFun := ![5, 4, 6, 7, 2, 3, 1, 0]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p2e57 : G := ⟨p2e57Perm, by
  change Equiv.Perm.sign p2e57Perm = 1
  decide +kernel⟩

def p2e58Perm : Equiv.Perm (Fin 8) where
  toFun := ![7, 6, 4, 5, 2, 3, 1, 0]
  invFun := ![7, 6, 4, 5, 2, 3, 1, 0]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p2e58 : G := ⟨p2e58Perm, by
  change Equiv.Perm.sign p2e58Perm = 1
  decide +kernel⟩

def p2e59Perm : Equiv.Perm (Fin 8) where
  toFun := ![7, 6, 4, 5, 3, 2, 0, 1]
  invFun := ![6, 7, 5, 4, 2, 3, 1, 0]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p2e59 : G := ⟨p2e59Perm, by
  change Equiv.Perm.sign p2e59Perm = 1
  decide +kernel⟩

def p2e60Perm : Equiv.Perm (Fin 8) where
  toFun := ![7, 6, 5, 4, 0, 1, 2, 3]
  invFun := ![4, 5, 6, 7, 3, 2, 1, 0]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p2e60 : G := ⟨p2e60Perm, by
  change Equiv.Perm.sign p2e60Perm = 1
  decide +kernel⟩

def p2e61Perm : Equiv.Perm (Fin 8) where
  toFun := ![7, 6, 5, 4, 1, 0, 3, 2]
  invFun := ![5, 4, 7, 6, 3, 2, 1, 0]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p2e61 : G := ⟨p2e61Perm, by
  change Equiv.Perm.sign p2e61Perm = 1
  decide +kernel⟩

def p2e62Perm : Equiv.Perm (Fin 8) where
  toFun := ![7, 6, 5, 4, 2, 3, 0, 1]
  invFun := ![6, 7, 4, 5, 3, 2, 1, 0]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p2e62 : G := ⟨p2e62Perm, by
  change Equiv.Perm.sign p2e62Perm = 1
  decide +kernel⟩

def p2e63Perm : Equiv.Perm (Fin 8) where
  toFun := ![7, 6, 5, 4, 3, 2, 1, 0]
  invFun := ![7, 6, 5, 4, 3, 2, 1, 0]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p2e63 : G := ⟨p2e63Perm, by
  change Equiv.Perm.sign p2e63Perm = 1
  decide +kernel⟩

/-- The sorted canonical subgroup carrier, before forming a finite set. -/
def row2Elements : List G :=
  [p2e0, p2e1, p2e2, p2e3, p2e4, p2e5, p2e6, p2e7,
   p2e8, p2e9, p2e10, p2e11, p2e12, p2e13, p2e14, p2e15,
   p2e16, p2e17, p2e18, p2e19, p2e20, p2e21, p2e22, p2e23,
   p2e24, p2e25, p2e26, p2e27, p2e28, p2e29, p2e30, p2e31,
   p2e32, p2e33, p2e34, p2e35, p2e36, p2e37, p2e38, p2e39,
   p2e40, p2e41, p2e42, p2e43, p2e44, p2e45, p2e46, p2e47,
   p2e48, p2e49, p2e50, p2e51, p2e52, p2e53, p2e54, p2e55,
   p2e56, p2e57, p2e58, p2e59, p2e60, p2e61, p2e62, p2e63]

/-- All row entries after the first, which is the identity. -/
def row2Probes : List G :=
  [p2e1, p2e2, p2e3, p2e4, p2e5, p2e6, p2e7, p2e8,
   p2e9, p2e10, p2e11, p2e12, p2e13, p2e14, p2e15, p2e16,
   p2e17, p2e18, p2e19, p2e20, p2e21, p2e22, p2e23, p2e24,
   p2e25, p2e26, p2e27, p2e28, p2e29, p2e30, p2e31, p2e32,
   p2e33, p2e34, p2e35, p2e36, p2e37, p2e38, p2e39, p2e40,
   p2e41, p2e42, p2e43, p2e44, p2e45, p2e46, p2e47, p2e48,
   p2e49, p2e50, p2e51, p2e52, p2e53, p2e54, p2e55, p2e56,
   p2e57, p2e58, p2e59, p2e60, p2e61, p2e62, p2e63]

theorem p2e0_eq_one : p2e0 = 1 := by decide +kernel

theorem row2Elements_eq_one_cons :
    row2Elements = 1 :: row2Probes := by
  rw [← p2e0_eq_one]
  rfl

/-- Cached literal base-8 codes for the row elements. -/
def row2Codes : List ℕ :=
  [342391, 342846, 343525, 343980, 371070, 371511, 372204, 372645,
   2177406, 2177847, 2178540, 2178981, 2206071, 2206526, 2207205, 2207660,
   4987255, 4987710, 4988389, 4988844, 5015934, 5016375, 5017068, 5017509,
   6822270, 6822711, 6823404, 6823845, 6850935, 6851390, 6852069, 6852524,
   9924691, 9925146, 9925825, 9926280, 9953370, 9953811, 9954504, 9954945,
   11759706, 11760147, 11760840, 11761281, 11788371, 11788826, 11789505, 11789960,
   14569555, 14570010, 14570689, 14571144, 14598234, 14598675, 14599368, 14599809,
   16404570, 16405011, 16405704, 16406145, 16433235, 16433690, 16434369, 16434824]

theorem row2Codes_eq :
    row2Codes = row2Elements.map (fun g ↦ permutationCode g.val) := by
  decide +kernel

theorem row2Elements_nodup : row2Elements.Nodup :=
  nodup_of_code_isChain (fun g : G ↦ permutationCode g.val) (by decide +kernel)

def row2 : Finset G :=
  finsetOfNodupList row2Elements row2Elements_nodup

theorem row2_card : row2.card = 64 := by
  change row2Elements.length = 64
  decide +kernel

/-- Array access keeps indexed closure verification linear in table size. -/
def row2Array : Array G := row2Elements.toArray

def row2At (i : Fin 64) : G :=
  row2Array[i.val]'(by change i.val < 64; exact i.isLt)

/-- Cached arithmetic row; products never reconstruct its group elements. -/
def row2CodeArray : Array ℕ := row2Codes.toArray

def row2CodeAt (i : Fin 64) : ℕ :=
  row2CodeArray[i.val]'(by change i.val < 64; exact i.isLt)

theorem row2CodeAt_correct :
    ∀ i, rowCode (row2At i) = row2CodeAt i := by
  decide +kernel

def row2InverseIndices : Array (Fin 64) :=
  #[0, 1, 2, 3, 4, 5, 7, 6,
   8, 9, 11, 10, 12, 13, 14, 15,
   16, 17, 18, 19, 24, 25, 27, 26,
   20, 21, 23, 22, 28, 29, 30, 31,
   32, 44, 48, 60, 36, 40, 56, 52,
   37, 41, 57, 53, 33, 45, 49, 61,
   34, 46, 50, 62, 39, 43, 59, 55,
   38, 42, 58, 54, 35, 47, 51, 63]

def row2InverseIndex (i : Fin 64) : Fin 64 :=
  row2InverseIndices[i.val]'(by change i.val < 64; exact i.isLt)

/-- Two-level multiplication indices keep each lookup bounded by row order. -/
def row2ProductRows : Array (Fin 64 → Fin 64) :=
  #[![0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15,
      16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
      32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
      48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63],
    ![1, 0, 3, 2, 5, 4, 7, 6, 9, 8, 11, 10, 13, 12, 15, 14,
      17, 16, 19, 18, 21, 20, 23, 22, 25, 24, 27, 26, 29, 28, 31, 30,
      44, 45, 46, 47, 40, 41, 42, 43, 36, 37, 38, 39, 32, 33, 34, 35,
      60, 61, 62, 63, 56, 57, 58, 59, 52, 53, 54, 55, 48, 49, 50, 51],
    ![2, 3, 0, 1, 6, 7, 4, 5, 10, 11, 8, 9, 14, 15, 12, 13,
      18, 19, 16, 17, 22, 23, 20, 21, 26, 27, 24, 25, 30, 31, 28, 29,
      48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
      32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47],
    ![3, 2, 1, 0, 7, 6, 5, 4, 11, 10, 9, 8, 15, 14, 13, 12,
      19, 18, 17, 16, 23, 22, 21, 20, 27, 26, 25, 24, 31, 30, 29, 28,
      60, 61, 62, 63, 56, 57, 58, 59, 52, 53, 54, 55, 48, 49, 50, 51,
      44, 45, 46, 47, 40, 41, 42, 43, 36, 37, 38, 39, 32, 33, 34, 35],
    ![4, 5, 7, 6, 0, 1, 3, 2, 12, 13, 15, 14, 8, 9, 11, 10,
      24, 25, 27, 26, 28, 29, 31, 30, 16, 17, 19, 18, 20, 21, 23, 22,
      36, 37, 39, 38, 32, 33, 35, 34, 44, 45, 47, 46, 40, 41, 43, 42,
      56, 57, 59, 58, 60, 61, 63, 62, 48, 49, 51, 50, 52, 53, 55, 54],
    ![5, 4, 6, 7, 1, 0, 2, 3, 13, 12, 14, 15, 9, 8, 10, 11,
      25, 24, 26, 27, 29, 28, 30, 31, 17, 16, 18, 19, 21, 20, 22, 23,
      40, 41, 43, 42, 44, 45, 47, 46, 32, 33, 35, 34, 36, 37, 39, 38,
      52, 53, 55, 54, 48, 49, 51, 50, 60, 61, 63, 62, 56, 57, 59, 58],
    ![6, 7, 5, 4, 2, 3, 1, 0, 14, 15, 13, 12, 10, 11, 9, 8,
      26, 27, 25, 24, 30, 31, 29, 28, 18, 19, 17, 16, 22, 23, 21, 20,
      52, 53, 55, 54, 48, 49, 51, 50, 60, 61, 63, 62, 56, 57, 59, 58,
      40, 41, 43, 42, 44, 45, 47, 46, 32, 33, 35, 34, 36, 37, 39, 38],
    ![7, 6, 4, 5, 3, 2, 0, 1, 15, 14, 12, 13, 11, 10, 8, 9,
      27, 26, 24, 25, 31, 30, 28, 29, 19, 18, 16, 17, 23, 22, 20, 21,
      56, 57, 59, 58, 60, 61, 63, 62, 48, 49, 51, 50, 52, 53, 55, 54,
      36, 37, 39, 38, 32, 33, 35, 34, 44, 45, 47, 46, 40, 41, 43, 42],
    ![8, 9, 11, 10, 12, 13, 15, 14, 0, 1, 3, 2, 4, 5, 7, 6,
      20, 21, 23, 22, 16, 17, 19, 18, 28, 29, 31, 30, 24, 25, 27, 26,
      37, 36, 38, 39, 33, 32, 34, 35, 45, 44, 46, 47, 41, 40, 42, 43,
      57, 56, 58, 59, 61, 60, 62, 63, 49, 48, 50, 51, 53, 52, 54, 55],
    ![9, 8, 10, 11, 13, 12, 14, 15, 1, 0, 2, 3, 5, 4, 6, 7,
      21, 20, 22, 23, 17, 16, 18, 19, 29, 28, 30, 31, 25, 24, 26, 27,
      41, 40, 42, 43, 45, 44, 46, 47, 33, 32, 34, 35, 37, 36, 38, 39,
      53, 52, 54, 55, 49, 48, 50, 51, 61, 60, 62, 63, 57, 56, 58, 59],
    ![10, 11, 9, 8, 14, 15, 13, 12, 2, 3, 1, 0, 6, 7, 5, 4,
      22, 23, 21, 20, 18, 19, 17, 16, 30, 31, 29, 28, 26, 27, 25, 24,
      53, 52, 54, 55, 49, 48, 50, 51, 61, 60, 62, 63, 57, 56, 58, 59,
      41, 40, 42, 43, 45, 44, 46, 47, 33, 32, 34, 35, 37, 36, 38, 39],
    ![11, 10, 8, 9, 15, 14, 12, 13, 3, 2, 0, 1, 7, 6, 4, 5,
      23, 22, 20, 21, 19, 18, 16, 17, 31, 30, 28, 29, 27, 26, 24, 25,
      57, 56, 58, 59, 61, 60, 62, 63, 49, 48, 50, 51, 53, 52, 54, 55,
      37, 36, 38, 39, 33, 32, 34, 35, 45, 44, 46, 47, 41, 40, 42, 43],
    ![12, 13, 14, 15, 8, 9, 10, 11, 4, 5, 6, 7, 0, 1, 2, 3,
      28, 29, 30, 31, 24, 25, 26, 27, 20, 21, 22, 23, 16, 17, 18, 19,
      33, 32, 35, 34, 37, 36, 39, 38, 41, 40, 43, 42, 45, 44, 47, 46,
      49, 48, 51, 50, 53, 52, 55, 54, 57, 56, 59, 58, 61, 60, 63, 62],
    ![13, 12, 15, 14, 9, 8, 11, 10, 5, 4, 7, 6, 1, 0, 3, 2,
      29, 28, 31, 30, 25, 24, 27, 26, 21, 20, 23, 22, 17, 16, 19, 18,
      45, 44, 47, 46, 41, 40, 43, 42, 37, 36, 39, 38, 33, 32, 35, 34,
      61, 60, 63, 62, 57, 56, 59, 58, 53, 52, 55, 54, 49, 48, 51, 50],
    ![14, 15, 12, 13, 10, 11, 8, 9, 6, 7, 4, 5, 2, 3, 0, 1,
      30, 31, 28, 29, 26, 27, 24, 25, 22, 23, 20, 21, 18, 19, 16, 17,
      49, 48, 51, 50, 53, 52, 55, 54, 57, 56, 59, 58, 61, 60, 63, 62,
      33, 32, 35, 34, 37, 36, 39, 38, 41, 40, 43, 42, 45, 44, 47, 46],
    ![15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0,
      31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
      61, 60, 63, 62, 57, 56, 59, 58, 53, 52, 55, 54, 49, 48, 51, 50,
      45, 44, 47, 46, 41, 40, 43, 42, 37, 36, 39, 38, 33, 32, 35, 34],
    ![16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
      0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15,
      34, 35, 32, 33, 38, 39, 36, 37, 42, 43, 40, 41, 46, 47, 44, 45,
      50, 51, 48, 49, 54, 55, 52, 53, 58, 59, 56, 57, 62, 63, 60, 61],
    ![17, 16, 19, 18, 21, 20, 23, 22, 25, 24, 27, 26, 29, 28, 31, 30,
      1, 0, 3, 2, 5, 4, 7, 6, 9, 8, 11, 10, 13, 12, 15, 14,
      46, 47, 44, 45, 42, 43, 40, 41, 38, 39, 36, 37, 34, 35, 32, 33,
      62, 63, 60, 61, 58, 59, 56, 57, 54, 55, 52, 53, 50, 51, 48, 49],
    ![18, 19, 16, 17, 22, 23, 20, 21, 26, 27, 24, 25, 30, 31, 28, 29,
      2, 3, 0, 1, 6, 7, 4, 5, 10, 11, 8, 9, 14, 15, 12, 13,
      50, 51, 48, 49, 54, 55, 52, 53, 58, 59, 56, 57, 62, 63, 60, 61,
      34, 35, 32, 33, 38, 39, 36, 37, 42, 43, 40, 41, 46, 47, 44, 45],
    ![19, 18, 17, 16, 23, 22, 21, 20, 27, 26, 25, 24, 31, 30, 29, 28,
      3, 2, 1, 0, 7, 6, 5, 4, 11, 10, 9, 8, 15, 14, 13, 12,
      62, 63, 60, 61, 58, 59, 56, 57, 54, 55, 52, 53, 50, 51, 48, 49,
      46, 47, 44, 45, 42, 43, 40, 41, 38, 39, 36, 37, 34, 35, 32, 33],
    ![20, 21, 23, 22, 16, 17, 19, 18, 28, 29, 31, 30, 24, 25, 27, 26,
      8, 9, 11, 10, 12, 13, 15, 14, 0, 1, 3, 2, 4, 5, 7, 6,
      38, 39, 37, 36, 34, 35, 33, 32, 46, 47, 45, 44, 42, 43, 41, 40,
      58, 59, 57, 56, 62, 63, 61, 60, 50, 51, 49, 48, 54, 55, 53, 52],
    ![21, 20, 22, 23, 17, 16, 18, 19, 29, 28, 30, 31, 25, 24, 26, 27,
      9, 8, 10, 11, 13, 12, 14, 15, 1, 0, 2, 3, 5, 4, 6, 7,
      42, 43, 41, 40, 46, 47, 45, 44, 34, 35, 33, 32, 38, 39, 37, 36,
      54, 55, 53, 52, 50, 51, 49, 48, 62, 63, 61, 60, 58, 59, 57, 56],
    ![22, 23, 21, 20, 18, 19, 17, 16, 30, 31, 29, 28, 26, 27, 25, 24,
      10, 11, 9, 8, 14, 15, 13, 12, 2, 3, 1, 0, 6, 7, 5, 4,
      54, 55, 53, 52, 50, 51, 49, 48, 62, 63, 61, 60, 58, 59, 57, 56,
      42, 43, 41, 40, 46, 47, 45, 44, 34, 35, 33, 32, 38, 39, 37, 36],
    ![23, 22, 20, 21, 19, 18, 16, 17, 31, 30, 28, 29, 27, 26, 24, 25,
      11, 10, 8, 9, 15, 14, 12, 13, 3, 2, 0, 1, 7, 6, 4, 5,
      58, 59, 57, 56, 62, 63, 61, 60, 50, 51, 49, 48, 54, 55, 53, 52,
      38, 39, 37, 36, 34, 35, 33, 32, 46, 47, 45, 44, 42, 43, 41, 40],
    ![24, 25, 27, 26, 28, 29, 31, 30, 16, 17, 19, 18, 20, 21, 23, 22,
      4, 5, 7, 6, 0, 1, 3, 2, 12, 13, 15, 14, 8, 9, 11, 10,
      39, 38, 36, 37, 35, 34, 32, 33, 47, 46, 44, 45, 43, 42, 40, 41,
      59, 58, 56, 57, 63, 62, 60, 61, 51, 50, 48, 49, 55, 54, 52, 53],
    ![25, 24, 26, 27, 29, 28, 30, 31, 17, 16, 18, 19, 21, 20, 22, 23,
      5, 4, 6, 7, 1, 0, 2, 3, 13, 12, 14, 15, 9, 8, 10, 11,
      43, 42, 40, 41, 47, 46, 44, 45, 35, 34, 32, 33, 39, 38, 36, 37,
      55, 54, 52, 53, 51, 50, 48, 49, 63, 62, 60, 61, 59, 58, 56, 57],
    ![26, 27, 25, 24, 30, 31, 29, 28, 18, 19, 17, 16, 22, 23, 21, 20,
      6, 7, 5, 4, 2, 3, 1, 0, 14, 15, 13, 12, 10, 11, 9, 8,
      55, 54, 52, 53, 51, 50, 48, 49, 63, 62, 60, 61, 59, 58, 56, 57,
      43, 42, 40, 41, 47, 46, 44, 45, 35, 34, 32, 33, 39, 38, 36, 37],
    ![27, 26, 24, 25, 31, 30, 28, 29, 19, 18, 16, 17, 23, 22, 20, 21,
      7, 6, 4, 5, 3, 2, 0, 1, 15, 14, 12, 13, 11, 10, 8, 9,
      59, 58, 56, 57, 63, 62, 60, 61, 51, 50, 48, 49, 55, 54, 52, 53,
      39, 38, 36, 37, 35, 34, 32, 33, 47, 46, 44, 45, 43, 42, 40, 41],
    ![28, 29, 30, 31, 24, 25, 26, 27, 20, 21, 22, 23, 16, 17, 18, 19,
      12, 13, 14, 15, 8, 9, 10, 11, 4, 5, 6, 7, 0, 1, 2, 3,
      35, 34, 33, 32, 39, 38, 37, 36, 43, 42, 41, 40, 47, 46, 45, 44,
      51, 50, 49, 48, 55, 54, 53, 52, 59, 58, 57, 56, 63, 62, 61, 60],
    ![29, 28, 31, 30, 25, 24, 27, 26, 21, 20, 23, 22, 17, 16, 19, 18,
      13, 12, 15, 14, 9, 8, 11, 10, 5, 4, 7, 6, 1, 0, 3, 2,
      47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
      63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48],
    ![30, 31, 28, 29, 26, 27, 24, 25, 22, 23, 20, 21, 18, 19, 16, 17,
      14, 15, 12, 13, 10, 11, 8, 9, 6, 7, 4, 5, 2, 3, 0, 1,
      51, 50, 49, 48, 55, 54, 53, 52, 59, 58, 57, 56, 63, 62, 61, 60,
      35, 34, 33, 32, 39, 38, 37, 36, 43, 42, 41, 40, 47, 46, 45, 44],
    ![31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
      15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0,
      63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48,
      47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32],
    ![32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
      48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
      0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15,
      16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31],
    ![33, 32, 35, 34, 37, 36, 39, 38, 41, 40, 43, 42, 45, 44, 47, 46,
      49, 48, 51, 50, 53, 52, 55, 54, 57, 56, 59, 58, 61, 60, 63, 62,
      12, 13, 14, 15, 8, 9, 10, 11, 4, 5, 6, 7, 0, 1, 2, 3,
      28, 29, 30, 31, 24, 25, 26, 27, 20, 21, 22, 23, 16, 17, 18, 19],
    ![34, 35, 32, 33, 38, 39, 36, 37, 42, 43, 40, 41, 46, 47, 44, 45,
      50, 51, 48, 49, 54, 55, 52, 53, 58, 59, 56, 57, 62, 63, 60, 61,
      16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
      0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    ![35, 34, 33, 32, 39, 38, 37, 36, 43, 42, 41, 40, 47, 46, 45, 44,
      51, 50, 49, 48, 55, 54, 53, 52, 59, 58, 57, 56, 63, 62, 61, 60,
      28, 29, 30, 31, 24, 25, 26, 27, 20, 21, 22, 23, 16, 17, 18, 19,
      12, 13, 14, 15, 8, 9, 10, 11, 4, 5, 6, 7, 0, 1, 2, 3],
    ![36, 37, 39, 38, 32, 33, 35, 34, 44, 45, 47, 46, 40, 41, 43, 42,
      56, 57, 59, 58, 60, 61, 63, 62, 48, 49, 51, 50, 52, 53, 55, 54,
      4, 5, 7, 6, 0, 1, 3, 2, 12, 13, 15, 14, 8, 9, 11, 10,
      24, 25, 27, 26, 28, 29, 31, 30, 16, 17, 19, 18, 20, 21, 23, 22],
    ![37, 36, 38, 39, 33, 32, 34, 35, 45, 44, 46, 47, 41, 40, 42, 43,
      57, 56, 58, 59, 61, 60, 62, 63, 49, 48, 50, 51, 53, 52, 54, 55,
      8, 9, 11, 10, 12, 13, 15, 14, 0, 1, 3, 2, 4, 5, 7, 6,
      20, 21, 23, 22, 16, 17, 19, 18, 28, 29, 31, 30, 24, 25, 27, 26],
    ![38, 39, 37, 36, 34, 35, 33, 32, 46, 47, 45, 44, 42, 43, 41, 40,
      58, 59, 57, 56, 62, 63, 61, 60, 50, 51, 49, 48, 54, 55, 53, 52,
      20, 21, 23, 22, 16, 17, 19, 18, 28, 29, 31, 30, 24, 25, 27, 26,
      8, 9, 11, 10, 12, 13, 15, 14, 0, 1, 3, 2, 4, 5, 7, 6],
    ![39, 38, 36, 37, 35, 34, 32, 33, 47, 46, 44, 45, 43, 42, 40, 41,
      59, 58, 56, 57, 63, 62, 60, 61, 51, 50, 48, 49, 55, 54, 52, 53,
      24, 25, 27, 26, 28, 29, 31, 30, 16, 17, 19, 18, 20, 21, 23, 22,
      4, 5, 7, 6, 0, 1, 3, 2, 12, 13, 15, 14, 8, 9, 11, 10],
    ![40, 41, 43, 42, 44, 45, 47, 46, 32, 33, 35, 34, 36, 37, 39, 38,
      52, 53, 55, 54, 48, 49, 51, 50, 60, 61, 63, 62, 56, 57, 59, 58,
      5, 4, 6, 7, 1, 0, 2, 3, 13, 12, 14, 15, 9, 8, 10, 11,
      25, 24, 26, 27, 29, 28, 30, 31, 17, 16, 18, 19, 21, 20, 22, 23],
    ![41, 40, 42, 43, 45, 44, 46, 47, 33, 32, 34, 35, 37, 36, 38, 39,
      53, 52, 54, 55, 49, 48, 50, 51, 61, 60, 62, 63, 57, 56, 58, 59,
      9, 8, 10, 11, 13, 12, 14, 15, 1, 0, 2, 3, 5, 4, 6, 7,
      21, 20, 22, 23, 17, 16, 18, 19, 29, 28, 30, 31, 25, 24, 26, 27],
    ![42, 43, 41, 40, 46, 47, 45, 44, 34, 35, 33, 32, 38, 39, 37, 36,
      54, 55, 53, 52, 50, 51, 49, 48, 62, 63, 61, 60, 58, 59, 57, 56,
      21, 20, 22, 23, 17, 16, 18, 19, 29, 28, 30, 31, 25, 24, 26, 27,
      9, 8, 10, 11, 13, 12, 14, 15, 1, 0, 2, 3, 5, 4, 6, 7],
    ![43, 42, 40, 41, 47, 46, 44, 45, 35, 34, 32, 33, 39, 38, 36, 37,
      55, 54, 52, 53, 51, 50, 48, 49, 63, 62, 60, 61, 59, 58, 56, 57,
      25, 24, 26, 27, 29, 28, 30, 31, 17, 16, 18, 19, 21, 20, 22, 23,
      5, 4, 6, 7, 1, 0, 2, 3, 13, 12, 14, 15, 9, 8, 10, 11],
    ![44, 45, 46, 47, 40, 41, 42, 43, 36, 37, 38, 39, 32, 33, 34, 35,
      60, 61, 62, 63, 56, 57, 58, 59, 52, 53, 54, 55, 48, 49, 50, 51,
      1, 0, 3, 2, 5, 4, 7, 6, 9, 8, 11, 10, 13, 12, 15, 14,
      17, 16, 19, 18, 21, 20, 23, 22, 25, 24, 27, 26, 29, 28, 31, 30],
    ![45, 44, 47, 46, 41, 40, 43, 42, 37, 36, 39, 38, 33, 32, 35, 34,
      61, 60, 63, 62, 57, 56, 59, 58, 53, 52, 55, 54, 49, 48, 51, 50,
      13, 12, 15, 14, 9, 8, 11, 10, 5, 4, 7, 6, 1, 0, 3, 2,
      29, 28, 31, 30, 25, 24, 27, 26, 21, 20, 23, 22, 17, 16, 19, 18],
    ![46, 47, 44, 45, 42, 43, 40, 41, 38, 39, 36, 37, 34, 35, 32, 33,
      62, 63, 60, 61, 58, 59, 56, 57, 54, 55, 52, 53, 50, 51, 48, 49,
      17, 16, 19, 18, 21, 20, 23, 22, 25, 24, 27, 26, 29, 28, 31, 30,
      1, 0, 3, 2, 5, 4, 7, 6, 9, 8, 11, 10, 13, 12, 15, 14],
    ![47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
      63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48,
      29, 28, 31, 30, 25, 24, 27, 26, 21, 20, 23, 22, 17, 16, 19, 18,
      13, 12, 15, 14, 9, 8, 11, 10, 5, 4, 7, 6, 1, 0, 3, 2],
    ![48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
      32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
      2, 3, 0, 1, 6, 7, 4, 5, 10, 11, 8, 9, 14, 15, 12, 13,
      18, 19, 16, 17, 22, 23, 20, 21, 26, 27, 24, 25, 30, 31, 28, 29],
    ![49, 48, 51, 50, 53, 52, 55, 54, 57, 56, 59, 58, 61, 60, 63, 62,
      33, 32, 35, 34, 37, 36, 39, 38, 41, 40, 43, 42, 45, 44, 47, 46,
      14, 15, 12, 13, 10, 11, 8, 9, 6, 7, 4, 5, 2, 3, 0, 1,
      30, 31, 28, 29, 26, 27, 24, 25, 22, 23, 20, 21, 18, 19, 16, 17],
    ![50, 51, 48, 49, 54, 55, 52, 53, 58, 59, 56, 57, 62, 63, 60, 61,
      34, 35, 32, 33, 38, 39, 36, 37, 42, 43, 40, 41, 46, 47, 44, 45,
      18, 19, 16, 17, 22, 23, 20, 21, 26, 27, 24, 25, 30, 31, 28, 29,
      2, 3, 0, 1, 6, 7, 4, 5, 10, 11, 8, 9, 14, 15, 12, 13],
    ![51, 50, 49, 48, 55, 54, 53, 52, 59, 58, 57, 56, 63, 62, 61, 60,
      35, 34, 33, 32, 39, 38, 37, 36, 43, 42, 41, 40, 47, 46, 45, 44,
      30, 31, 28, 29, 26, 27, 24, 25, 22, 23, 20, 21, 18, 19, 16, 17,
      14, 15, 12, 13, 10, 11, 8, 9, 6, 7, 4, 5, 2, 3, 0, 1],
    ![52, 53, 55, 54, 48, 49, 51, 50, 60, 61, 63, 62, 56, 57, 59, 58,
      40, 41, 43, 42, 44, 45, 47, 46, 32, 33, 35, 34, 36, 37, 39, 38,
      6, 7, 5, 4, 2, 3, 1, 0, 14, 15, 13, 12, 10, 11, 9, 8,
      26, 27, 25, 24, 30, 31, 29, 28, 18, 19, 17, 16, 22, 23, 21, 20],
    ![53, 52, 54, 55, 49, 48, 50, 51, 61, 60, 62, 63, 57, 56, 58, 59,
      41, 40, 42, 43, 45, 44, 46, 47, 33, 32, 34, 35, 37, 36, 38, 39,
      10, 11, 9, 8, 14, 15, 13, 12, 2, 3, 1, 0, 6, 7, 5, 4,
      22, 23, 21, 20, 18, 19, 17, 16, 30, 31, 29, 28, 26, 27, 25, 24],
    ![54, 55, 53, 52, 50, 51, 49, 48, 62, 63, 61, 60, 58, 59, 57, 56,
      42, 43, 41, 40, 46, 47, 45, 44, 34, 35, 33, 32, 38, 39, 37, 36,
      22, 23, 21, 20, 18, 19, 17, 16, 30, 31, 29, 28, 26, 27, 25, 24,
      10, 11, 9, 8, 14, 15, 13, 12, 2, 3, 1, 0, 6, 7, 5, 4],
    ![55, 54, 52, 53, 51, 50, 48, 49, 63, 62, 60, 61, 59, 58, 56, 57,
      43, 42, 40, 41, 47, 46, 44, 45, 35, 34, 32, 33, 39, 38, 36, 37,
      26, 27, 25, 24, 30, 31, 29, 28, 18, 19, 17, 16, 22, 23, 21, 20,
      6, 7, 5, 4, 2, 3, 1, 0, 14, 15, 13, 12, 10, 11, 9, 8],
    ![56, 57, 59, 58, 60, 61, 63, 62, 48, 49, 51, 50, 52, 53, 55, 54,
      36, 37, 39, 38, 32, 33, 35, 34, 44, 45, 47, 46, 40, 41, 43, 42,
      7, 6, 4, 5, 3, 2, 0, 1, 15, 14, 12, 13, 11, 10, 8, 9,
      27, 26, 24, 25, 31, 30, 28, 29, 19, 18, 16, 17, 23, 22, 20, 21],
    ![57, 56, 58, 59, 61, 60, 62, 63, 49, 48, 50, 51, 53, 52, 54, 55,
      37, 36, 38, 39, 33, 32, 34, 35, 45, 44, 46, 47, 41, 40, 42, 43,
      11, 10, 8, 9, 15, 14, 12, 13, 3, 2, 0, 1, 7, 6, 4, 5,
      23, 22, 20, 21, 19, 18, 16, 17, 31, 30, 28, 29, 27, 26, 24, 25],
    ![58, 59, 57, 56, 62, 63, 61, 60, 50, 51, 49, 48, 54, 55, 53, 52,
      38, 39, 37, 36, 34, 35, 33, 32, 46, 47, 45, 44, 42, 43, 41, 40,
      23, 22, 20, 21, 19, 18, 16, 17, 31, 30, 28, 29, 27, 26, 24, 25,
      11, 10, 8, 9, 15, 14, 12, 13, 3, 2, 0, 1, 7, 6, 4, 5],
    ![59, 58, 56, 57, 63, 62, 60, 61, 51, 50, 48, 49, 55, 54, 52, 53,
      39, 38, 36, 37, 35, 34, 32, 33, 47, 46, 44, 45, 43, 42, 40, 41,
      27, 26, 24, 25, 31, 30, 28, 29, 19, 18, 16, 17, 23, 22, 20, 21,
      7, 6, 4, 5, 3, 2, 0, 1, 15, 14, 12, 13, 11, 10, 8, 9],
    ![60, 61, 62, 63, 56, 57, 58, 59, 52, 53, 54, 55, 48, 49, 50, 51,
      44, 45, 46, 47, 40, 41, 42, 43, 36, 37, 38, 39, 32, 33, 34, 35,
      3, 2, 1, 0, 7, 6, 5, 4, 11, 10, 9, 8, 15, 14, 13, 12,
      19, 18, 17, 16, 23, 22, 21, 20, 27, 26, 25, 24, 31, 30, 29, 28],
    ![61, 60, 63, 62, 57, 56, 59, 58, 53, 52, 55, 54, 49, 48, 51, 50,
      45, 44, 47, 46, 41, 40, 43, 42, 37, 36, 39, 38, 33, 32, 35, 34,
      15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0,
      31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16],
    ![62, 63, 60, 61, 58, 59, 56, 57, 54, 55, 52, 53, 50, 51, 48, 49,
      46, 47, 44, 45, 42, 43, 40, 41, 38, 39, 36, 37, 34, 35, 32, 33,
      19, 18, 17, 16, 23, 22, 21, 20, 27, 26, 25, 24, 31, 30, 29, 28,
      3, 2, 1, 0, 7, 6, 5, 4, 11, 10, 9, 8, 15, 14, 13, 12],
    ![63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48,
      47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
      31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
      15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]]

def row2ProductIndex (i j : Fin 64) : Fin 64 :=
  (row2ProductRows[i.val]'(by change i.val < 64; exact i.isLt)) j

/-- A fixed row needs one inverse and 64 product checks.
Separate proof declarations bound each kernel reduction's working set. -/
def row2CodedRowCheck (i : Fin 64) : Bool :=
  decide (composeCode8 (row2CodeAt (row2InverseIndex i))
    (row2CodeAt i) = 342391) &&
    (List.finRange 64).all (fun j ↦ decide
      (row2CodeAt (row2ProductIndex i j) =
        composeCode8 (row2CodeAt i) (row2CodeAt j)))

theorem row2_codedRow00 :
    row2CodedRowCheck 0 = true := by decide +kernel

theorem row2_codedRow01 :
    row2CodedRowCheck 1 = true := by decide +kernel

theorem row2_codedRow02 :
    row2CodedRowCheck 2 = true := by decide +kernel

theorem row2_codedRow03 :
    row2CodedRowCheck 3 = true := by decide +kernel

theorem row2_codedRow04 :
    row2CodedRowCheck 4 = true := by decide +kernel

theorem row2_codedRow05 :
    row2CodedRowCheck 5 = true := by decide +kernel

theorem row2_codedRow06 :
    row2CodedRowCheck 6 = true := by decide +kernel

theorem row2_codedRow07 :
    row2CodedRowCheck 7 = true := by decide +kernel

theorem row2_codedRow08 :
    row2CodedRowCheck 8 = true := by decide +kernel

theorem row2_codedRow09 :
    row2CodedRowCheck 9 = true := by decide +kernel

theorem row2_codedRow10 :
    row2CodedRowCheck 10 = true := by decide +kernel

theorem row2_codedRow11 :
    row2CodedRowCheck 11 = true := by decide +kernel

theorem row2_codedRow12 :
    row2CodedRowCheck 12 = true := by decide +kernel

theorem row2_codedRow13 :
    row2CodedRowCheck 13 = true := by decide +kernel

theorem row2_codedRow14 :
    row2CodedRowCheck 14 = true := by decide +kernel

theorem row2_codedRow15 :
    row2CodedRowCheck 15 = true := by decide +kernel

theorem row2_codedRow16 :
    row2CodedRowCheck 16 = true := by decide +kernel

theorem row2_codedRow17 :
    row2CodedRowCheck 17 = true := by decide +kernel

theorem row2_codedRow18 :
    row2CodedRowCheck 18 = true := by decide +kernel

theorem row2_codedRow19 :
    row2CodedRowCheck 19 = true := by decide +kernel

theorem row2_codedRow20 :
    row2CodedRowCheck 20 = true := by decide +kernel

theorem row2_codedRow21 :
    row2CodedRowCheck 21 = true := by decide +kernel

theorem row2_codedRow22 :
    row2CodedRowCheck 22 = true := by decide +kernel

theorem row2_codedRow23 :
    row2CodedRowCheck 23 = true := by decide +kernel

theorem row2_codedRow24 :
    row2CodedRowCheck 24 = true := by decide +kernel

theorem row2_codedRow25 :
    row2CodedRowCheck 25 = true := by decide +kernel

theorem row2_codedRow26 :
    row2CodedRowCheck 26 = true := by decide +kernel

theorem row2_codedRow27 :
    row2CodedRowCheck 27 = true := by decide +kernel

theorem row2_codedRow28 :
    row2CodedRowCheck 28 = true := by decide +kernel

theorem row2_codedRow29 :
    row2CodedRowCheck 29 = true := by decide +kernel

theorem row2_codedRow30 :
    row2CodedRowCheck 30 = true := by decide +kernel

theorem row2_codedRow31 :
    row2CodedRowCheck 31 = true := by decide +kernel

theorem row2_codedRow32 :
    row2CodedRowCheck 32 = true := by decide +kernel

theorem row2_codedRow33 :
    row2CodedRowCheck 33 = true := by decide +kernel

theorem row2_codedRow34 :
    row2CodedRowCheck 34 = true := by decide +kernel

theorem row2_codedRow35 :
    row2CodedRowCheck 35 = true := by decide +kernel

theorem row2_codedRow36 :
    row2CodedRowCheck 36 = true := by decide +kernel

theorem row2_codedRow37 :
    row2CodedRowCheck 37 = true := by decide +kernel

theorem row2_codedRow38 :
    row2CodedRowCheck 38 = true := by decide +kernel

theorem row2_codedRow39 :
    row2CodedRowCheck 39 = true := by decide +kernel

theorem row2_codedRow40 :
    row2CodedRowCheck 40 = true := by decide +kernel

theorem row2_codedRow41 :
    row2CodedRowCheck 41 = true := by decide +kernel

theorem row2_codedRow42 :
    row2CodedRowCheck 42 = true := by decide +kernel

theorem row2_codedRow43 :
    row2CodedRowCheck 43 = true := by decide +kernel

theorem row2_codedRow44 :
    row2CodedRowCheck 44 = true := by decide +kernel

theorem row2_codedRow45 :
    row2CodedRowCheck 45 = true := by decide +kernel

theorem row2_codedRow46 :
    row2CodedRowCheck 46 = true := by decide +kernel

theorem row2_codedRow47 :
    row2CodedRowCheck 47 = true := by decide +kernel

theorem row2_codedRow48 :
    row2CodedRowCheck 48 = true := by decide +kernel

theorem row2_codedRow49 :
    row2CodedRowCheck 49 = true := by decide +kernel

theorem row2_codedRow50 :
    row2CodedRowCheck 50 = true := by decide +kernel

theorem row2_codedRow51 :
    row2CodedRowCheck 51 = true := by decide +kernel

theorem row2_codedRow52 :
    row2CodedRowCheck 52 = true := by decide +kernel

theorem row2_codedRow53 :
    row2CodedRowCheck 53 = true := by decide +kernel

theorem row2_codedRow54 :
    row2CodedRowCheck 54 = true := by decide +kernel

theorem row2_codedRow55 :
    row2CodedRowCheck 55 = true := by decide +kernel

theorem row2_codedRow56 :
    row2CodedRowCheck 56 = true := by decide +kernel

theorem row2_codedRow57 :
    row2CodedRowCheck 57 = true := by decide +kernel

theorem row2_codedRow58 :
    row2CodedRowCheck 58 = true := by decide +kernel

theorem row2_codedRow59 :
    row2CodedRowCheck 59 = true := by decide +kernel

theorem row2_codedRow60 :
    row2CodedRowCheck 60 = true := by decide +kernel

theorem row2_codedRow61 :
    row2CodedRowCheck 61 = true := by decide +kernel

theorem row2_codedRow62 :
    row2CodedRowCheck 62 = true := by decide +kernel

theorem row2_codedRow63 :
    row2CodedRowCheck 63 = true := by decide +kernel

/-- Assemble the separately checked rows without repeating their calculations. -/
theorem row2_codedClosure :
    codedIndexedClosureCheck 64 342391 composeCode8 row2CodeAt 0
      row2InverseIndex row2ProductIndex = true := by
  apply Bool.and_eq_true_iff.mpr
  refine ⟨by decide +kernel, List.all_eq_true.mpr ?_⟩
  intro i _
  change row2CodedRowCheck i = true
  fin_cases i
  · exact row2_codedRow00
  · exact row2_codedRow01
  · exact row2_codedRow02
  · exact row2_codedRow03
  · exact row2_codedRow04
  · exact row2_codedRow05
  · exact row2_codedRow06
  · exact row2_codedRow07
  · exact row2_codedRow08
  · exact row2_codedRow09
  · exact row2_codedRow10
  · exact row2_codedRow11
  · exact row2_codedRow12
  · exact row2_codedRow13
  · exact row2_codedRow14
  · exact row2_codedRow15
  · exact row2_codedRow16
  · exact row2_codedRow17
  · exact row2_codedRow18
  · exact row2_codedRow19
  · exact row2_codedRow20
  · exact row2_codedRow21
  · exact row2_codedRow22
  · exact row2_codedRow23
  · exact row2_codedRow24
  · exact row2_codedRow25
  · exact row2_codedRow26
  · exact row2_codedRow27
  · exact row2_codedRow28
  · exact row2_codedRow29
  · exact row2_codedRow30
  · exact row2_codedRow31
  · exact row2_codedRow32
  · exact row2_codedRow33
  · exact row2_codedRow34
  · exact row2_codedRow35
  · exact row2_codedRow36
  · exact row2_codedRow37
  · exact row2_codedRow38
  · exact row2_codedRow39
  · exact row2_codedRow40
  · exact row2_codedRow41
  · exact row2_codedRow42
  · exact row2_codedRow43
  · exact row2_codedRow44
  · exact row2_codedRow45
  · exact row2_codedRow46
  · exact row2_codedRow47
  · exact row2_codedRow48
  · exact row2_codedRow49
  · exact row2_codedRow50
  · exact row2_codedRow51
  · exact row2_codedRow52
  · exact row2_codedRow53
  · exact row2_codedRow54
  · exact row2_codedRow55
  · exact row2_codedRow56
  · exact row2_codedRow57
  · exact row2_codedRow58
  · exact row2_codedRow59
  · exact row2_codedRow60
  · exact row2_codedRow61
  · exact row2_codedRow62
  · exact row2_codedRow63

/-- Arithmetic correctness transfers back to the actual group table. -/
theorem row2_indexedClosure :
    indexedClosureCheck 64 row2At 0
      row2InverseIndex row2ProductIndex = true := by
  apply indexedClosureCheck_of_codedIndexedClosureCheck rowCode rowCode_injective
    composeCode8 rowCode_mul row2At row2CodeAt row2CodeAt_correct
    0 row2InverseIndex row2ProductIndex
  simpa only [rowCode_one] using row2_codedClosure

theorem row2_closed : subgroupCheck row2 = true := by
  exact subgroupCheck_finsetOfNodupList_of_arrayIndexedClosureCheck
    row2Elements row2Elements_nodup
    (0 : Fin 64) row2InverseIndex row2ProductIndex row2_indexedClosure

theorem row2_card_factorization :
    row2.card = 2 ^ (Nat.card G).factorization 2 := by
  rw [row2_card, card_G]
  decide +kernel

noncomputable def sylow2 : Sylow 2 G :=
  checkedSylow row2 row2_closed row2_card_factorization

@[simp] theorem mem_sylow2_iff (g : G) :
    g ∈ sylow2 ↔ g ∈ row2 := Iff.rfl

theorem sylow2_card : Nat.card sylow2 = 64 := by
  change Nat.card (checkedSubgroup row2 row2_closed) = 64
  exact (card_checkedSubgroup row2 row2_closed).trans row2_card

local instance : Fact (Nat.Prime 3) := ⟨by decide⟩

def p3e0Perm : Equiv.Perm (Fin 8) where
  toFun := ![0, 1, 2, 3, 4, 5, 6, 7]
  invFun := ![0, 1, 2, 3, 4, 5, 6, 7]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p3e0 : G := ⟨p3e0Perm, by
  change Equiv.Perm.sign p3e0Perm = 1
  decide +kernel⟩

def p3e1Perm : Equiv.Perm (Fin 8) where
  toFun := ![0, 1, 2, 4, 5, 3, 6, 7]
  invFun := ![0, 1, 2, 5, 3, 4, 6, 7]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p3e1 : G := ⟨p3e1Perm, by
  change Equiv.Perm.sign p3e1Perm = 1
  decide +kernel⟩

def p3e2Perm : Equiv.Perm (Fin 8) where
  toFun := ![0, 1, 2, 5, 3, 4, 6, 7]
  invFun := ![0, 1, 2, 4, 5, 3, 6, 7]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p3e2 : G := ⟨p3e2Perm, by
  change Equiv.Perm.sign p3e2Perm = 1
  decide +kernel⟩

def p3e3Perm : Equiv.Perm (Fin 8) where
  toFun := ![1, 2, 0, 3, 4, 5, 6, 7]
  invFun := ![2, 0, 1, 3, 4, 5, 6, 7]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p3e3 : G := ⟨p3e3Perm, by
  change Equiv.Perm.sign p3e3Perm = 1
  decide +kernel⟩

def p3e4Perm : Equiv.Perm (Fin 8) where
  toFun := ![1, 2, 0, 4, 5, 3, 6, 7]
  invFun := ![2, 0, 1, 5, 3, 4, 6, 7]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p3e4 : G := ⟨p3e4Perm, by
  change Equiv.Perm.sign p3e4Perm = 1
  decide +kernel⟩

def p3e5Perm : Equiv.Perm (Fin 8) where
  toFun := ![1, 2, 0, 5, 3, 4, 6, 7]
  invFun := ![2, 0, 1, 4, 5, 3, 6, 7]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p3e5 : G := ⟨p3e5Perm, by
  change Equiv.Perm.sign p3e5Perm = 1
  decide +kernel⟩

def p3e6Perm : Equiv.Perm (Fin 8) where
  toFun := ![2, 0, 1, 3, 4, 5, 6, 7]
  invFun := ![1, 2, 0, 3, 4, 5, 6, 7]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p3e6 : G := ⟨p3e6Perm, by
  change Equiv.Perm.sign p3e6Perm = 1
  decide +kernel⟩

def p3e7Perm : Equiv.Perm (Fin 8) where
  toFun := ![2, 0, 1, 4, 5, 3, 6, 7]
  invFun := ![1, 2, 0, 5, 3, 4, 6, 7]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p3e7 : G := ⟨p3e7Perm, by
  change Equiv.Perm.sign p3e7Perm = 1
  decide +kernel⟩

def p3e8Perm : Equiv.Perm (Fin 8) where
  toFun := ![2, 0, 1, 5, 3, 4, 6, 7]
  invFun := ![1, 2, 0, 4, 5, 3, 6, 7]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p3e8 : G := ⟨p3e8Perm, by
  change Equiv.Perm.sign p3e8Perm = 1
  decide +kernel⟩

/-- The sorted canonical subgroup carrier, before forming a finite set. -/
def row3Elements : List G :=
  [p3e0, p3e1, p3e2, p3e3, p3e4, p3e5, p3e6, p3e7,
   p3e8]

/-- All row entries after the first, which is the identity. -/
def row3Probes : List G :=
  [p3e1, p3e2, p3e3, p3e4, p3e5, p3e6, p3e7, p3e8]

theorem p3e0_eq_one : p3e0 = 1 := by decide +kernel

theorem row3Elements_eq_one_cons :
    row3Elements = 1 :: row3Probes := by
  rw [← p3e0_eq_one]
  rfl

/-- Cached literal base-8 codes for the row elements. -/
def row3Codes : List ℕ :=
  [342391, 346871, 350007, 2636151, 2640631, 2643767, 4241783, 4246263,
   4249399]

theorem row3Codes_eq :
    row3Codes = row3Elements.map (fun g ↦ permutationCode g.val) := by
  decide +kernel

theorem row3Elements_nodup : row3Elements.Nodup :=
  nodup_of_code_isChain (fun g : G ↦ permutationCode g.val) (by decide +kernel)

def row3 : Finset G :=
  finsetOfNodupList row3Elements row3Elements_nodup

theorem row3_card : row3.card = 9 := by
  change row3Elements.length = 9
  decide +kernel

/-- Array access keeps indexed closure verification linear in table size. -/
def row3Array : Array G := row3Elements.toArray

def row3At (i : Fin 9) : G :=
  row3Array[i.val]'(by change i.val < 9; exact i.isLt)

/-- Cached arithmetic row; products never reconstruct its group elements. -/
def row3CodeArray : Array ℕ := row3Codes.toArray

def row3CodeAt (i : Fin 9) : ℕ :=
  row3CodeArray[i.val]'(by change i.val < 9; exact i.isLt)

theorem row3CodeAt_correct :
    ∀ i, rowCode (row3At i) = row3CodeAt i := by
  decide +kernel

def row3InverseIndices : Array (Fin 9) :=
  #[0, 2, 1, 6, 8, 7, 3, 5,
   4]

def row3InverseIndex (i : Fin 9) : Fin 9 :=
  row3InverseIndices[i.val]'(by change i.val < 9; exact i.isLt)

/-- Two-level multiplication indices keep each lookup bounded by row order. -/
def row3ProductRows : Array (Fin 9 → Fin 9) :=
  #[![0, 1, 2, 3, 4, 5, 6, 7, 8],
    ![1, 2, 0, 4, 5, 3, 7, 8, 6],
    ![2, 0, 1, 5, 3, 4, 8, 6, 7],
    ![3, 4, 5, 6, 7, 8, 0, 1, 2],
    ![4, 5, 3, 7, 8, 6, 1, 2, 0],
    ![5, 3, 4, 8, 6, 7, 2, 0, 1],
    ![6, 7, 8, 0, 1, 2, 3, 4, 5],
    ![7, 8, 6, 1, 2, 0, 4, 5, 3],
    ![8, 6, 7, 2, 0, 1, 5, 3, 4]]

def row3ProductIndex (i j : Fin 9) : Fin 9 :=
  (row3ProductRows[i.val]'(by change i.val < 9; exact i.isLt)) j

/-- The multiplication-table calculation uses natural numbers only. -/
theorem row3_codedClosure :
    codedIndexedClosureCheck 9 342391 composeCode8 row3CodeAt 0
      row3InverseIndex row3ProductIndex = true := by
  decide +kernel

/-- Arithmetic correctness transfers back to the actual group table. -/
theorem row3_indexedClosure :
    indexedClosureCheck 9 row3At 0
      row3InverseIndex row3ProductIndex = true := by
  apply indexedClosureCheck_of_codedIndexedClosureCheck rowCode rowCode_injective
    composeCode8 rowCode_mul row3At row3CodeAt row3CodeAt_correct
    0 row3InverseIndex row3ProductIndex
  simpa only [rowCode_one] using row3_codedClosure

theorem row3_closed : subgroupCheck row3 = true := by
  exact subgroupCheck_finsetOfNodupList_of_arrayIndexedClosureCheck
    row3Elements row3Elements_nodup
    (0 : Fin 9) row3InverseIndex row3ProductIndex row3_indexedClosure

theorem row3_card_factorization :
    row3.card = 3 ^ (Nat.card G).factorization 3 := by
  rw [row3_card, card_G]
  decide +kernel

noncomputable def sylow3 : Sylow 3 G :=
  checkedSylow row3 row3_closed row3_card_factorization

@[simp] theorem mem_sylow3_iff (g : G) :
    g ∈ sylow3 ↔ g ∈ row3 := Iff.rfl

theorem sylow3_card : Nat.card sylow3 = 9 := by
  change Nat.card (checkedSubgroup row3 row3_closed) = 9
  exact (card_checkedSubgroup row3 row3_closed).trans row3_card

local instance : Fact (Nat.Prime 5) := ⟨by decide⟩

def p5e0Perm : Equiv.Perm (Fin 8) where
  toFun := ![0, 1, 2, 3, 4, 5, 6, 7]
  invFun := ![0, 1, 2, 3, 4, 5, 6, 7]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p5e0 : G := ⟨p5e0Perm, by
  change Equiv.Perm.sign p5e0Perm = 1
  decide +kernel⟩

def p5e1Perm : Equiv.Perm (Fin 8) where
  toFun := ![1, 2, 3, 4, 0, 5, 6, 7]
  invFun := ![4, 0, 1, 2, 3, 5, 6, 7]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p5e1 : G := ⟨p5e1Perm, by
  change Equiv.Perm.sign p5e1Perm = 1
  decide +kernel⟩

def p5e2Perm : Equiv.Perm (Fin 8) where
  toFun := ![2, 3, 4, 0, 1, 5, 6, 7]
  invFun := ![3, 4, 0, 1, 2, 5, 6, 7]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p5e2 : G := ⟨p5e2Perm, by
  change Equiv.Perm.sign p5e2Perm = 1
  decide +kernel⟩

def p5e3Perm : Equiv.Perm (Fin 8) where
  toFun := ![3, 4, 0, 1, 2, 5, 6, 7]
  invFun := ![2, 3, 4, 0, 1, 5, 6, 7]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p5e3 : G := ⟨p5e3Perm, by
  change Equiv.Perm.sign p5e3Perm = 1
  decide +kernel⟩

def p5e4Perm : Equiv.Perm (Fin 8) where
  toFun := ![4, 0, 1, 2, 3, 5, 6, 7]
  invFun := ![1, 2, 3, 4, 0, 5, 6, 7]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p5e4 : G := ⟨p5e4Perm, by
  change Equiv.Perm.sign p5e4Perm = 1
  decide +kernel⟩

/-- The sorted canonical subgroup carrier, before forming a finite set. -/
def row5Elements : List G :=
  [p5e0, p5e1, p5e2, p5e3, p5e4]

/-- All row entries after the first, which is the identity. -/
def row5Probes : List G :=
  [p5e1, p5e2, p5e3, p5e4]

theorem p5e0_eq_one : p5e0 = 1 := by decide +kernel

theorem row5Elements_eq_one_cons :
    row5Elements = 1 :: row5Probes := by
  rw [← p5e0_eq_one]
  rfl

/-- Cached literal base-8 codes for the row elements. -/
def row5Codes : List ℕ :=
  [342391, 2736503, 5112695, 7345527, 8431479]

theorem row5Codes_eq :
    row5Codes = row5Elements.map (fun g ↦ permutationCode g.val) := by
  decide +kernel

theorem row5Elements_nodup : row5Elements.Nodup :=
  nodup_of_code_isChain (fun g : G ↦ permutationCode g.val) (by decide +kernel)

def row5 : Finset G :=
  finsetOfNodupList row5Elements row5Elements_nodup

theorem row5_card : row5.card = 5 := by
  change row5Elements.length = 5
  decide +kernel

/-- Array access keeps indexed closure verification linear in table size. -/
def row5Array : Array G := row5Elements.toArray

def row5At (i : Fin 5) : G :=
  row5Array[i.val]'(by change i.val < 5; exact i.isLt)

/-- Cached arithmetic row; products never reconstruct its group elements. -/
def row5CodeArray : Array ℕ := row5Codes.toArray

def row5CodeAt (i : Fin 5) : ℕ :=
  row5CodeArray[i.val]'(by change i.val < 5; exact i.isLt)

theorem row5CodeAt_correct :
    ∀ i, rowCode (row5At i) = row5CodeAt i := by
  decide +kernel

def row5InverseIndices : Array (Fin 5) :=
  #[0, 4, 3, 2, 1]

def row5InverseIndex (i : Fin 5) : Fin 5 :=
  row5InverseIndices[i.val]'(by change i.val < 5; exact i.isLt)

/-- Two-level multiplication indices keep each lookup bounded by row order. -/
def row5ProductRows : Array (Fin 5 → Fin 5) :=
  #[![0, 1, 2, 3, 4],
    ![1, 2, 3, 4, 0],
    ![2, 3, 4, 0, 1],
    ![3, 4, 0, 1, 2],
    ![4, 0, 1, 2, 3]]

def row5ProductIndex (i j : Fin 5) : Fin 5 :=
  (row5ProductRows[i.val]'(by change i.val < 5; exact i.isLt)) j

/-- The multiplication-table calculation uses natural numbers only. -/
theorem row5_codedClosure :
    codedIndexedClosureCheck 5 342391 composeCode8 row5CodeAt 0
      row5InverseIndex row5ProductIndex = true := by
  decide +kernel

/-- Arithmetic correctness transfers back to the actual group table. -/
theorem row5_indexedClosure :
    indexedClosureCheck 5 row5At 0
      row5InverseIndex row5ProductIndex = true := by
  apply indexedClosureCheck_of_codedIndexedClosureCheck rowCode rowCode_injective
    composeCode8 rowCode_mul row5At row5CodeAt row5CodeAt_correct
    0 row5InverseIndex row5ProductIndex
  simpa only [rowCode_one] using row5_codedClosure

theorem row5_closed : subgroupCheck row5 = true := by
  exact subgroupCheck_finsetOfNodupList_of_arrayIndexedClosureCheck
    row5Elements row5Elements_nodup
    (0 : Fin 5) row5InverseIndex row5ProductIndex row5_indexedClosure

theorem row5_card_factorization :
    row5.card = 5 ^ (Nat.card G).factorization 5 := by
  rw [row5_card, card_G]
  decide +kernel

noncomputable def sylow5 : Sylow 5 G :=
  checkedSylow row5 row5_closed row5_card_factorization

@[simp] theorem mem_sylow5_iff (g : G) :
    g ∈ sylow5 ↔ g ∈ row5 := Iff.rfl

theorem sylow5_card : Nat.card sylow5 = 5 := by
  change Nat.card (checkedSubgroup row5 row5_closed) = 5
  exact (card_checkedSubgroup row5 row5_closed).trans row5_card

local instance : Fact (Nat.Prime 7) := ⟨by decide⟩

def p7e0Perm : Equiv.Perm (Fin 8) where
  toFun := ![0, 1, 2, 3, 4, 5, 6, 7]
  invFun := ![0, 1, 2, 3, 4, 5, 6, 7]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p7e0 : G := ⟨p7e0Perm, by
  change Equiv.Perm.sign p7e0Perm = 1
  decide +kernel⟩

def p7e1Perm : Equiv.Perm (Fin 8) where
  toFun := ![1, 2, 3, 4, 5, 6, 0, 7]
  invFun := ![6, 0, 1, 2, 3, 4, 5, 7]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p7e1 : G := ⟨p7e1Perm, by
  change Equiv.Perm.sign p7e1Perm = 1
  decide +kernel⟩

def p7e2Perm : Equiv.Perm (Fin 8) where
  toFun := ![2, 3, 4, 5, 6, 0, 1, 7]
  invFun := ![5, 6, 0, 1, 2, 3, 4, 7]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p7e2 : G := ⟨p7e2Perm, by
  change Equiv.Perm.sign p7e2Perm = 1
  decide +kernel⟩

def p7e3Perm : Equiv.Perm (Fin 8) where
  toFun := ![3, 4, 5, 6, 0, 1, 2, 7]
  invFun := ![4, 5, 6, 0, 1, 2, 3, 7]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p7e3 : G := ⟨p7e3Perm, by
  change Equiv.Perm.sign p7e3Perm = 1
  decide +kernel⟩

def p7e4Perm : Equiv.Perm (Fin 8) where
  toFun := ![4, 5, 6, 0, 1, 2, 3, 7]
  invFun := ![3, 4, 5, 6, 0, 1, 2, 7]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p7e4 : G := ⟨p7e4Perm, by
  change Equiv.Perm.sign p7e4Perm = 1
  decide +kernel⟩

def p7e5Perm : Equiv.Perm (Fin 8) where
  toFun := ![5, 6, 0, 1, 2, 3, 4, 7]
  invFun := ![2, 3, 4, 5, 6, 0, 1, 7]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p7e5 : G := ⟨p7e5Perm, by
  change Equiv.Perm.sign p7e5Perm = 1
  decide +kernel⟩

def p7e6Perm : Equiv.Perm (Fin 8) where
  toFun := ![6, 0, 1, 2, 3, 4, 5, 7]
  invFun := ![1, 2, 3, 4, 5, 6, 0, 7]
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def p7e6 : G := ⟨p7e6Perm, by
  change Equiv.Perm.sign p7e6Perm = 1
  decide +kernel⟩

/-- The sorted canonical subgroup carrier, before forming a finite set. -/
def row7Elements : List G :=
  [p7e0, p7e1, p7e2, p7e3, p7e4, p7e5, p7e6]

/-- All row entries after the first, which is the identity. -/
def row7Probes : List G :=
  [p7e1, p7e2, p7e3, p7e4, p7e5, p7e6]

theorem p7e0_eq_one : p7e0 = 1 := by decide +kernel

theorem row7Elements_eq_one_cons :
    row7Elements = 1 :: row7Probes := by
  rw [← p7e0_eq_one]
  rfl

/-- Cached literal base-8 codes for the row elements. -/
def row7Codes : List ℕ :=
  [342391, 2739079, 5135375, 7528535, 9896607, 12063975, 12625711]

theorem row7Codes_eq :
    row7Codes = row7Elements.map (fun g ↦ permutationCode g.val) := by
  decide +kernel

theorem row7Elements_nodup : row7Elements.Nodup :=
  nodup_of_code_isChain (fun g : G ↦ permutationCode g.val) (by decide +kernel)

def row7 : Finset G :=
  finsetOfNodupList row7Elements row7Elements_nodup

theorem row7_card : row7.card = 7 := by
  change row7Elements.length = 7
  decide +kernel

/-- Array access keeps indexed closure verification linear in table size. -/
def row7Array : Array G := row7Elements.toArray

def row7At (i : Fin 7) : G :=
  row7Array[i.val]'(by change i.val < 7; exact i.isLt)

/-- Cached arithmetic row; products never reconstruct its group elements. -/
def row7CodeArray : Array ℕ := row7Codes.toArray

def row7CodeAt (i : Fin 7) : ℕ :=
  row7CodeArray[i.val]'(by change i.val < 7; exact i.isLt)

theorem row7CodeAt_correct :
    ∀ i, rowCode (row7At i) = row7CodeAt i := by
  decide +kernel

def row7InverseIndices : Array (Fin 7) :=
  #[0, 6, 5, 4, 3, 2, 1]

def row7InverseIndex (i : Fin 7) : Fin 7 :=
  row7InverseIndices[i.val]'(by change i.val < 7; exact i.isLt)

/-- Two-level multiplication indices keep each lookup bounded by row order. -/
def row7ProductRows : Array (Fin 7 → Fin 7) :=
  #[![0, 1, 2, 3, 4, 5, 6],
    ![1, 2, 3, 4, 5, 6, 0],
    ![2, 3, 4, 5, 6, 0, 1],
    ![3, 4, 5, 6, 0, 1, 2],
    ![4, 5, 6, 0, 1, 2, 3],
    ![5, 6, 0, 1, 2, 3, 4],
    ![6, 0, 1, 2, 3, 4, 5]]

def row7ProductIndex (i j : Fin 7) : Fin 7 :=
  (row7ProductRows[i.val]'(by change i.val < 7; exact i.isLt)) j

/-- The multiplication-table calculation uses natural numbers only. -/
theorem row7_codedClosure :
    codedIndexedClosureCheck 7 342391 composeCode8 row7CodeAt 0
      row7InverseIndex row7ProductIndex = true := by
  decide +kernel

/-- Arithmetic correctness transfers back to the actual group table. -/
theorem row7_indexedClosure :
    indexedClosureCheck 7 row7At 0
      row7InverseIndex row7ProductIndex = true := by
  apply indexedClosureCheck_of_codedIndexedClosureCheck rowCode rowCode_injective
    composeCode8 rowCode_mul row7At row7CodeAt row7CodeAt_correct
    0 row7InverseIndex row7ProductIndex
  simpa only [rowCode_one] using row7_codedClosure

theorem row7_closed : subgroupCheck row7 = true := by
  exact subgroupCheck_finsetOfNodupList_of_arrayIndexedClosureCheck
    row7Elements row7Elements_nodup
    (0 : Fin 7) row7InverseIndex row7ProductIndex row7_indexedClosure

theorem row7_card_factorization :
    row7.card = 7 ^ (Nat.card G).factorization 7 := by
  rw [row7_card, card_G]
  decide +kernel

noncomputable def sylow7 : Sylow 7 G :=
  checkedSylow row7 row7_closed row7_card_factorization

@[simp] theorem mem_sylow7_iff (g : G) :
    g ∈ sylow7 ↔ g ∈ row7 := Iff.rfl

theorem sylow7_card : Nat.card sylow7 = 7 := by
  change Nat.card (checkedSubgroup row7 row7_closed) = 7
  exact (card_checkedSubgroup row7 row7_closed).trans row7_card

end LisiSabatini.FiniteCertificates.A8Rows
