#!/usr/bin/env python3
"""Generate A8 Sylow-row literals and indexed multiplication certificates.

Python supplies candidate tables only. Lean checks the permutation identities,
all indexed products and inverses, row cardinalities, and Sylow maximality.
"""

from __future__ import annotations

import argparse
from hashlib import sha256
import json
from pathlib import Path


def vector(values: list[int] | list[str]) -> str:
    pieces = [", ".join(map(str, values[i:i + 16]))
              for i in range(0, len(values), 16)]
    return "![" + ",\n      ".join(pieces) + "]"


def literal_list(values: list[int] | list[str], width: int = 8, array: bool = False) -> str:
    pieces = [", ".join(map(str, values[i:i + width])) for i in range(0, len(values), width)]
    return ("#[" if array else "[") + ",\n   ".join(pieces) + "]"


def perm_code(images: list[int]) -> int:
    result = 0
    for image in images:
        result = result * 8 + image
    return result


def coded_closure(prefix: str, size: int) -> list[str]:
    statement = [
        f"theorem {prefix}_codedClosure :",
        f"    codedIndexedClosureCheck {size} 342391 composeCode8 {prefix}CodeAt 0",
        f"      {prefix}InverseIndex {prefix}ProductIndex = true := by",
    ]
    if size != 64:
        return [
            "/-- The multiplication-table calculation uses natural numbers only. -/",
            *statement, "  decide +kernel", "",
        ]
    lines = [
        "/-- A fixed row needs one inverse and 64 product checks.",
        "Separate proof declarations bound each kernel reduction's working set. -/",
        f"def {prefix}CodedRowCheck (i : Fin {size}) : Bool :=",
        f"  decide (composeCode8 ({prefix}CodeAt ({prefix}InverseIndex i))",
        f"    ({prefix}CodeAt i) = 342391) &&",
        f"    (List.finRange {size}).all (fun j ↦ decide",
        f"      ({prefix}CodeAt ({prefix}ProductIndex i j) =",
        f"        composeCode8 ({prefix}CodeAt i) ({prefix}CodeAt j)))", "",
    ]
    for index in range(size):
        lines.extend([
            f"theorem {prefix}_codedRow{index:02d} :",
            f"    {prefix}CodedRowCheck {index} = true := by decide +kernel", "",
        ])
    lines.extend([
        "/-- Assemble the separately checked rows without repeating their calculations. -/",
        *statement,
        "  apply Bool.and_eq_true_iff.mpr",
        "  refine ⟨by decide +kernel, List.all_eq_true.mpr ?_⟩",
        "  intro i _",
        f"  change {prefix}CodedRowCheck i = true",
        "  fin_cases i",
        *(f"  · exact {prefix}_codedRow{index:02d}" for index in range(size)), "",
    ])
    return lines


def generate(data: dict, selected_primes: list[int]) -> str:
    lines = [
        "module", "",
        "public import LisiSabatini.FiniteCertificates.CodedIndexedTable",
        "public import LisiSabatini.FiniteCertificates.PermutationCodeArithmetic", "",
        "/-!",
        "# Indexed finite Sylow certificates for A8", "",
        "Generated by generate_a8_rows.py from A8Data.json. Python supplies",
        "candidate literals. All permutation, product, inverse and cardinality",
        "acceptance proofs are checked by the Lean kernel.",
        "-/", "",
        "@[expose] public section", "",
        "namespace LisiSabatini.FiniteCertificates.A8Rows", "",
        "abbrev G := alternatingGroup (Fin 8)", "",
        "local instance : DecidableEq G := alternatingCodeDecidableEq_fin8", "",
        "set_option maxRecDepth 100000",
        "",
        "/-- The injective arithmetic code used only while checking row tables. -/",
        "def rowCode (g : G) : ℕ := permutationCode g.val", "",
        "theorem rowCode_injective : Function.Injective rowCode := by",
        "  intro g h heq",
        "  exact Subtype.ext (permutationCode_injective_fin8 heq)", "",
        "theorem rowCode_mul (g h : G) :",
        "    rowCode (g * h) = composeCode8 (rowCode g) (rowCode h) :=",
        "  permutationCode_mul_fin8 g.val h.val", "",
        "theorem rowCode_one : rowCode 1 = 342391 := by decide +kernel", "",
        "theorem card_G : Nat.card G = 20160 := by",
        "  rw [nat_card_alternatingGroup]",
        "  norm_num",
        "  decide +kernel", "",
    ]

    for row in data["rows"]:
        prime, size = row["prime"], row["order"]
        if prime not in selected_primes:
            continue
        lines.extend([
            f"local instance : Fact (Nat.Prime {prime}) := ⟨by decide⟩", "",
        ])
        elements = [element["images"] for element in row["elements"]]
        lookup = {tuple(element): index for index, element in enumerate(elements)}
        assert len(lookup) == size and elements == sorted(elements)
        assert elements[0] == list(range(8))
        inverses = [[element.index(i) for i in range(8)] for element in elements]
        inverse_indices = [lookup[tuple(inverse)] for inverse in inverses]
        product_indices = [lookup[tuple(a[b[i]] for i in range(8))]
                           for a in elements for b in elements]
        product_rows = [vector(product_indices[i:i + size])
                        for i in range(0, len(product_indices), size)]
        codes = list(map(perm_code, elements))
        assert all(a < b for a, b in zip(codes, codes[1:]))

        for index, (images, inverse) in enumerate(zip(elements, inverses)):
            name = f"p{prime}e{index}"
            lines.extend([
                f"def {name}Perm : Equiv.Perm (Fin 8) where",
                f"  toFun := {vector(images)}",
                f"  invFun := {vector(inverse)}",
                "  left_inv := by decide +kernel",
                "  right_inv := by decide +kernel", "",
                f"def {name} : G := ⟨{name}Perm, by",
                f"  change Equiv.Perm.sign {name}Perm = 1",
                "  decide +kernel⟩", "",
            ])

        prefix = f"row{prime}"
        names = [f"p{prime}e{i}" for i in range(size)]
        lines.extend([
            "/-- The sorted canonical subgroup carrier, before forming a finite set. -/",
            f"def {prefix}Elements : List G :=", "  " + literal_list(names), "",
            "/-- All row entries after the first, which is the identity. -/",
            f"def {prefix}Probes : List G :=", "  " + literal_list(names[1:]), "",
            f"theorem p{prime}e0_eq_one : p{prime}e0 = 1 := by decide +kernel", "",
            f"theorem {prefix}Elements_eq_one_cons :",
            f"    {prefix}Elements = 1 :: {prefix}Probes := by",
            f"  rw [← p{prime}e0_eq_one]",
            "  rfl", "",
            "/-- Cached literal base-8 codes for the row elements. -/",
            f"def {prefix}Codes : List ℕ :=", "  " + literal_list(codes), "",
            f"theorem {prefix}Codes_eq :",
            f"    {prefix}Codes = {prefix}Elements.map (fun g ↦ permutationCode g.val) := by",
            "  decide +kernel", "",
            f"theorem {prefix}Elements_nodup : {prefix}Elements.Nodup :=",
            "  nodup_of_code_isChain (fun g : G ↦ permutationCode g.val) (by decide +kernel)", "",
            f"def {prefix} : Finset G :=",
            f"  finsetOfNodupList {prefix}Elements {prefix}Elements_nodup", "",
            f"theorem {prefix}_card : {prefix}.card = {size} := by",
            f"  change {prefix}Elements.length = {size}",
            "  decide +kernel", "",
            "/-- Array access keeps indexed closure verification linear in table size. -/",
            f"def {prefix}Array : Array G := {prefix}Elements.toArray", "",
            f"def {prefix}At (i : Fin {size}) : G :=",
            f"  {prefix}Array[i.val]'(by change i.val < {size}; exact i.isLt)", "",
            "/-- Cached arithmetic row; products never reconstruct its group elements. -/",
            f"def {prefix}CodeArray : Array ℕ := {prefix}Codes.toArray", "",
            f"def {prefix}CodeAt (i : Fin {size}) : ℕ :=",
            f"  {prefix}CodeArray[i.val]'(by change i.val < {size}; exact i.isLt)", "",
            f"theorem {prefix}CodeAt_correct :",
            f"    ∀ i, rowCode ({prefix}At i) = {prefix}CodeAt i := by",
            "  decide +kernel", "",
            f"def {prefix}InverseIndices : Array (Fin {size}) :=",
            "  " + literal_list(inverse_indices, array=True), "",
            f"def {prefix}InverseIndex (i : Fin {size}) : Fin {size} :=",
            f"  {prefix}InverseIndices[i.val]'(by change i.val < {size}; exact i.isLt)", "",
            "/-- Two-level multiplication indices keep each lookup bounded by row order. -/",
            f"def {prefix}ProductRows : Array (Fin {size} → Fin {size}) :=",
            "  #[" + ",\n    ".join(product_rows) + "]", "",
            f"def {prefix}ProductIndex (i j : Fin {size}) : Fin {size} :=",
            f"  ({prefix}ProductRows[i.val]'(by change i.val < {size}; exact i.isLt)) j", "",
            *coded_closure(prefix, size),
            "/-- Arithmetic correctness transfers back to the actual group table. -/",
            f"theorem {prefix}_indexedClosure :",
            f"    indexedClosureCheck {size} {prefix}At 0",
            f"      {prefix}InverseIndex {prefix}ProductIndex = true := by",
            "  apply indexedClosureCheck_of_codedIndexedClosureCheck rowCode rowCode_injective",
            f"    composeCode8 rowCode_mul {prefix}At {prefix}CodeAt {prefix}CodeAt_correct",
            f"    0 {prefix}InverseIndex {prefix}ProductIndex",
            f"  simpa only [rowCode_one] using {prefix}_codedClosure", "",
            f"theorem {prefix}_closed : subgroupCheck {prefix} = true := by",
            f"  exact subgroupCheck_finsetOfNodupList_of_arrayIndexedClosureCheck",
            f"    {prefix}Elements {prefix}Elements_nodup",
            (f"    (0 : Fin {size}) {prefix}InverseIndex {prefix}ProductIndex"
             f" {prefix}_indexedClosure"), "",
            f"theorem {prefix}_card_factorization :",
            f"    {prefix}.card = {prime} ^ (Nat.card G).factorization {prime} := by",
            f"  rw [{prefix}_card, card_G]",
            "  decide +kernel", "",
            f"noncomputable def sylow{prime} : Sylow {prime} G :=",
            f"  checkedSylow {prefix} {prefix}_closed {prefix}_card_factorization", "",
            f"@[simp] theorem mem_sylow{prime}_iff (g : G) :",
            f"    g ∈ sylow{prime} ↔ g ∈ {prefix} := Iff.rfl", "",
            f"theorem sylow{prime}_card : Nat.card sylow{prime} = {size} := by",
            f"  change Nat.card (checkedSubgroup {prefix} {prefix}_closed) = {size}",
            f"  exact (card_checkedSubgroup {prefix} {prefix}_closed).trans {prefix}_card", "",
        ])

    lines.extend(["end LisiSabatini.FiniteCertificates.A8Rows", ""])
    result = "\n".join(lines)
    assert all(len(line) <= 100 for line in result.splitlines()), "Long generated Lean line"
    return result


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=Path(__file__).with_name("A8Data.json"))
    parser.add_argument("--output", type=Path, default=Path(__file__).with_name("A8Rows.lean"))
    parser.add_argument("--primes", type=int, nargs="+", default=[2, 3, 5, 7])
    parser.add_argument("--check", action="store_true",
                        help="Compare deterministic output without writing")
    args = parser.parse_args()
    assert set(args.primes) <= {2, 3, 5, 7}
    document = json.loads(args.input.read_text())
    result = generate(document, args.primes).encode("utf-8")
    if args.check:
        assert args.output.read_bytes() == result
    else:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_bytes(result)
    print(json.dumps({"file": args.output.name, "bytes": len(result),
                      "sha256": sha256(result).hexdigest(), "primes": args.primes},
                     sort_keys=True))


if __name__ == "__main__":
    main()
