import LisiSabatini.ClassThreeCommutatorPower
import LisiSabatini.CyclicFrattiniOmega
import LisiSabatini.FrattiniCentrality

/-!
# Core centrality of cyclic Frattini subgroups at odd primes

This file assembles the odd-prime, class-three commutator calculation needed
to lift the structured Frattini-centralizer descent back to the ambient
`p`-group.
-/

noncomputable section

namespace LisiSabatini

set_option backward.isDefEq.respectTransparency false

open Subgroup
open scoped commutatorElement

/-! ## Exponent of basic commutators -/

/-- The class-three commutator calculation for one ordered pair. -/
private theorem basic_commutator_pow_prime_eq_one_of_pow_left_commutes
    {p : ℕ} {P : Type*} [Group P] [Finite P]
    (hp : p.Prime) (hpOdd : Odd p) (hPp : IsPGroup p P)
    (hPhiCyclic : IsCyclic (frattini P)) (x y : P)
    (hcomm : Commute (x ^ p) y) :
    ⁅x, y⁆ ^ p = 1 := by
  letI : Fact p.Prime := ⟨hp⟩
  have hcPhi : ⁅x, y⁆ ∈ frattini P :=
    commutator_le_frattini_of_isPGroup hp hPp
      (Subgroup.commutator_mem_commutator
        (Subgroup.mem_top x) (Subgroup.mem_top y))
  have htriple : ⁅x, ⁅x, y⁆⁆ ∈ Subgroup.center P :=
    frattini_commutator_mem_center_of_isCyclic
      hp hpOdd hPp hPhiCyclic x hcPhi
  have htriplePow : ⁅x, ⁅x, y⁆⁆ ^ p = 1 :=
    frattini_commutator_pow_prime_eq_one_of_isCyclic
      hp hpOdd hPp hPhiCyclic x hcPhi
  calc
    ⁅x, y⁆ ^ p = ⁅x ^ p, y⁆ :=
      (commutatorElement_pow_left_eq_pow_of_triple_mem_center_of_odd
        x y hpOdd htriple htriplePow).symm
    _ = 1 := commutatorElement_eq_one_iff_commute.mpr hcomm

/-- In a finite odd `p`-group with cyclic Frattini subgroup, every basic
commutator has `p`-th power one.

The cyclic subgroups generated by `x ^ p` and `y ^ p` are comparable inside
`Phi(P)`.  The class-three correction term vanishes because commutators with
`Phi(P)` are central and killed by `p`. -/
theorem basic_commutator_pow_prime_eq_one_of_odd_of_frattini_isCyclic
    {p : ℕ} {P : Type*} [Group P] [Finite P]
    (hp : p.Prime) (hpOdd : Odd p) (hPp : IsPGroup p P)
    (hPhiCyclic : IsCyclic (frattini P)) (x y : P) :
    ⁅x, y⁆ ^ p = 1 := by
  letI : Fact p.Prime := ⟨hp⟩
  letI : IsCyclic (frattini P) := hPhiCyclic
  let xp : frattini P :=
    ⟨x ^ p, pow_prime_mem_frattini_of_isPGroup hp hPp x⟩
  let yp : frattini P :=
    ⟨y ^ p, pow_prime_mem_frattini_of_isPGroup hp hPp y⟩
  have hPhiP : IsPGroup p (frattini P) :=
    hPp.to_subgroup (frattini P)
  rcases zpowers_le_or_le_of_isCyclic_isPGroup hp hPhiP xp yp with
      hxy | hyx
  · have hmem : xp ∈ Subgroup.zpowers yp :=
      hxy (Subgroup.mem_zpowers xp)
    obtain ⟨k, hk⟩ := Subgroup.mem_zpowers_iff.mp hmem
    have hkval : (y ^ p) ^ k = x ^ p := congrArg Subtype.val hk
    have hcomm : Commute (x ^ p) y := by
      rw [← hkval]
      exact ((Commute.refl y).pow_left p).zpow_left k
    exact basic_commutator_pow_prime_eq_one_of_pow_left_commutes
      hp hpOdd hPp hPhiCyclic x y hcomm
  · have hmem : yp ∈ Subgroup.zpowers xp :=
      hyx (Subgroup.mem_zpowers yp)
    obtain ⟨k, hk⟩ := Subgroup.mem_zpowers_iff.mp hmem
    have hkval : (x ^ p) ^ k = y ^ p := congrArg Subtype.val hk
    have hcomm : Commute (y ^ p) x := by
      rw [← hkval]
      exact ((Commute.refl x).pow_left p).zpow_left k
    have hswap : ⁅y, x⁆ ^ p = 1 :=
      basic_commutator_pow_prime_eq_one_of_pow_left_commutes
        hp hpOdd hPp hPhiCyclic y x hcomm
    rw [← commutatorElement_inv x y] at hswap
    simpa only [inv_pow, inv_eq_one] using hswap

/-! ## Ambient class two and Frattini centrality -/

/-- The same hypotheses force the ambient group to have nilpotency class at
most two.  Every basic commutator lies in `Phi(P)`, is killed by `p`, and is
therefore in the central prime-order layer proved in
`CyclicFrattiniOmega`. -/
theorem commutator_le_center_of_odd_of_frattini_isCyclic
    {p : ℕ} {P : Type*} [Group P] [Finite P]
    (hp : p.Prime) (hpOdd : Odd p) (hPp : IsPGroup p P)
    (hPhiCyclic : IsCyclic (frattini P)) :
    commutator P ≤ Subgroup.center P := by
  apply Subgroup.commutator_le.mpr
  intro x _hx y _hy
  apply frattini_prime_order_element_mem_center_of_isCyclic
    hp hPp hPhiCyclic
  · exact commutator_le_frattini_of_isPGroup hp hPp
      (Subgroup.commutator_mem_commutator
        (Subgroup.mem_top x) (Subgroup.mem_top y))
  · exact basic_commutator_pow_prime_eq_one_of_odd_of_frattini_isCyclic
      hp hpOdd hPp hPhiCyclic x y

/-- **Odd cyclic-Frattini centrality.**  A cyclic Frattini subgroup of a
finite odd `p`-group is central. -/
theorem frattini_le_center_of_odd_of_isCyclic
    {p : ℕ} {P : Type*} [Group P] [Finite P]
    (hp : p.Prime) (hpOdd : Odd p) (hPp : IsPGroup p P)
    (hPhiCyclic : IsCyclic (frattini P)) :
    frattini P ≤ Subgroup.center P :=
  frattini_le_center_of_classTwo_of_frattini_isCyclic
    hp hPp
      (commutator_le_center_of_odd_of_frattini_isCyclic
        hp hpOdd hPp hPhiCyclic)
      hPhiCyclic

end LisiSabatini
