import LisiSabatini.ClassTwoFrattini
import LisiSabatini.HallPGroupStructure

/-!
# The class-two core in Hall's odd p-group argument

The missing Hall classification says that a finite odd `p`-group whose
characteristic abelian subgroups are cyclic is a central product of an
extraspecial group and a cyclic group.  This file proves a structural step
strictly before that classification.

First, the Hall hypothesis descends to characteristic subgroups.  Next, in
any finite nonabelian class-two `p`-group with cyclic center, the canonical
central subgroup of order `p` is contained in the derived subgroup.  Applied
to `C_G(G')`, this produces a characteristic class-two core with

* cyclic center;
* nontrivial cyclic derived subgroup;
* a canonical central subgroup of order `p`; and
* that canonical subgroup contained in the derived subgroup.

No extraspecial factor or central complement is asserted.  The residual
group-theoretic step is precisely to split the possibly larger cyclic center
and extract a subgroup whose center and derived subgroup are the canonical
order-`p` kernel.
-/

noncomputable section

namespace LisiSabatini

set_option backward.isDefEq.respectTransparency false

namespace HasCyclicCharacteristicAbelianSubgroups

variable {G : Type*} [Group G]

/-- The Hall hypothesis is inherited by characteristic subgroups.

If `A` is characteristic and abelian in a characteristic subgroup `H`, its
faithful image in `G` is again characteristic and abelian.  Cyclicity of the
image therefore transports back to `A`. -/
theorem of_characteristic_subgroup
    (hG : HasCyclicCharacteristicAbelianSubgroups G)
    (H : Subgroup G) [H.Characteristic] :
    HasCyclicCharacteristicAbelianSubgroups H := by
  intro A hAchar hAcomm
  letI : A.Characteristic := hAchar
  letI : IsMulCommutative A := hAcomm
  have hImageChar : (A.map H.subtype).Characteristic :=
    characteristic_map_subtype (H := H) hAchar
  have hImageComm : IsMulCommutative (A.map H.subtype) :=
    Subgroup.map_isMulCommutative A H.subtype
  have hImageCyclic : IsCyclic (A.map H.subtype) :=
    hG (A.map H.subtype) hImageChar hImageComm
  exact (Subgroup.equivMapOfInjective A H.subtype
    Subtype.coe_injective).isCyclic.mpr hImageCyclic

end HasCyclicCharacteristicAbelianSubgroups

/-! ## The unique central subgroup of order `p` -/

/-- A finite nontrivial `p`-group with cyclic center has exactly `p`
central elements killed by the `p`-th power map.

This is the group-theoretic content used by
`HasCyclicCharacteristicAbelianSubgroups.card_centerPrimeKernel`, separated
from the stronger Hall hypothesis. -/
theorem card_centerPrimeKernel_of_center_isCyclic
    {p : ℕ} {G : Type*} [Group G] [Finite G] [Nontrivial G]
    (hp : p.Prime) (hGp : IsPGroup p G)
    (hcenter : IsCyclic (Subgroup.center G)) :
    Nat.card (centerPrimeKernel p G) = p := by
  letI : Fact p.Prime := ⟨hp⟩
  let Z := Subgroup.center G
  letI : Finite Z := inferInstance
  letI : Nontrivial Z := hGp.center_nontrivial
  letI : IsCyclic Z := hcenter
  let K0 := (powMonoidHom p : Z →* Z).ker
  have hp_dvd_cardZ : p ∣ Nat.card Z := by
    have hZp : IsPGroup p Z := hGp.to_subgroup (Subgroup.center G)
    obtain ⟨n, hn, hcard⟩ :=
      (hZp.nontrivial_iff_card.mp (inferInstance : Nontrivial Z))
    rw [hcard]
    exact dvd_pow_self p hn.ne'
  have hcardK0 : Nat.card K0 = (Nat.card Z).gcd p := by
    exact IsCyclic.card_powMonoidHom_ker Z p
  have hcardImage :
      Nat.card (K0.map (Subgroup.center G).subtype) = Nat.card K0 := by
    exact (Nat.card_congr
      (Subgroup.equivMapOfInjective K0 (Subgroup.center G).subtype
        Subtype.coe_injective).toEquiv).symm
  change Nat.card (K0.map (Subgroup.center G).subtype) = p
  calc
    Nat.card (K0.map (Subgroup.center G).subtype) = Nat.card K0 := hcardImage
    _ = (Nat.card Z).gcd p := hcardK0
    _ = p := Nat.gcd_eq_right_iff_dvd.mpr hp_dvd_cardZ

/-- **Canonical-kernel containment for a class-two core.**

Let `G` be a finite nonabelian `p`-group of class at most two with cyclic
center.  Its derived subgroup is a nontrivial `p`-subgroup of the center, so
it contains an element of order `p`.  Cyclicity of the center makes the
subgroup generated by that element equal to the canonical central kernel.
Consequently `centerPrimeKernel p G ≤ G'`.

This is the first intrinsic overlap needed for the eventual central-product
decomposition; it uses no classification theorem. -/
theorem centerPrimeKernel_le_commutator_of_classTwo_of_center_isCyclic
    {p : ℕ} {G : Type*} [Group G] [Finite G]
    (hp : p.Prime) (hGp : IsPGroup p G)
    (hclass : commutator G ≤ Subgroup.center G)
    (hcenter : IsCyclic (Subgroup.center G))
    (hnoncomm : ¬ IsMulCommutative G) :
    centerPrimeKernel p G ≤ commutator G := by
  letI : Fact p.Prime := ⟨hp⟩
  have hnotSubsingleton : ¬ Subsingleton G := by
    intro hsub
    apply hnoncomm
    exact ⟨⟨fun x y ↦ hsub.elim (x * y) (y * x)⟩⟩
  letI : Nontrivial G := not_subsingleton_iff_nontrivial.mp hnotSubsingleton
  have hcommNeBot : commutator G ≠ ⊥ := by
    intro hbot
    apply hnoncomm
    have hcenterTop : Subgroup.center G = ⊤ :=
      (commutator_eq_bot_iff_center_eq_top (G := G)).mp hbot
    refine ⟨⟨fun x y ↦ ?_⟩⟩
    have hx : x ∈ Subgroup.center G := by
      rw [hcenterTop]
      exact Subgroup.mem_top x
    exact (Subgroup.mem_center_iff.mp hx y).symm
  let D := commutator G
  letI : Nontrivial D :=
    (commutator G).nontrivial_iff_ne_bot.mpr hcommNeBot
  have hDp : IsPGroup p D := hGp.to_subgroup (commutator G)
  obtain ⟨m, hm, hcardD⟩ :=
    (hDp.nontrivial_iff_card.mp (inferInstance : Nontrivial D))
  have hp_dvd_cardD : p ∣ Nat.card D := by
    rw [hcardD]
    exact dvd_pow_self p hm.ne'
  obtain ⟨c, hcOrder⟩ := exists_prime_orderOf_dvd_card' p hp_dvd_cardD
  let z : G := c
  have hzComm : z ∈ commutator G := c.2
  have hzCenter : z ∈ Subgroup.center G := hclass hzComm
  let zc : Subgroup.center G := ⟨z, hzCenter⟩
  have hzOrder : orderOf z = p := by
    exact (Subgroup.orderOf_coe c).trans hcOrder
  have hzcOrder : orderOf zc = p := by
    calc
      orderOf zc = orderOf (zc : G) := (Subgroup.orderOf_coe zc).symm
      _ = orderOf z := rfl
      _ = p := hzOrder
  have hzKernel : z ∈ centerPrimeKernel p G := by
    apply Subgroup.mem_map.mpr
    refine ⟨zc, ?_, rfl⟩
    apply MonoidHom.mem_ker.mpr
    change zc ^ p = 1
    rw [← hzcOrder]
    exact pow_orderOf_eq_one zc
  have hzpowersLe : Subgroup.zpowers z ≤ centerPrimeKernel p G :=
    Subgroup.zpowers_le_of_mem hzKernel
  have hzpowersCard : Nat.card (Subgroup.zpowers z) = p := by
    rw [Nat.card_zpowers, hzOrder]
  have hkernelCard : Nat.card (centerPrimeKernel p G) = p :=
    card_centerPrimeKernel_of_center_isCyclic hp hGp hcenter
  have hzpowersEq : Subgroup.zpowers z = centerPrimeKernel p G := by
    apply Subgroup.eq_of_le_of_card_ge hzpowersLe
    rw [hkernelCard, hzpowersCard]
  rw [← hzpowersEq]
  exact Subgroup.zpowers_le_of_mem hzComm

/-- If the derived subgroup of a class-two group has exponent dividing `p`,
then it lies in the canonical central `p`-kernel.

Unlike the preceding theorem, this direction needs no finiteness or
`p`-group hypothesis.  It records exactly how the still-missing exponent
step would close the intrinsic overlap. -/
theorem commutator_le_centerPrimeKernel_of_classTwo_of_exponent
    {p : ℕ} {G : Type*} [Group G]
    (hclass : commutator G ≤ Subgroup.center G)
    (hpow : ∀ c : commutator G, (c : G) ^ p = 1) :
    commutator G ≤ centerPrimeKernel p G := by
  intro c hc
  have hcCenter : c ∈ Subgroup.center G := hclass hc
  let zc : Subgroup.center G := ⟨c, hcCenter⟩
  apply Subgroup.mem_map.mpr
  refine ⟨zc, ?_, rfl⟩
  apply MonoidHom.mem_ker.mpr
  apply Subtype.ext
  exact hpow ⟨c, hc⟩

/-- For a finite nonabelian class-two `p`-group with cyclic center, an
exponent-`p` derived subgroup is exactly the canonical central subgroup of
order `p`.

The exponent hypothesis is deliberately exposed: proving it from the Hall
hypothesis is the remaining critical-subgroup step, not something established
by class two and cyclic center alone. -/
theorem commutator_eq_centerPrimeKernel_of_classTwo_of_center_isCyclic
    {p : ℕ} {G : Type*} [Group G] [Finite G]
    (hp : p.Prime) (hGp : IsPGroup p G)
    (hclass : commutator G ≤ Subgroup.center G)
    (hcenter : IsCyclic (Subgroup.center G))
    (hnoncomm : ¬ IsMulCommutative G)
    (hpow : ∀ c : commutator G, (c : G) ^ p = 1) :
    commutator G = centerPrimeKernel p G := by
  apply le_antisymm
  · exact commutator_le_centerPrimeKernel_of_classTwo_of_exponent
      hclass hpow
  · exact centerPrimeKernel_le_commutator_of_classTwo_of_center_isCyclic
      hp hGp hclass hcenter hnoncomm

/-! ## A bundled critical-subgroup intermediate -/

/-- The exact class-two package now available before the missing Hall
central-product classification.

The name `Intermediate` is intentional: this is not an extraspecial group.
Its center and derived subgroup may have order larger than `p`. -/
structure IsHallClassTwoIntermediate
    (p : ℕ) (P : Type*) [Group P] [Finite P] : Prop where
  prime : p.Prime
  odd : Odd p
  pGroup : IsPGroup p P
  hall : HasCyclicCharacteristicAbelianSubgroups P
  noncommutative : ¬ IsMulCommutative P
  commutator_le_center : commutator P ≤ Subgroup.center P
  centerPrimeKernel_le_commutator :
    centerPrimeKernel p P ≤ commutator P

namespace IsHallClassTwoIntermediate

variable {p : ℕ} {P : Type*} [Group P] [Finite P]

/-- The center of a Hall class-two intermediate is cyclic. -/
theorem center_isCyclic (h : IsHallClassTwoIntermediate p P) :
    IsCyclic (Subgroup.center P) :=
  h.hall.center_isCyclic

/-- A Hall class-two intermediate is nontrivial. -/
theorem nontrivial (h : IsHallClassTwoIntermediate p P) : Nontrivial P := by
  apply not_subsingleton_iff_nontrivial.mp
  intro hsub
  apply h.noncommutative
  exact ⟨⟨fun x y ↦ hsub.elim (x * y) (y * x)⟩⟩

/-- Its canonical central kernel has order exactly `p`. -/
theorem card_centerPrimeKernel (h : IsHallClassTwoIntermediate p P) :
    Nat.card (centerPrimeKernel p P) = p := by
  letI : Nontrivial P := h.nontrivial
  exact card_centerPrimeKernel_of_center_isCyclic
    h.prime h.pGroup h.center_isCyclic

/-- The canonical order-`p` subgroup sits in the useful chain
`K ≤ P' ≤ Z(P)`. -/
theorem centerPrimeKernel_le_commutator_le_center
    (h : IsHallClassTwoIntermediate p P) :
    centerPrimeKernel p P ≤ commutator P ∧
      commutator P ≤ Subgroup.center P :=
  ⟨h.centerPrimeKernel_le_commutator, h.commutator_le_center⟩

/-- Once the residual exponent-`p` statement is supplied, the derived
subgroup of the bundled intermediate is exactly its canonical central
order-`p` kernel. -/
theorem commutator_eq_centerPrimeKernel
    (h : IsHallClassTwoIntermediate p P)
    (hpow : ∀ c : commutator P, (c : P) ^ p = 1) :
    commutator P = centerPrimeKernel p P :=
  commutator_eq_centerPrimeKernel_of_classTwo_of_center_isCyclic
    h.prime h.pGroup h.commutator_le_center h.center_isCyclic
      h.noncommutative hpow

/-- Centrality of the Frattini subgroup is a structural sufficient condition
for the residual exponent statement, and hence identifies the derived
subgroup with the canonical central order-`p` kernel. -/
theorem commutator_eq_centerPrimeKernel_of_frattini_le_center
    (h : IsHallClassTwoIntermediate p P)
    (hPhi : frattini P ≤ Subgroup.center P) :
    commutator P = centerPrimeKernel p P := by
  apply h.commutator_eq_centerPrimeKernel
  exact commutator_pow_prime_eq_one_of_frattini_le_center
    h.prime h.pGroup h.commutator_le_center hPhi

end IsHallClassTwoIntermediate

namespace derivedCentralizer

variable {p : ℕ} {G : Type*} [Group G]

/-- The Hall hypothesis descends to the characteristic centralizer
`C_G(G')`. -/
theorem hallHypothesis
    (hG : HasCyclicCharacteristicAbelianSubgroups G) :
    HasCyclicCharacteristicAbelianSubgroups (derivedCentralizer G) :=
  hG.of_characteristic_subgroup (derivedCentralizer G)

variable [Finite G]

/-- **Construct the Hall class-two intermediate.**

For a finite odd `p`-group satisfying the Hall hypothesis, the characteristic
centralizer `C_G(G')` has the complete bundled intermediate structure as soon
as it is nonabelian.  The canonical-kernel containment is proved above; it is
not an additional assumption. -/
def isHallClassTwoIntermediate
    (hp : p.Prime) (hpOdd : Odd p) (hGp : IsPGroup p G)
    (hG : HasCyclicCharacteristicAbelianSubgroups G)
    (hnoncomm : ¬ IsMulCommutative (derivedCentralizer G)) :
    IsHallClassTwoIntermediate p (derivedCentralizer G) := by
  let hCp : IsPGroup p (derivedCentralizer G) :=
    hGp.to_subgroup (derivedCentralizer G)
  let hHallC : HasCyclicCharacteristicAbelianSubgroups
      (derivedCentralizer G) := hallHypothesis hG
  refine
    { prime := hp
      odd := hpOdd
      pGroup := hCp
      hall := hHallC
      noncommutative := hnoncomm
      commutator_le_center := derivedCentralizer.commutator_le_center G
      centerPrimeKernel_le_commutator := ?_ }
  exact centerPrimeKernel_le_commutator_of_classTwo_of_center_isCyclic
    hp hCp (derivedCentralizer.commutator_le_center G)
      hHallC.center_isCyclic hnoncomm

end derivedCentralizer

end LisiSabatini
