module

public import LisiSabatini.HallClassTwoCore
public import LisiSabatini.ClassTwoCommutator

/-!
# A sharper Frattini reduction in the Hall class-two core

`HallClassTwoCore` exposed centrality of the Frattini subgroup as a sufficient
condition for the derived subgroup of the class-two core to have exponent
`p`.  This file weakens that condition substantially.

For a finite cyclic `p`-group, the cyclic subgroups generated by any two
elements are comparable.  Apply this inside `Φ(G)` to `x ^ p` and `y ^ p`.
When `G` has class at most two, the comparison forces the basic commutator
`[x,y]` to have `p`-th power one.  Hence every `p`-th power is central and
the whole derived subgroup has exponent dividing `p`.

Consequently, for a Hall class-two intermediate it is enough to know that
`Φ(G)` is *abelian*: the Hall hypothesis then makes `Φ(G)` cyclic, and the
argument above identifies the derived subgroup with the canonical central
subgroup of order `p`.

This does not prove that `Φ(G)` is abelian.  That is the precise remaining
critical-subgroup/Hobby step.  Nor do we assert that class two and cyclic
center alone suffice: higher-exponent Heisenberg-type groups show they do
not.
-/

@[expose] public section

noncomputable section

namespace LisiSabatini

set_option backward.isDefEq.respectTransparency false

open Subgroup
open scoped commutatorElement

/-! ## Comparable cyclic subgroups in a cyclic p-group -/

/-- A Bézout calculation used to compare cyclic subgroups.

If `gcd(n, orderOf g)` divides `m`, then `g ^ m` is an integral power of
`g ^ n`. -/
theorem pow_mem_zpowers_pow_of_gcd_dvd
    {G : Type*} [Group G] {g : G} {m n : ℕ}
    (h : Nat.gcd n (orderOf g) ∣ m) :
    g ^ m ∈ Subgroup.zpowers (g ^ n) := by
  obtain ⟨k, rfl⟩ := h
  apply Subgroup.mem_zpowers_iff.mpr
  refine ⟨(Nat.gcdA n (orderOf g)) * (k : ℤ), ?_⟩
  rw [← zpow_natCast g n]
  rw [← zpow_natCast g (Nat.gcd n (orderOf g) * k)]
  rw [← zpow_mul, zpow_eq_zpow_iff_modEq]
  have hmod := Int.gcd_a_modEq n (orderOf g)
  have hmodk := hmod.mul_right (k : ℤ)
  simpa [Int.natCast_mul, mul_assoc] using hmodk

/-- The cyclic subgroups generated by two elements of a finite cyclic
`p`-group are comparable.

The proof chooses a generator `g`.  Both relevant gcds divide the prime
power `orderOf g`, so they are powers of `p` and hence comparable. -/
theorem zpowers_le_or_le_of_isCyclic_isPGroup
    {p : ℕ} {G : Type*} [Group G] [Finite G]
    (hp : p.Prime) (hGp : IsPGroup p G) [IsCyclic G]
    (a b : G) :
    Subgroup.zpowers a ≤ Subgroup.zpowers b ∨
      Subgroup.zpowers b ≤ Subgroup.zpowers a := by
  letI : Fact p.Prime := ⟨hp⟩
  obtain ⟨g, hg⟩ := IsCyclic.exists_monoid_generator (α := G)
  obtain ⟨m, hm⟩ := hg a
  obtain ⟨n, hn⟩ := hg b
  rw [← hm, ← hn]
  obtain ⟨k, hk⟩ := (IsPGroup.iff_orderOf.mp hGp) g
  obtain ⟨i, _hi, hmi⟩ :=
    (Nat.dvd_prime_pow hp).mp
      (hk ▸ Nat.gcd_dvd_right m (orderOf g))
  obtain ⟨j, _hj, hnj⟩ :=
    (Nat.dvd_prime_pow hp).mp
      (hk ▸ Nat.gcd_dvd_right n (orderOf g))
  rcases le_total i j with hij | hji
  · right
    apply Subgroup.zpowers_le_of_mem
    apply pow_mem_zpowers_pow_of_gcd_dvd
    have hd : Nat.gcd m (orderOf g) ∣ Nat.gcd n (orderOf g) := by
      rw [hk, hmi, hnj]
      exact pow_dvd_pow p hij
    exact hd.trans (Nat.gcd_dvd_left n (orderOf g))
  · left
    apply Subgroup.zpowers_le_of_mem
    apply pow_mem_zpowers_pow_of_gcd_dvd
    have hd : Nat.gcd n (orderOf g) ∣ Nat.gcd m (orderOf g) := by
      rw [hk, hmi, hnj]
      exact pow_dvd_pow p hji
    exact hd.trans (Nat.gcd_dvd_left m (orderOf g))

/-! ## Cyclic Frattini forces the required exponent -/

/-- In a finite class-two `p`-group with cyclic Frattini subgroup, every
basic commutator has `p`-th power one. -/
theorem basic_commutator_pow_eq_one_of_frattini_isCyclic
    {p : ℕ} {G : Type*} [Group G] [Finite G]
    (hp : p.Prime) (hGp : IsPGroup p G)
    (hclass : commutator G ≤ Subgroup.center G)
    (hPhiCyclic : IsCyclic (frattini G)) (x y : G) :
    ⁅x, y⁆ ^ p = 1 := by
  letI : Fact p.Prime := ⟨hp⟩
  letI : IsCyclic (frattini G) := hPhiCyclic
  let xp : frattini G :=
    ⟨x ^ p, pow_prime_mem_frattini_of_isPGroup hp hGp x⟩
  let yp : frattini G :=
    ⟨y ^ p, pow_prime_mem_frattini_of_isPGroup hp hGp y⟩
  have hPhiP : IsPGroup p (frattini G) :=
    hGp.to_subgroup (frattini G)
  rcases zpowers_le_or_le_of_isCyclic_isPGroup hp hPhiP xp yp with
      hxy | hyx
  · have hmem : xp ∈ Subgroup.zpowers yp :=
      hxy (Subgroup.mem_zpowers xp)
    obtain ⟨k, hk⟩ := Subgroup.mem_zpowers_iff.mp hmem
    have hkval : (y ^ p) ^ k = x ^ p := congrArg Subtype.val hk
    have hcomm : Commute (x ^ p) y := by
      rw [← hkval]
      exact ((Commute.refl y).pow_left p).zpow_left k
    rw [← commutatorElement_pow_left_of_mem_center x y]
    · exact commutatorElement_eq_one_iff_mul_comm.mpr hcomm.eq
    · exact hclass (Subgroup.commutator_mem_commutator
        (Subgroup.mem_top x) (Subgroup.mem_top y))
  · have hmem : yp ∈ Subgroup.zpowers xp :=
      hyx (Subgroup.mem_zpowers yp)
    obtain ⟨k, hk⟩ := Subgroup.mem_zpowers_iff.mp hmem
    have hkval : (x ^ p) ^ k = y ^ p := congrArg Subtype.val hk
    have hcomm : Commute (y ^ p) x := by
      rw [← hkval]
      exact ((Commute.refl x).pow_left p).zpow_left k
    have hswap : ⁅y, x⁆ ^ p = 1 := by
      rw [← commutatorElement_pow_left_of_mem_center y x]
      · exact commutatorElement_eq_one_iff_mul_comm.mpr hcomm.eq
      · exact hclass (Subgroup.commutator_mem_commutator
          (Subgroup.mem_top y) (Subgroup.mem_top x))
    rw [← commutatorElement_inv x y] at hswap
    simpa only [inv_pow, inv_eq_one] using hswap

/-- Under the same hypotheses, every ambient `p`-th power is central. -/
theorem pow_mem_center_of_frattini_isCyclic
    {p : ℕ} {G : Type*} [Group G] [Finite G]
    (hp : p.Prime) (hGp : IsPGroup p G)
    (hclass : commutator G ≤ Subgroup.center G)
    (hPhiCyclic : IsCyclic (frattini G)) (x : G) :
    x ^ p ∈ Subgroup.center G := by
  rw [Subgroup.mem_center_iff]
  intro y
  rw [eq_comm, ← commutatorElement_eq_one_iff_mul_comm,
    commutatorElement_pow_left_of_mem_center x y]
  · exact basic_commutator_pow_eq_one_of_frattini_isCyclic
      hp hGp hclass hPhiCyclic x y
  · exact hclass (Subgroup.commutator_mem_commutator
      (Subgroup.mem_top x) (Subgroup.mem_top y))

/-- Cyclicity of the Frattini subgroup supplies exactly the residual
exponent-`p` statement required by `HallClassTwoCore`. -/
theorem commutator_pow_prime_eq_one_of_frattini_isCyclic
    {p : ℕ} {G : Type*} [Group G] [Finite G]
    (hp : p.Prime) (hGp : IsPGroup p G)
    (hclass : commutator G ≤ Subgroup.center G)
    (hPhiCyclic : IsCyclic (frattini G)) :
    ∀ c : commutator G, (c : G) ^ p = 1 := by
  apply commutator_pow_eq_one_of_classTwo_of_pow_mem_center hclass
  exact pow_mem_center_of_frattini_isCyclic
    hp hGp hclass hPhiCyclic

/-! ## Hall and derived-centralizer endpoints -/

namespace IsHallClassTwoIntermediate

variable {p : ℕ} {P : Type*} [Group P] [Finite P]

/-- A cyclic Frattini subgroup closes the canonical-kernel equality. -/
theorem commutator_eq_centerPrimeKernel_of_frattini_isCyclic
    (h : IsHallClassTwoIntermediate p P)
    (hPhiCyclic : IsCyclic (frattini P)) :
    commutator P = centerPrimeKernel p P := by
  apply h.commutator_eq_centerPrimeKernel
  exact commutator_pow_prime_eq_one_of_frattini_isCyclic
    h.prime h.pGroup h.commutator_le_center hPhiCyclic

/-- **Sharpened Hall residual.**

For a Hall class-two intermediate, it is enough that `Φ(P)` be abelian.
Characteristicity of `Φ(P)` and the Hall hypothesis make it cyclic; the
preceding theorem then closes the derived subgroup calculation. -/
theorem commutator_eq_centerPrimeKernel_of_frattini_isMulCommutative
    (h : IsHallClassTwoIntermediate p P)
    (hPhiComm : IsMulCommutative (frattini P)) :
    commutator P = centerPrimeKernel p P := by
  letI : IsMulCommutative (frattini P) := hPhiComm
  have hPhiCyclic : IsCyclic (frattini P) :=
    h.hall.isCyclic (frattini P)
  exact h.commutator_eq_centerPrimeKernel_of_frattini_isCyclic
    hPhiCyclic

end IsHallClassTwoIntermediate

namespace derivedCentralizer

variable {p : ℕ} {G : Type*} [Group G] [Finite G]

/-- Applied to `C_G(G')`, the remaining input is only abelianness of its
Frattini subgroup.  All other class-two, characteristic, Hall, and
canonical-kernel facts are supplied by the existing construction. -/
theorem commutator_eq_centerPrimeKernel_of_frattini_isMulCommutative
    (hp : p.Prime) (hpOdd : Odd p) (hGp : IsPGroup p G)
    (hG : HasCyclicCharacteristicAbelianSubgroups G)
    (hnoncomm : ¬ IsMulCommutative (derivedCentralizer G))
    (hPhiComm : IsMulCommutative (frattini (derivedCentralizer G))) :
    commutator (derivedCentralizer G) =
      centerPrimeKernel p (derivedCentralizer G) := by
  let hC := isHallClassTwoIntermediate hp hpOdd hGp hG hnoncomm
  exact hC.commutator_eq_centerPrimeKernel_of_frattini_isMulCommutative
    hPhiComm

end derivedCentralizer

end LisiSabatini
