import LisiSabatini.TwoCoreSymplecticTypeFrontier
import Mathlib.Algebra.Group.Subgroup.Lattice

/-!
# The exact omega-one/Frattini-centralizer hypothesis in Hall--Berger

Berger--Kovács--Newman prove their central-product classification under
the hypothesis

`Z(Ω₁(C_G(Φ(G)))) is cyclic`.

The quasiprimitive linear argument supplies the stronger Hall condition
that every characteristic abelian subgroup is cyclic.  This file proves
the exact implication between those two hypotheses.  It therefore
separates the published classification theorem itself from the elementary
characteristic-subgroup bridge needed to apply it.
-/

noncomputable section

namespace LisiSabatini

universe u

variable (p : ℕ) (G : Type u) [Group G]

/-- The subgroup `Ω₁(G)` generated by all elements whose `p`-th power is
one.  Closure is necessary because the set of such elements need not
itself be a subgroup in a noncommutative `p`-group. -/
def omegaOneSubgroup : Subgroup G :=
  Subgroup.closure {x : G | x ^ p = 1}

/-- `Ω₁(G)` is characteristic. -/
instance omegaOneSubgroup_characteristic :
    (omegaOneSubgroup p G).Characteristic := by
  rw [Subgroup.characteristic_iff_map_le]
  intro e
  rw [Subgroup.map_le_iff_le_comap]
  apply (Subgroup.closure_le _).mpr
  intro x hx
  change e x ∈ omegaOneSubgroup p G
  apply Subgroup.subset_closure
  change (e x) ^ p = 1
  rw [← map_pow, hx, map_one]

/-- The centralizer `C_G(Φ(G))` occurring in the
Berger--Kovács--Newman theorem. -/
def frattiniCentralizer : Subgroup G :=
  Subgroup.centralizer (frattini G : Set G)

/-- `C_G(Φ(G))` is characteristic. -/
instance frattiniCentralizer_characteristic :
    (frattiniCentralizer G).Characteristic := by
  unfold frattiniCentralizer
  infer_instance

/-- The exact cyclic-center hypothesis in the
Berger--Kovács--Newman theorem. -/
def HasCyclicOmegaOneFrattiniCentralizerCenter : Prop :=
  IsCyclic
    (Subgroup.center
      (omegaOneSubgroup p (frattiniCentralizer G)))

namespace HasCyclicCharacteristicAbelianSubgroups

variable {p : ℕ} {G : Type u} [Group G]

/-- Hall's condition implies the precise omega-one centralizer condition
used in the published classification theorem.

Indeed `C = C_G(Φ(G))` is characteristic, hence so is the ambient image
of `Ω₁(C)`.  Its center is therefore cyclic by Hall's condition, and
cyclicity transports back through the faithful subtype image. -/
theorem hasCyclicOmegaOneFrattiniCentralizerCenter
    (hHall : HasCyclicCharacteristicAbelianSubgroups G) :
    HasCyclicOmegaOneFrattiniCentralizerCenter p G := by
  let C : Subgroup G := frattiniCentralizer G
  let A₀ : Subgroup C := omegaOneSubgroup p C
  let A : Subgroup G := A₀.map C.subtype
  letI : C.Characteristic :=
    frattiniCentralizer_characteristic G
  have hAchar : A.Characteristic := by
    dsimp only [A, A₀]
    exact characteristic_map_subtype
      (H := C) (omegaOneSubgroup_characteristic p C)
  letI : A.Characteristic := hAchar
  have hcenterA : IsCyclic (Subgroup.center A) :=
    hHall.characteristic_center_isCyclic A
  let eA : A₀ ≃* A :=
    Subgroup.equivMapOfInjective A₀ C.subtype
      Subtype.coe_injective
  exact (Subgroup.centerCongr eA).isCyclic.mpr hcenterA

end HasCyclicCharacteristicAbelianSubgroups

/-! ## The published classification boundary -/

/-- The Berger--Kovács--Newman classification, stated with its actual
omega-one hypothesis rather than the stronger Hall hypothesis used by the
linear application.

This is a proposition interface, not an axiom or theorem. -/
def BergerKovacsNewmanTwoGroupClassificationStatement : Prop :=
  ∀ (P : Type u) [Group P] [Finite P],
    IsPGroup 2 P →
    HasCyclicOmegaOneFrattiniCentralizerCenter 2 P →
    Nonempty (HallBergerTwoCoreShape P)

/-- The published source statement implies the Hall-form classification
interface used by the affine reserve. -/
theorem hallBergerTwoGroupClassification_of_bergerKovacsNewman
    (hBKN : BergerKovacsNewmanTwoGroupClassificationStatement.{u}) :
    HallBergerTwoGroupClassificationStatement.{u} := by
  intro P _ _ hP hHall
  exact hBKN P hP hHall.hasCyclicOmegaOneFrattiniCentralizerCenter

end LisiSabatini
