module

public import LisiSabatini.HallBergerSourcePreliminaries

/-!
# The two-generator central-factor lemma in Hall--Berger

The second elementary fact in the Berger--Kovács--Newman proof says that,
when the derived subgroup has prime order, every noncommutative
two-generator subgroup is a central factor.  The application here is at
`p = 2`, after the Frattini-centralizer preliminaries have shown that the
derived subgroup is central of order two.
-/

@[expose] public section

noncomputable section

namespace LisiSabatini

set_option backward.isDefEq.respectTransparency false

open scoped commutatorElement

universe u

/-- The subgroup generated by two elements. -/
def twoGeneratorSubgroup
    {D : Type u} [Group D] (x y : D) : Subgroup D :=
  Subgroup.zpowers x ⊔ Subgroup.zpowers y

/-- An internal central factor, stated exactly in the form used in the
Berger--Kovács--Newman decomposition: the factor and its centralizer
generate the ambient group, and their overlap is the center of the
factor, viewed in the ambient group. -/
structure IsInternalCentralFactor
    {D : Type u} [Group D] (H : Subgroup D) : Prop where
  generate :
    H ⊔ Subgroup.centralizer (H : Set D) = ⊤
  overlap :
    H ⊓ Subgroup.centralizer (H : Set D) =
      characteristicCenterImage H

private theorem mul_commutators_eq_one_of_ne_one
    {D : Type u} [Group D] [Finite D]
    (hD : HasCentralCommutatorOfOrderTwo D)
    {a b c d : D}
    (hab : ⁅a, b⁆ ≠ 1) (hcd : ⁅c, d⁆ ≠ 1) :
    ⁅a, b⁆ * ⁅c, d⁆ = 1 := by
  let u : commutator D :=
    ⟨⁅a, b⁆, Subgroup.commutator_mem_commutator
      (Subgroup.mem_top a) (Subgroup.mem_top b)⟩
  let v : commutator D :=
    ⟨⁅c, d⁆, Subgroup.commutator_mem_commutator
      (Subgroup.mem_top c) (Subgroup.mem_top d)⟩
  obtain ⟨z, hzNe, hzUnique⟩ :=
    (Nat.card_eq_two_iff' (1 : commutator D)).mp
      hD.card_commutator
  have huNe : u ≠ 1 := by
    intro hu
    exact hab (congrArg Subtype.val hu)
  have hvNe : v ≠ 1 := by
    intro hv
    exact hcd (congrArg Subtype.val hv)
  have hu : u = z := hzUnique u huNe
  have hv : v = z := hzUnique v hvNe
  have hzSq : z ^ 2 = 1 := by
    have hpow : z ^ Nat.card (commutator D) = 1 :=
      pow_card_eq_one'
    simpa [hD.card_commutator] using hpow
  change (u : D) * (v : D) = 1
  rw [hu, hv]
  simpa only [pow_two, Subgroup.coe_mul, Subgroup.coe_one] using
    congrArg Subtype.val hzSq

/-- Every commutator has square one when the full derived subgroup is
central of order two. -/
theorem commutatorElement_sq_eq_one
    {D : Type u} [Group D] [Finite D]
    (hD : HasCentralCommutatorOfOrderTwo D)
    (a b : D) :
    ⁅a, b⁆ ^ 2 = 1 := by
  by_cases hab : ⁅a, b⁆ = 1
  · rw [hab]
    simp
  · simpa only [pow_two] using
      mul_commutators_eq_one_of_ne_one hD hab hab

private theorem mem_centralizer_twoGeneratorSubgroup
    {D : Type u} [Group D]
    {x y k : D}
    (hkx : ⁅k, x⁆ = 1) (hky : ⁅k, y⁆ = 1) :
    k ∈ Subgroup.centralizer
      (twoGeneratorSubgroup x y : Set D) := by
  let L : Subgroup D := Subgroup.centralizer ({k} : Set D)
  have hxL : x ∈ L := by
    rw [Subgroup.mem_centralizer_singleton_iff]
    exact (commutatorElement_eq_one_iff_mul_comm.mp hkx).symm
  have hyL : y ∈ L := by
    rw [Subgroup.mem_centralizer_singleton_iff]
    exact (commutatorElement_eq_one_iff_mul_comm.mp hky).symm
  have hHL : twoGeneratorSubgroup x y ≤ L :=
    sup_le (Subgroup.zpowers_le_of_mem hxL)
      (Subgroup.zpowers_le_of_mem hyL)
  rw [Subgroup.mem_centralizer_iff]
  intro a ha
  exact Subgroup.mem_centralizer_singleton_iff.mp (hHL ha)

/-- A noncommutative two-generator subgroup of a finite group with
central derived subgroup of order two, together with its centralizer,
generates the whole group. -/
theorem twoGeneratorSubgroup_sup_centralizer_eq_top
    {D : Type u} [Group D] [Finite D]
    (hD : HasCentralCommutatorOfOrderTwo D)
    (x y : D) (hxy : ⁅x, y⁆ ≠ 1) :
    twoGeneratorSubgroup x y ⊔
        Subgroup.centralizer
          (twoGeneratorSubgroup x y : Set D) =
      ⊤ := by
  let H : Subgroup D := twoGeneratorSubgroup x y
  let C : Subgroup D := Subgroup.centralizer (H : Set D)
  have hcommCenter (a b : D) :
      ⁅a, b⁆ ∈ Subgroup.center D :=
    hD.commutator_le_center
      (Subgroup.commutator_mem_commutator
        (Subgroup.mem_top a) (Subgroup.mem_top b))
  have hyx : ⁅y, x⁆ ≠ 1 := by
    intro hyx
    apply hxy
    have hinv : ⁅x, y⁆⁻¹ = 1 := by
      simpa only [commutatorElement_inv] using hyx
    simpa only [inv_eq_one] using hinv
  rw [Subgroup.eq_top_iff']
  intro g
  by_cases hgx : ⁅g, x⁆ = 1
  · by_cases hgy : ⁅g, y⁆ = 1
    · have hgC : g ∈ C :=
        mem_centralizer_twoGeneratorSubgroup hgx hgy
      exact (show C ≤ H ⊔ C from le_sup_right) hgC
    · let k : D := x * g
      have hkx : ⁅k, x⁆ = 1 := by
        dsimp only [k]
        rw [commutatorElement_mul_left_of_mem_center
          x g x (hcommCenter g x), hgx]
        simp
      have hky : ⁅k, y⁆ = 1 := by
        dsimp only [k]
        rw [commutatorElement_mul_left_of_mem_center
          x g y (hcommCenter g y)]
        exact mul_commutators_eq_one_of_ne_one hD hgy hxy
      have hkC : k ∈ C :=
        mem_centralizer_twoGeneratorSubgroup hkx hky
      have hxH : x ∈ H := by
        exact (show Subgroup.zpowers x ≤ H from le_sup_left)
          (Subgroup.mem_zpowers x)
      have hxInv : x⁻¹ ∈ H := H.inv_mem hxH
      have hprod :
          x⁻¹ * k ∈ H ⊔ C :=
        (H ⊔ C).mul_mem
          ((show H ≤ H ⊔ C from le_sup_left) hxInv)
          ((show C ≤ H ⊔ C from le_sup_right) hkC)
      simpa only [k, inv_mul_cancel_left] using hprod
  · by_cases hgy : ⁅g, y⁆ = 1
    · let k : D := y * g
      have hkx : ⁅k, x⁆ = 1 := by
        dsimp only [k]
        rw [commutatorElement_mul_left_of_mem_center
          y g x (hcommCenter g x)]
        exact mul_commutators_eq_one_of_ne_one hD hgx hyx
      have hky : ⁅k, y⁆ = 1 := by
        dsimp only [k]
        rw [commutatorElement_mul_left_of_mem_center
          y g y (hcommCenter g y), hgy]
        simp
      have hkC : k ∈ C :=
        mem_centralizer_twoGeneratorSubgroup hkx hky
      have hyH : y ∈ H := by
        exact (show Subgroup.zpowers y ≤ H from le_sup_right)
          (Subgroup.mem_zpowers y)
      have hyInv : y⁻¹ ∈ H := H.inv_mem hyH
      have hprod :
          y⁻¹ * k ∈ H ⊔ C :=
        (H ⊔ C).mul_mem
          ((show H ≤ H ⊔ C from le_sup_left) hyInv)
          ((show C ≤ H ⊔ C from le_sup_right) hkC)
      simpa only [k, inv_mul_cancel_left] using hprod
    · let h : D := x * y
      let k : D := h * g
      have hkx : ⁅k, x⁆ = 1 := by
        dsimp only [k, h]
        rw [commutatorElement_mul_left_of_mem_center
          (x * y) g x (hcommCenter g x),
          commutatorElement_mul_left_of_mem_center
            x y x (hcommCenter y x)]
        simp only [commutatorElement_self, mul_one]
        exact mul_commutators_eq_one_of_ne_one hD hgx hyx
      have hky : ⁅k, y⁆ = 1 := by
        dsimp only [k, h]
        rw [commutatorElement_mul_left_of_mem_center
          (x * y) g y (hcommCenter g y),
          commutatorElement_mul_left_of_mem_center
            x y y (hcommCenter y y)]
        simp only [commutatorElement_self, one_mul]
        exact mul_commutators_eq_one_of_ne_one hD hgy hxy
      have hkC : k ∈ C :=
        mem_centralizer_twoGeneratorSubgroup hkx hky
      have hxH : x ∈ H :=
        (show Subgroup.zpowers x ≤ H from le_sup_left)
          (Subgroup.mem_zpowers x)
      have hyH : y ∈ H :=
        (show Subgroup.zpowers y ≤ H from le_sup_right)
          (Subgroup.mem_zpowers y)
      have hhInv : h⁻¹ ∈ H :=
        H.inv_mem (H.mul_mem hxH hyH)
      have hprod :
          h⁻¹ * k ∈ H ⊔ C :=
        (H ⊔ C).mul_mem
          ((show H ≤ H ⊔ C from le_sup_left) hhInv)
          ((show C ≤ H ⊔ C from le_sup_right) hkC)
      simpa only [k, inv_mul_cancel_left] using hprod

/-- The two-generator subgroup in the preceding lemma is an internal
central factor in the precise sense used by BKN. -/
theorem twoGeneratorSubgroup_isInternalCentralFactor
    {D : Type u} [Group D] [Finite D]
    (hD : HasCentralCommutatorOfOrderTwo D)
    (x y : D) (hxy : ⁅x, y⁆ ≠ 1) :
    IsInternalCentralFactor (twoGeneratorSubgroup x y) where
  generate :=
    twoGeneratorSubgroup_sup_centralizer_eq_top hD x y hxy
  overlap :=
    (characteristicCenterImage_eq_inf_centralizer
      (twoGeneratorSubgroup x y)).symm

/-- The residual centralizer of an internal central factor has the same
center as the ambient group (both centers are viewed in the ambient
group).  This is the identity `Z(D) = Z(C)` used in the maximal BKN
decomposition. -/
theorem centralizer_centerImage_eq_center_of_isInternalCentralFactor
    {D : Type u} [Group D]
    {H : Subgroup D} (hH : IsInternalCentralFactor H) :
    characteristicCenterImage
        (Subgroup.centralizer (H : Set D)) =
      Subgroup.center D := by
  let K : Subgroup D := Subgroup.centralizer (H : Set D)
  rw [characteristicCenterImage_eq_inf_centralizer]
  apply le_antisymm
  · intro z hz
    rw [Subgroup.mem_center_iff]
    intro g
    let L : Subgroup D := Subgroup.centralizer ({z} : Set D)
    have hHL : H ≤ L := by
      intro h hh
      rw [Subgroup.mem_centralizer_singleton_iff]
      exact hz.1 h hh
    have hKL : K ≤ L := by
      intro k hk
      rw [Subgroup.mem_centralizer_singleton_iff]
      exact hz.2 k hk
    have hsupL : H ⊔ K ≤ L := sup_le hHL hKL
    have hgL : g ∈ L := by
      apply hsupL
      rw [hH.generate]
      exact Subgroup.mem_top g
    exact Subgroup.mem_centralizer_singleton_iff.mp hgL
  · exact le_inf
      (Subgroup.center_le_centralizer (H : Set D))
      (Subgroup.center_le_centralizer (K : Set D))

end LisiSabatini
