module

public import LisiSabatini.HallBergerFirstFrattiniBranch

/-!
# A rotation generator in the Hall--Berger square-image branch

In the remaining large-Frattini branch,

`Φ(G) = Z(C_G(Φ(G)))²`.

The center of the Frattini centralizer is cyclic.  Choosing a generator
`g` of that center therefore identifies the Frattini subgroup with the
ambient cyclic subgroup generated by `g²`.  This is the rotation
generator used in the final cyclic-maximal-subgroup argument.
-/

@[expose] public section

noncomputable section

namespace LisiSabatini

set_option backward.isDefEq.respectTransparency false

universe u

/-- The square range of a finite cyclic group generated by `g` is the
cyclic subgroup generated by `g²`. -/
theorem powMonoidHom_two_range_eq_zpowers_sq_of_zpowers_eq_top
    {A : Type u} [CommGroup A]
    (g : A) (hg : Subgroup.zpowers g = ⊤) :
    (powMonoidHom 2 : A →* A).range =
      Subgroup.zpowers (g ^ 2) := by
  calc
    (powMonoidHom 2 : A →* A).range =
        (⊤ : Subgroup A).map
          (powMonoidHom 2 : A →* A) :=
      MonoidHom.range_eq_map
        (powMonoidHom 2 : A →* A)
    _ = (Subgroup.zpowers g).map
          (powMonoidHom 2 : A →* A) := by
      rw [hg]
    _ = Subgroup.zpowers
          ((powMonoidHom 2 : A →* A) g) :=
      MonoidHom.map_zpowers
        (powMonoidHom 2 : A →* A) g
    _ = Subgroup.zpowers (g ^ 2) := rfl

/-- In the square-image branch one may choose a generator of the center
of the Frattini centralizer whose square generates the ambient Frattini
subgroup. -/
theorem exists_frattiniCentralizer_center_generator_with_frattini_eq_zpowers_sq
    {G : Type u} [Group G] [Finite G]
    (hG2 : IsPGroup 2 G)
    (hBKN :
      HasCyclicOmegaOneFrattiniCentralizerCenter 2 G)
    (hSquare :
      frattini G =
        frattiniCentralizerCenterSquareImage G) :
    ∃ g :
        Subgroup.center (frattiniCentralizer G),
      Subgroup.zpowers g = ⊤ ∧
      frattini G =
        Subgroup.zpowers
          ((((g :
              frattiniCentralizer G) : G)) ^ 2) := by
  classical
  let C : Subgroup G :=
    frattiniCentralizer G
  let Z : Subgroup C :=
    Subgroup.center C
  let ι : Z →* G :=
    C.subtype.comp Z.subtype
  have hZcyclic : IsCyclic Z :=
    frattiniCentralizer_center_isCyclic
      Nat.prime_two hG2 hBKN
  obtain ⟨g, hg⟩ :=
    isCyclic_iff_exists_zpowers_eq_top.mp
      hZcyclic
  refine ⟨g, hg, ?_⟩
  rw [hSquare]
  change
    ((powMonoidHom 2 : Z →* Z).range).map ι =
      Subgroup.zpowers ((ι g) ^ 2)
  rw [
    powMonoidHom_two_range_eq_zpowers_sq_of_zpowers_eq_top
      g hg,
    MonoidHom.map_zpowers]
  rfl

/-- In a nontrivial square-image branch the cyclic center has twice the
order of the Frattini subgroup. -/
theorem natCard_frattiniCentralizer_center_eq_two_mul_natCard_frattini
    {G : Type u} [Group G] [Finite G]
    (hG2 : IsPGroup 2 G)
    (hBKN :
      HasCyclicOmegaOneFrattiniCentralizerCenter 2 G)
    (hSquare :
      frattini G =
        frattiniCentralizerCenterSquareImage G)
    (hPhiNontrivial : 1 < Nat.card (frattini G)) :
    Nat.card
        (Subgroup.center (frattiniCentralizer G)) =
      2 * Nat.card (frattini G) := by
  classical
  let C : Subgroup G :=
    frattiniCentralizer G
  let Z : Subgroup C :=
    Subgroup.center C
  let R : Subgroup Z :=
    (powMonoidHom 2 : Z →* Z).range
  let ι : Z →* G :=
    C.subtype.comp Z.subtype
  let S : Subgroup G :=
    R.map ι
  have hZcyclic : IsCyclic Z :=
    frattiniCentralizer_center_isCyclic
      Nat.prime_two hG2 hBKN
  letI : IsCyclic Z := hZcyclic
  have hPhiS : frattini G = S := by
    simpa only [
      S, R, ι, C, Z,
      frattiniCentralizerCenterSquareImage] using
        hSquare
  let eR : R ≃* S :=
    Subgroup.equivMapOfInjective
      R ι (by
        intro x y hxy
        exact Subtype.ext
          (Subtype.ext hxy))
  have hcardS :
      Nat.card S = Nat.card R :=
    (Nat.card_congr eR.toEquiv).symm
  have hcardPhiR :
      Nat.card (frattini G) = Nat.card R := by
    rw [hPhiS]
    exact hcardS
  have hRnontrivial : 1 < Nat.card R := by
    omega
  have hZ2 : IsPGroup 2 Z :=
    (hG2.to_subgroup C).to_subgroup Z
  have htwoDvdZ : 2 ∣ Nat.card Z := by
    rcases hZ2.card_eq_or_dvd with hcard | hdvd
    · have hRcardLeZ :
          Nat.card R ≤ Nat.card Z :=
        calc
          Nat.card R ≤
              Nat.card (⊤ : Subgroup Z) :=
            Subgroup.card_le_of_le
              (show R ≤ (⊤ : Subgroup Z) from le_top)
          _ = Nat.card Z :=
            Subgroup.card_top
      rw [hcard] at hRcardLeZ
      omega
    · exact hdvd
  have hgcd : (Nat.card Z).gcd 2 = 2 :=
    Nat.gcd_eq_right_iff_dvd.mpr htwoDvdZ
  have hRindex : R.index = 2 := by
    simpa only [R, hgcd] using
      (IsCyclic.index_powMonoidHom_range Z 2)
  have hcardMul :
      Nat.card R * 2 = Nat.card Z := by
    simpa only [hRindex] using
      R.card_mul_index
  change Nat.card Z =
    2 * Nat.card (frattini G)
  omega

/-- The center rotation has order at least eight in the large
square-image branch. -/
theorem eight_le_natCard_frattiniCentralizer_center_of_two_lt_natCard_frattini
    {G : Type u} [Group G] [Finite G]
    (hG2 : IsPGroup 2 G)
    (hBKN :
      HasCyclicOmegaOneFrattiniCentralizerCenter 2 G)
    (hSquare :
      frattini G =
        frattiniCentralizerCenterSquareImage G)
    (hPhiLarge : 2 < Nat.card (frattini G)) :
    8 ≤ Nat.card
      (Subgroup.center (frattiniCentralizer G)) := by
  have hcard :=
    natCard_frattiniCentralizer_center_eq_two_mul_natCard_frattini
      hG2 hBKN hSquare (by omega)
  have hPhi2 :
      IsPGroup 2 (frattini G) :=
    hG2.to_subgroup (frattini G)
  have htwoDvdPhi :
      2 ∣ Nat.card (frattini G) := by
    rcases hPhi2.card_eq_or_dvd with hcardOne | hdvd
    · omega
    · exact hdvd
  omega

end LisiSabatini
