import LisiSabatini.HallBergerCyclicHeadSeed
import Mathlib.GroupTheory.IndexNormal

/-!
# The cyclic maximal subgroup produced by a Hall--Berger seed

For a Hall--Berger cyclic-head seed `(g,h)`, let `H = ⟨g,h⟩`.  The
rotation subgroup `⟨g⟩` has index exactly two in `H`: the quotient is
generated by the image of `h`, that image has square one, and it is
nontrivial.  Thus `H` is precisely the finite `2`-group with a cyclic
maximal subgroup to which the classical classification applies.
-/

noncomputable section

namespace LisiSabatini

set_option backward.isDefEq.respectTransparency false

universe u

/-- Proof-relevant input to the classification of finite `2`-groups
with a cyclic maximal subgroup, restricted to the noncentral-square
case needed by Hall--Berger. -/
structure CyclicMaximalTwoGroupData
    (H : Type u) [Group H] [Finite H] where
  rotation : H
  coset : H
  generate :
    Subgroup.zpowers rotation ⊔
      Subgroup.zpowers coset = ⊤
  rotation_index_two :
    (Subgroup.zpowers rotation).index = 2
  rotation_order_ge_eight :
    8 ≤ orderOf rotation
  cosetSquare_mem_rotation :
    coset ^ 2 ∈ Subgroup.zpowers rotation
  rotationSquare_not_commute :
    ¬ Commute (rotation ^ 2) coset

/-- The classical classification statement isolated from the
Hall--Berger reduction.  It is proved in
`CyclicMaximalTwoGroupClassification`.

The output is the maximal-class head already consumed by the affine
counting files.  This is a proposition definition, not an axiom. -/
def CyclicMaximalTwoGroupClassificationStatement : Prop :=
  ∀ (H : Type u) [Group H] [Finite H],
    IsPGroup 2 H →
    CyclicMaximalTwoGroupData H →
    Nonempty (BergerMaximalClassHead H)

namespace HallBergerCyclicHeadSeed

variable {G : Type u} [Group G] [Finite G]

/-- The two-generator subgroup attached to a cyclic-head seed. -/
def headSubgroup
    (seed : HallBergerCyclicHeadSeed G) :
    Subgroup G :=
  Subgroup.zpowers seed.rotation ⊔
    Subgroup.zpowers seed.coset

/-- A Hall--Berger seed produces a finite `2`-group with a cyclic
index-two subgroup and noncentral square action. -/
noncomputable def cyclicMaximalTwoGroupData
    (seed : HallBergerCyclicHeadSeed G) :
    CyclicMaximalTwoGroupData
      (seed.headSubgroup) := by
  classical
  let H : Subgroup G :=
    seed.headSubgroup
  let aH : H :=
    ⟨seed.rotation, by
      exact
        (show Subgroup.zpowers seed.rotation ≤ H
          from le_sup_left)
          (Subgroup.mem_zpowers seed.rotation)⟩
  let bH : H :=
    ⟨seed.coset, by
      exact
        (show Subgroup.zpowers seed.coset ≤ H
          from le_sup_right)
          (Subgroup.mem_zpowers seed.coset)⟩
  let A : Subgroup H :=
    Subgroup.zpowers aH
  have hmapA :
      A.map H.subtype =
        Subgroup.zpowers seed.rotation := by
    simpa only [A, aH] using
      MonoidHom.map_zpowers H.subtype aH
  have hmapB :
      (Subgroup.zpowers bH).map H.subtype =
        Subgroup.zpowers seed.coset := by
    simpa only [bH] using
      MonoidHom.map_zpowers H.subtype bH
  have hgenerate :
      A ⊔ Subgroup.zpowers bH = ⊤ := by
    apply
      (Subgroup.map_injective
        H.subtype_injective)
    calc
      (A ⊔ Subgroup.zpowers bH).map
          H.subtype =
          A.map H.subtype ⊔
            (Subgroup.zpowers bH).map
              H.subtype :=
        Subgroup.map_sup A
          (Subgroup.zpowers bH) H.subtype
      _ = Subgroup.zpowers seed.rotation ⊔
            Subgroup.zpowers seed.coset := by
        rw [hmapA, hmapB]
      _ = H := rfl
      _ = (⊤ : Subgroup H).map
            H.subtype := by
        calc
          H = H.subtype.range :=
            (Subgroup.range_subtype H).symm
          _ = (⊤ : Subgroup H).map
                H.subtype :=
            MonoidHom.range_eq_map H.subtype
  have hseedRotationNormal :
      (Subgroup.zpowers seed.rotation).Normal :=
    seed.rotation_normal
  letI :
      (Subgroup.zpowers seed.rotation).Normal :=
    hseedRotationNormal
  have hANormal : A.Normal := by
    have hcomap :
        (Subgroup.zpowers seed.rotation).comap
            H.subtype = A := by
      apply le_antisymm
      · intro x hx
        have hxMap :
            (x : G) ∈ A.map H.subtype := by
          rw [hmapA]
          exact hx
        obtain ⟨y, hyA, hyx⟩ :=
          Subgroup.mem_map.mp hxMap
        have hyEq : y = x :=
          H.subtype_injective hyx
        simpa only [hyEq] using hyA
      · intro x hx
        change (x : G) ∈
          Subgroup.zpowers seed.rotation
        rw [← hmapA]
        exact
          Subgroup.mem_map.mpr
            ⟨x, hx, rfl⟩
    rw [← hcomap]
    infer_instance
  letI : A.Normal := hANormal
  have hbSqA : bH ^ 2 ∈ A := by
    have hbSqMap :
        ((bH ^ 2 : H) : G) ∈
          A.map H.subtype := by
      rw [hmapA]
      exact
        (Subgroup.zpowers_le_of_mem
          (Subgroup.npow_mem_zpowers
            seed.rotation 2))
          seed.cosetSquare_mem_rotationSquare
    obtain ⟨y, hyA, hyEq⟩ :=
      Subgroup.mem_map.mp hbSqMap
    have hyEq' : y = bH ^ 2 :=
      H.subtype_injective hyEq
    simpa only [hyEq'] using hyA
  have hbNotA : bH ∉ A := by
    intro hbA
    have hbCenterImage :
        seed.coset ∈
          characteristicCenterImage
            (frattiniCentralizer G) := by
      rw [← seed.rotation_generates_centerImage,
        ← hmapA]
      exact
        Subgroup.mem_map.mpr
          ⟨bH, hbA, rfl⟩
    have hbC :
        seed.coset ∈
          frattiniCentralizer G := by
      rw [characteristicCenterImage_eq_inf_centralizer]
        at hbCenterImage
      exact hbCenterImage.1
    exact
      seed.coset_not_mem_frattiniCentralizer
        hbC
  let Q := H ⧸ A
  let q : H →* Q :=
    QuotientGroup.mk' A
  have hAmapBot : A.map q = ⊥ := by
    rw [Subgroup.map_eq_bot_iff,
      QuotientGroup.ker_mk']
  have hqGenerate :
      Subgroup.zpowers (q bH) = ⊤ := by
    have hmapGenerate :=
      congrArg
        (fun K : Subgroup H => K.map q)
        hgenerate
    change
      (A ⊔ Subgroup.zpowers bH).map q =
        (⊤ : Subgroup H).map q
      at hmapGenerate
    rw [
      Subgroup.map_sup,
      hAmapBot,
      MonoidHom.map_zpowers,
      bot_sup_eq,
      Subgroup.map_top_of_surjective
        q (QuotientGroup.mk'_surjective A)]
      at hmapGenerate
    exact hmapGenerate
  have hqbSq : (q bH) ^ 2 = 1 := by
    rw [← map_pow,
      QuotientGroup.mk'_apply,
      QuotientGroup.eq_one_iff]
    exact hbSqA
  have hqbNe : q bH ≠ 1 := by
    intro hqb
    apply hbNotA
    exact
      (QuotientGroup.eq_one_iff bH).mp
        (by
          simpa only [q,
            QuotientGroup.mk'_apply] using hqb)
  letI : Fact (Nat.Prime 2) :=
    ⟨Nat.prime_two⟩
  have hqbOrder :
      orderOf (q bH) = 2 :=
    orderOf_eq_prime hqbSq hqbNe
  have hcardQ : Nat.card Q = 2 := by
    calc
      Nat.card Q =
          Nat.card (⊤ : Subgroup Q) :=
        Subgroup.card_top.symm
      _ = Nat.card
            (Subgroup.zpowers (q bH)) := by
        rw [hqGenerate]
      _ = orderOf (q bH) :=
        by rw [Nat.card_zpowers]
      _ = 2 := hqbOrder
  have hAindex : A.index = 2 := by
    rw [Subgroup.index_eq_card]
    exact hcardQ
  have haOrder :
      orderOf aH =
        orderOf seed.rotation :=
    by
      simpa only [aH] using
        (orderOf_injective
          H.subtype H.subtype_injective aH).symm
  have hnoncommute :
      ¬ Commute (aH ^ 2) bH := by
    intro hcommute
    apply seed.rotationSquare_not_commute
    exact congrArg Subtype.val hcommute
  exact
    {
      rotation := aH
      coset := bH
      generate := by
        simpa only [A] using hgenerate
      rotation_index_two := by
        simpa only [A] using hAindex
      rotation_order_ge_eight := by
        rw [haOrder]
        exact seed.rotation_order_ge_eight
      cosetSquare_mem_rotation := by
        simpa only [A] using hbSqA
      rotationSquare_not_commute :=
        hnoncommute
    }

/-- The head subgroup of a Hall--Berger seed is itself a `2`-group. -/
theorem headSubgroup_isPGroup
    (hG2 : IsPGroup 2 G)
    (seed : HallBergerCyclicHeadSeed G) :
    IsPGroup 2 seed.headSubgroup :=
  hG2.to_subgroup seed.headSubgroup

end HallBergerCyclicHeadSeed

end LisiSabatini
