import LisiSabatini.ImprimitiveIndexedBaseColor
import LisiSabatini.SemiregularTopCore

/-!
# The exact action on the bundle of block vectors

An imprimitive linear element transports a vector in one block to a vector
in another block.  The resulting action on pairs `(i, w)` records exactly the
colour transport contributed by the acting component; it does not enlarge
the transporters to an arbitrary subgroup generated by basis-dependent local
factors.

This file derives the block-factor cocycle from `action_apply`, constructs the
exact bundle action, and proves a single-marker stabilizer theorem.  A unique
bundle orbit at one block kills a semiregular top, while block-indexed base
regularity kills the remaining kernel.
-/

noncomputable section

namespace LisiSabatini

universe uI uR uW

variable {I : Type uI} {R : Type uR} {W : Type uW}
variable [Semiring R] [AddCommMonoid W] [Module R W]

namespace ImprimitiveLinearActionData

variable {H : Subgroup
    (LinearMap.GeneralLinearGroup R (I → W))}
variable {L : Subgroup (LinearMap.GeneralLinearGroup R W)}

/-! ## Exact transport on the block bundle -/

/-- Transport a vector in block `i` by one imprimitive element. -/
def bundleMap
    (D : ImprimitiveLinearActionData H L) (g : H) : I × W → I × W :=
  fun z ↦
    (D.blockPerm g z.1,
      (D.blockLinear g (D.blockPerm g z.1)).1 • z.2)

@[simp]
theorem bundleMap_one
    (D : ImprimitiveLinearActionData H L) (z : I × W) :
    D.bundleMap 1 z = z := by
  rcases z with ⟨i, w⟩
  simp [bundleMap]

/-- Bundle transport respects multiplication. -/
theorem bundleMap_mul
    (D : ImprimitiveLinearActionData H L) (g h : H) (z : I × W) :
    D.bundleMap (g * h) z = D.bundleMap g (D.bundleMap h z) := by
  rcases z with ⟨i, w⟩
  apply Prod.ext
  · simp [bundleMap]
  · change
      (D.blockLinear (g * h)
          (D.blockPerm (g * h) i)).1 • w =
        (D.blockLinear g (D.blockPerm g (D.blockPerm h i))).1 •
          ((D.blockLinear h (D.blockPerm h i)).1 • w)
    rw [D.blockLinear_mul]
    simp [mul_smul]

/-- The exact bundle transport as an equivalence. -/
def bundleEquiv
    (D : ImprimitiveLinearActionData H L) (g : H) : Equiv.Perm (I × W) where
  toFun := D.bundleMap g
  invFun := D.bundleMap g⁻¹
  left_inv z := by
    rw [← D.bundleMap_mul]
    simp
  right_inv z := by
    rw [← D.bundleMap_mul]
    simp

/-- The exact action of the imprimitive group on the bundle of block
vectors. -/
def bundlePerm
    (D : ImprimitiveLinearActionData H L) : H →* Equiv.Perm (I × W) where
  toFun := D.bundleEquiv
  map_one' := by
    apply Equiv.ext
    intro z
    exact D.bundleMap_one z
  map_mul' g h := by
    apply Equiv.ext
    intro z
    exact D.bundleMap_mul g h z

@[simp]
theorem bundlePerm_apply
    (D : ImprimitiveLinearActionData H L) (g : H) (z : I × W) :
    D.bundlePerm g z = D.bundleMap g z :=
  rfl

/-- Two block vectors have the same exact component colour when one is
transported to the other by an element of the imprimitive group. -/
def SameBundleOrbit
    (D : ImprimitiveLinearActionData H L) (a b : I × W) : Prop :=
  ∃ g : H, D.bundleMap g a = b

@[refl]
theorem sameBundleOrbit_refl
    (D : ImprimitiveLinearActionData H L) (a : I × W) :
    D.SameBundleOrbit a a := by
  exact ⟨1, D.bundleMap_one a⟩

@[symm]
theorem sameBundleOrbit_symm
    (D : ImprimitiveLinearActionData H L) {a b : I × W}
    (hab : D.SameBundleOrbit a b) :
    D.SameBundleOrbit b a := by
  obtain ⟨g, rfl⟩ := hab
  refine ⟨g⁻¹, ?_⟩
  rw [← D.bundleMap_mul]
  simp

@[trans]
theorem sameBundleOrbit_trans
    (D : ImprimitiveLinearActionData H L) {a b c : I × W}
    (hab : D.SameBundleOrbit a b) (hbc : D.SameBundleOrbit b c) :
    D.SameBundleOrbit a c := by
  obtain ⟨g, rfl⟩ := hab
  obtain ⟨h, rfl⟩ := hbc
  exact ⟨h * g, D.bundleMap_mul h g a⟩

/-! ## A unique exact bundle marker -/

/-- The exact component orbit of `(omega, x omega)` meets the graph of `x`
only over the marker block `omega`. -/
def UniqueBundleOrbitAt
    (D : ImprimitiveLinearActionData H L) (x : I → W) (omega : I) : Prop :=
  ∀ i : I, D.SameBundleOrbit (omega, x omega) (i, x i) → i = omega

/-- An element fixing a product vector transports every point of its graph
to the corresponding point over the permuted block. -/
theorem bundleMap_graph_of_fix
    (D : ImprimitiveLinearActionData H L)
    (g : H) (x : I → W) (hfix : g.1 • x = x) (i : I) :
    D.bundleMap g (i, x i) =
      (D.blockPerm g i, x (D.blockPerm g i)) := by
  apply Prod.ext
  · rfl
  · have hi := D.action_apply g x (D.blockPerm g i)
    rw [hfix] at hi
    simpa [bundleMap] using hi.symm

/-- A unique exact bundle marker forces every point stabilizer element to
fix the marker block in the top action. -/
theorem blockPerm_fix_of_mem_stabilizer_of_uniqueBundleOrbit
    (D : ImprimitiveLinearActionData H L)
    (x : I → W) (omega : I) (hmarker : D.UniqueBundleOrbitAt x omega)
    (g : H) (hg : g ∈ MulAction.stabilizer H x) :
    D.blockPerm g omega = omega := by
  apply hmarker (D.blockPerm g omega)
  refine ⟨g, ?_⟩
  exact D.bundleMap_graph_of_fix g x
    (MulAction.mem_stabilizer_iff.mp hg) omega

/-- **Exact-bundle single-marker stabilizer theorem.**

Block-indexed base regularity makes the top map injective on the point
stabilizer.  Exact bundle-orbit uniqueness makes its image fix `omega`, and
semiregularity at `omega` makes that image trivial. -/
theorem stabilizer_eq_bot_of_indexedBase_regular_of_uniqueBundleOrbit_of_semiregularAt
    (D : ImprimitiveLinearActionData H L)
    (B : I → Subgroup L)
    (hkernel : BlockPermKernelFactorsInAt D B)
    (x : I → W) (omega : I)
    (hbase : ∀ i, MulAction.stabilizer (B i) (x i) = ⊥)
    (hmarker : D.UniqueBundleOrbitAt x omega)
    (hsemi : IsSemiregularAt D.blockPerm.range omega) :
    MulAction.stabilizer H x = ⊥ := by
  apply (Subgroup.eq_bot_iff_forall _).mpr
  intro g hg
  let sigma : D.blockPerm.range := ⟨D.blockPerm g, ⟨g, rfl⟩⟩
  have hfix : sigma ∈ MulAction.stabilizer D.blockPerm.range omega := by
    apply MulAction.mem_stabilizer_iff.mpr
    exact D.blockPerm_fix_of_mem_stabilizer_of_uniqueBundleOrbit
      x omega hmarker g hg
  rw [hsemi] at hfix
  have hperm : D.blockPerm g = 1 := congrArg Subtype.val hfix
  let gs : MulAction.stabilizer H x := ⟨g, hg⟩
  have hgs : gs = 1 := by
    apply pointStabilizerBlockPerm_injective_of_indexedBase_regular
      D B hkernel x hbase
    simpa [pointStabilizerBlockPerm] using hperm
  exact congrArg Subtype.val hgs

end ImprimitiveLinearActionData

end LisiSabatini
