import LisiSabatini.AffineReductionCore

/-!
# Normal components in the affine chief-factor reduction

The elementary-abelian lift naturally places all cross-characteristic local
actions inside the single image of ambient conjugation.  If

`L_p = O_p(G / N)` pulled back to `G` and `A_p = P_p \cap L_p`,

then the existing quotient calculation gives `N \vee A_p = L_p`.  The
section acts trivially on itself, so the images of `A_p` and `L_p` in the
common action are equal.  Consequently the local image is a normal
`p`-subgroup of that common action, and distinct local images commute.

This file also states normal-component affine synchronization (NCAS) in the
form consumed by the group-theoretic reduction and proves the corresponding
elementary-abelian lifting theorem.  NCAS itself remains the new linear input.
-/

noncomputable section

namespace LisiSabatini

universe uG uI uV

variable {G : Type uG} [Group G]

namespace ElementaryAbelianSection

variable (S : ElementaryAbelianSection G)

/-- The common linear action generated by ambient conjugation on the
elementary-abelian section. -/
abbrev commonAction : Subgroup
    (LinearMap.GeneralLinearGroup (ZMod S.r) (Fin S.d → ZMod S.r)) :=
  S.conjugation.range

/-- The image of an ambient subgroup inside the common action.  Keeping this
as a subgroup of `S.commonAction` records normality in the correct ambient
group rather than incorrectly asking for normality in the full general
linear group. -/
def actionImage (A : Subgroup G) : Subgroup S.commonAction :=
  A.map S.conjugation.rangeRestrict

/-- The section acts trivially on itself by conjugation. -/
theorem N_le_conjugation_ker : S.N ≤ S.conjugation.ker := by
  intro n hn
  rw [S.mem_conjugation_ker_iff]
  intro m
  let nN : S.N := ⟨n, hn⟩
  apply Subtype.ext
  rw [coe_normalConj]
  have hcomm : n * (m : G) = (m : G) * n :=
    congrArg Subtype.val (S.commute nN m).eq
  exact mul_inv_eq_iff_eq_mul.mpr hcomm

/-- The image in the common action of the elementary-abelian section itself
is trivial. -/
@[simp]
theorem actionImage_N : S.actionImage S.N = ⊥ := by
  apply (Subgroup.eq_bot_iff_forall _).mpr
  intro g hg
  obtain ⟨n, hn, rfl⟩ := Subgroup.mem_map.mp hg
  apply Subtype.ext
  exact MonoidHom.mem_ker.mp (S.N_le_conjugation_ker hn)

/-- Generic image equality: adjoining the section does not change an action
image.  This is the reusable formal form of `ρ(NA) = ρ(A)`. -/
theorem actionImage_eq_of_sup_eq
    (A L : Subgroup G) (hsup : S.N ⊔ A = L) :
    S.actionImage A = S.actionImage L := by
  calc
    S.actionImage A = ⊥ ⊔ S.actionImage A := by simp
    _ = S.actionImage S.N ⊔ S.actionImage A := by rw [S.actionImage_N]
    _ = S.actionImage (S.N ⊔ A) := by
      exact (Subgroup.map_sup S.N A S.conjugation.rangeRestrict).symm
    _ = S.actionImage L := by rw [hsup]

/-- Mapping an action image back to the full general linear group recovers
the range of the restricted conjugation representation. -/
theorem map_actionImage_subtype (A : Subgroup G) :
    (S.actionImage A).map S.commonAction.subtype =
      (S.restrictedConjugation A).range := by
  rw [actionImage, Subgroup.map_map]
  rw [MonoidHom.subtype_comp_rangeRestrict]
  rw [restrictedConjugation, MonoidHom.range_comp, Subgroup.range_subtype]

/-- Pullback to `G` of the quotient `p`-core. -/
def quotientCorePullback [S.N.Normal] (p : ℕ) : Subgroup G :=
  (pCore p (G ⧸ S.N)).comap (QuotientGroup.mk' S.N)

/-- The canonical Sylow section over the quotient `p`-core. -/
def quotientCoreComplement [S.N.Normal] {p : ℕ} (P : Sylow p G) : Subgroup G :=
  (P : Subgroup G) ⊓ S.quotientCorePullback p

/-- The cross-characteristic local component, as a subgroup of the single
common action. -/
def normalComponent [S.N.Normal] {p : ℕ} (P : Sylow p G) :
    Subgroup S.commonAction :=
  S.actionImage (S.quotientCoreComplement P)

/-- The canonical local component is the image of the whole pullback of the
quotient core.  This is `ρ(A_p) = ρ(L_p)` with all objects explicit. -/
theorem localImage_eq_image_pullbackCore [S.N.Normal]
    {p : ℕ} (P : Sylow p G)
    (himage : pCore p (G ⧸ S.N) ≤
      (P : Subgroup G).map (QuotientGroup.mk' S.N)) :
    S.normalComponent P = S.actionImage (S.quotientCorePullback p) := by
  apply S.actionImage_eq_of_sup_eq
  simpa [quotientCoreComplement, quotientCorePullback] using
    sup_inf_comap_quotient_pCore_eq S.N P himage

/-- Ambient-`GL` form of `localImage_eq_image_pullbackCore`. -/
theorem localImage_ambient_eq_image_pullbackCore [S.N.Normal]
    {p : ℕ} (P : Sylow p G)
    (himage : pCore p (G ⧸ S.N) ≤
      (P : Subgroup G).map (QuotientGroup.mk' S.N)) :
    (S.normalComponent P).map S.commonAction.subtype =
      (S.restrictedConjugation (S.quotientCorePullback p)).range := by
  rw [S.localImage_eq_image_pullbackCore P himage,
    S.map_actionImage_subtype]

/-- The ambient image of a local component is exactly the faithful image
used by the existing affine-fibre equivalence. -/
theorem localImage_ambient_eq_restrictedConjugation_range [S.N.Normal]
    {p : ℕ} (P : Sylow p G) :
    (S.normalComponent P).map S.commonAction.subtype =
      (S.restrictedConjugation (S.quotientCoreComplement P)).range := by
  exact S.map_actionImage_subtype (S.quotientCoreComplement P)

/-- Every local component is a `p`-group. -/
theorem localImage_isPGroup [S.N.Normal]
    {p : ℕ} (P : Sylow p G) : IsPGroup p (S.normalComponent P) := by
  exact (P.isPGroup'.to_inf_left).map S.conjugation.rangeRestrict

/-- Once the quotient core lies in the image of the chosen Sylow subgroup,
the corresponding local component is normal in the common action. -/
theorem localImage_normal [S.N.Normal]
    {p : ℕ} (P : Sylow p G)
    (himage : pCore p (G ⧸ S.N) ≤
      (P : Subgroup G).map (QuotientGroup.mk' S.N)) :
    (S.normalComponent P).Normal := by
  rw [S.localImage_eq_image_pullbackCore P himage]
  have hL : (S.quotientCorePullback p).Normal := by
    dsimp [quotientCorePullback]
    exact Subgroup.Normal.comap (pCore_normal p (G ⧸ S.N))
      (QuotientGroup.mk' S.N)
  exact Subgroup.Normal.map hL S.conjugation.rangeRestrict
    S.conjugation.rangeRestrict_surjective

/-- A quotient strong-intersection equality supplies the image-containment
hypothesis used by the normal-component lemmas. -/
theorem quotientCore_le_sylow_map_of_sylowInter_eq [S.N.Normal] [Finite G]
    {p : ℕ} [Fact p.Prime] (P : Sylow p G) (x : G)
    (hquot :
      sylowInter (P.mapSurjective (QuotientGroup.mk'_surjective S.N))
          (QuotientGroup.mk' S.N x) = pCore p (G ⧸ S.N)) :
    pCore p (G ⧸ S.N) ≤
      (P : Subgroup G).map (QuotientGroup.mk' S.N) := by
  intro y hy
  have hy' : y ∈
      sylowInter (P.mapSurjective (QuotientGroup.mk'_surjective S.N))
        (QuotientGroup.mk' S.N x) := by
    rw [hquot]
    exact hy
  exact hy'.1

/-- Local components belonging to distinct prime characteristics commute
elementwise. -/
theorem localImages_commute_of_ne [S.N.Normal]
    {p q : ℕ} [Fact p.Prime] [Fact q.Prime] (hpq : p ≠ q)
    (P : Sylow p G) (Q : Sylow q G)
    (himageP : pCore p (G ⧸ S.N) ≤
      (P : Subgroup G).map (QuotientGroup.mk' S.N))
    (himageQ : pCore q (G ⧸ S.N) ≤
      (Q : Subgroup G).map (QuotientGroup.mk' S.N))
    {a b : S.commonAction}
    (ha : a ∈ S.normalComponent P) (hb : b ∈ S.normalComponent Q) :
    Commute a b :=
  normalPSubgroups_commute_of_ne hpq
    (S.localImage_isPGroup P) (S.localImage_normal P himageP)
    (S.localImage_isPGroup Q) (S.localImage_normal Q himageQ) ha hb

end ElementaryAbelianSection

/-- Normal-component affine synchronization on an arbitrary `ZMod r` module.

This representation-independent form is useful for block decompositions and
transport along linear equivalences.  The chief-factor-facing predicate below
is its coordinate-space specialization. -/
def NormalComponentAffineSynchronizationOn
    (r : ℕ) (V : Type uV)
    [AddCommGroup V] [Module (ZMod r) V]
    (K : Subgroup (LinearMap.GeneralLinearGroup (ZMod r) V)) : Prop :=
  ∀ {I : Type uI} [Fintype I] (p : I → ℕ),
    (∀ i, Nat.Prime (p i)) →
    Function.Injective p →
    (∀ i, p i ≠ 2) →
    (∀ i, p i ≠ r) →
    ∀ H : I → Subgroup K,
      (∀ i, (H i).Normal) →
      (∀ i, IsPGroup (p i) (H i)) →
      ∀ t : I → V,
        ∃ v, ∀ i,
          MulAction.stabilizer ((H i).map K.subtype) (v + t i) = ⊥

/-- Normal-component affine synchronization for one common linear action.

The components are subgroups of `K`, so their normality is stated in the
mathematically correct common ambient group.  Regularity is expressed after
mapping them into `GL(V)`; this makes the interface directly compatible with
the existing affine reduction. -/
def NormalComponentAffineSynchronization
    (r d : ℕ)
    (K : Subgroup
      (LinearMap.GeneralLinearGroup (ZMod r) (Fin d → ZMod r))) : Prop :=
  ∀ {I : Type uI} [Fintype I] (p : I → ℕ),
    (∀ i, Nat.Prime (p i)) →
    Function.Injective p →
    (∀ i, p i ≠ 2) →
    (∀ i, p i ≠ r) →
    ∀ H : I → Subgroup K,
      (∀ i, (H i).Normal) →
      (∀ i, IsPGroup (p i) (H i)) →
      ∀ t : I → (Fin d → ZMod r),
        ∃ v, ∀ i,
          MulAction.stabilizer ((H i).map K.subtype) (v + t i) = ⊥

/-- The original coordinate predicate is definitionally the arbitrary-module
predicate on `Fin d → ZMod r`. -/
theorem normalComponentAffineSynchronization_iff_on
    (r d : ℕ)
    (K : Subgroup
      (LinearMap.GeneralLinearGroup (ZMod r) (Fin d → ZMod r))) :
    NormalComponentAffineSynchronization.{uI} r d K ↔
      NormalComponentAffineSynchronizationOn.{uI} r
        (Fin d → ZMod r) K :=
  Iff.rfl

namespace ElementaryAbelianSection

/-- Elementary-abelian lifting from normal-component affine
synchronization.  Unlike the original lift, the linear hypothesis is asked
only for the normal prime components which actually arise in the common
conjugation action. -/
theorem strongLisiSabatini_lift_normalComponents
    (S : ElementaryAbelianSection G) [S.N.Normal] [Finite G]
    (hodd : Odd (Nat.card G))
    (hquot : StrongLisiSabatini.{uG, uI} (G ⧸ S.N))
    (hNCAS : NormalComponentAffineSynchronization.{uI}
      S.r S.d S.commonAction) :
    StrongLisiSabatini.{uG, uI} G := by
  intro I _ p hp hinj P
  let Pbar : ∀ i, Sylow (p i) (G ⧸ S.N) := fun i ↦ by
    letI : Fact (p i).Prime := ⟨hp i⟩
    exact (P i).mapSurjective (QuotientGroup.mk'_surjective S.N)
  obtain ⟨xbar, hxbar⟩ := hquot p hp hinj Pbar
  obtain ⟨x, hx⟩ := QuotientGroup.mk'_surjective S.N xbar
  have hxquot (i : I) :
      sylowInter (Pbar i) (QuotientGroup.mk' S.N x) =
        pCore (p i) (G ⧸ S.N) := by
    rw [hx]
    exact hxbar i
  let J := {i : I // p i ≠ 2 ∧ p i ≠ S.r}
  let H : J → Subgroup S.commonAction := fun j ↦
    S.normalComponent (P j.1)
  let localData := fun j : J ↦ by
    letI : Fact (p j.1).Prime := ⟨hp j.1⟩
    exact S.exists_translation_sylowInter_eq_pCore_iff_regular
      (P j.1) x j.2.2 (hxquot j.1)
  let t : J → S.N := fun j ↦ Classical.choose (localData j)
  have ht (j : J) := Classical.choose_spec (localData j)
  have himage (j : J) : pCore (p j.1) (G ⧸ S.N) ≤
      (P j.1 : Subgroup G).map (QuotientGroup.mk' S.N) := by
    letI : Fact (p j.1).Prime := ⟨hp j.1⟩
    exact S.quotientCore_le_sylow_map_of_sylowInter_eq
      (P j.1) x (hxquot j.1)
  have hpJ (j : J) : Nat.Prime (p j.1) := hp j.1
  have hinjJ : Function.Injective (fun j : J ↦ p j.1) := by
    intro i j hij
    apply Subtype.ext
    exact hinj hij
  have hnormal (j : J) : (H j).Normal := by
    dsimp [H]
    exact S.localImage_normal (P j.1) (himage j)
  have hHp (j : J) : IsPGroup (p j.1) (H j) := by
    dsimp [H]
    exact S.localImage_isPGroup (P j.1)
  obtain ⟨v, hv⟩ := hNCAS (fun j : J ↦ p j.1) hpJ hinjJ
    (fun j ↦ j.2.1) (fun j ↦ j.2.2) H hnormal hHp
    (fun j ↦ S.coordinates (Additive.ofMul (t j)))
  let n : S.N := Additive.toMul (S.coordinates.symm v)
  refine ⟨(n : G) * x, fun i ↦ ?_⟩
  by_cases hiTwo : p i = 2
  · exact sylowInter_eq_pCore_of_eq_two hodd hiTwo (P i) ((n : G) * x)
  by_cases hiSection : p i = S.r
  · letI : Fact (p i).Prime := ⟨hp i⟩
    have hNp : IsPGroup (p i) S.N := by
      simpa [hiSection] using S.isPGroup_N
    apply sylowInter_eq_pCore_of_quotient_eq S.N hNp (P i) ((n : G) * x)
    have hmn : QuotientGroup.mk' S.N (n : G) = 1 :=
      (QuotientGroup.eq_one_iff (n : G)).mpr n.2
    simpa [map_mul, hmn] using hxquot i
  · let j : J := ⟨i, hiTwo, hiSection⟩
    apply (ht j n).mpr
    have hvj := hv j
    dsimp [H] at hvj
    rw [S.localImage_ambient_eq_restrictedConjugation_range (P j.1)] at hvj
    simpa [t, n, quotientCoreComplement, quotientCorePullback] using hvj

end ElementaryAbelianSection

end LisiSabatini
