module

public import LisiSabatini.FiniteCertificates.TableCertificate
public import Mathlib.Algebra.Group.Action.Pointwise.Finset
public import Mathlib.GroupTheory.GroupAction.Defs

/-!
# Subgroup certificates from generator actions and reachability

Left multiplication is injective. Consequently, a generator that maps a
finite row into itself permutes that row. The subgroup generated by these
elements therefore stabilizes the row. If the identity belongs to the row,
the generated subgroup is contained in it; reachability supplies the reverse
inclusion. This certifies a subgroup without its full multiplication table.
-/

@[expose] public section

open scoped Pointwise

namespace LisiSabatini.FiniteCertificates

variable {G : Type*} [Group G]

/-- Generator invariance of a finite row containing the identity forces the
entire generated subgroup to lie in that row. The ambient group may be infinite. -/
theorem closure_subset_finset_of_generator_invariance
    (s : Finset G) (A : Set G) (hone : 1 ∈ s)
    (hgen : ∀ a ∈ A, ∀ x ∈ s, a * x ∈ s) :
    ∀ x ∈ Subgroup.closure A, x ∈ s := by
  classical
  have hstab : Subgroup.closure A ≤ MulAction.stabilizer G s := by
    apply (Subgroup.closure_le _).mpr
    intro a ha
    change a • s = s
    apply Finset.eq_of_subset_of_card_le
    · intro y hy
      obtain ⟨x, hx, rfl⟩ := Finset.mem_smul_finset.mp hy
      exact hgen a ha x hx
    · rw [Finset.card_smul_finset]
  intro x hx
  have hxs : x • s = s := MulAction.mem_stabilizer_iff.mp (hstab hx)
  have hxone : x * 1 ∈ x • s := (Finset.mul_mem_smul_finset_iff x).mpr hone
  simpa only [hxs, mul_one] using hxone

/-- Generator invariance and reachability identify the finite row with the
generated subgroup, without assuming that the row is already a subgroup. -/
theorem finset_eq_closure_of_generator_invariance_and_reachability
    (s : Finset G) (A : Set G) (hone : 1 ∈ s)
    (hgen : ∀ a ∈ A, ∀ x ∈ s, a * x ∈ s)
    (hreach : ∀ x ∈ s, x ∈ Subgroup.closure A) :
    (s : Set G) = (Subgroup.closure A : Set G) := by
  ext x
  exact ⟨hreach x, closure_subset_finset_of_generator_invariance s A hone hgen x⟩

/-- The generator-action certificate implies the original full subgroup
check, so existing checked-subgroup and checked-Sylow APIs can be reused. -/
theorem subgroupCheck_of_generator_invariance_and_reachability
    [DecidableEq G]
    (s : Finset G) (A : Set G) (hone : 1 ∈ s)
    (hgen : ∀ a ∈ A, ∀ x ∈ s, a * x ∈ s)
    (hreach : ∀ x ∈ s, x ∈ Subgroup.closure A) :
    subgroupCheck s = true := by
  have hback := closure_subset_finset_of_generator_invariance s A hone hgen
  apply decide_eq_true
  refine ⟨hone, fun x hx ↦ ⟨?_, fun y hy ↦ ?_⟩⟩
  · exact hback _ ((Subgroup.closure A).inv_mem (hreach x hx))
  · exact hback _ ((Subgroup.closure A).mul_mem (hreach x hx) (hreach y hy))

/-- A rooted, earlier-parent traversal proves that every indexed element
belongs to the subgroup generated by the edge labels. -/
theorem indexed_bfs_mem_closure
    {n : ℕ} (r : Fin (n + 1) → G) (A : Set G)
    (parent : Fin (n + 1) → Fin (n + 1)) (a : Fin (n + 1) → G)
    (hroot : r 0 = 1)
    (hparent : ∀ k, 0 < k → parent k < k)
    (ha : ∀ k, 0 < k → a k ∈ A)
    (hedge : ∀ k, 0 < k → r k = a k * r (parent k)) :
    ∀ k, r k ∈ Subgroup.closure A := by
  intro k
  refine (measure (fun k : Fin (n + 1) ↦ k.val)).wf.induction
    (C := fun k ↦ r k ∈ Subgroup.closure A) k (fun k ih ↦ ?_)
  by_cases hk : k = 0
  · subst k
    rw [hroot]
    exact (Subgroup.closure A).one_mem
  · have hpos : 0 < k := Fin.pos_iff_ne_zero.mpr hk
    rw [hedge k hpos]
    exact (Subgroup.closure A).mul_mem (Subgroup.subset_closure (ha k hpos))
      (ih (parent k) (hparent k hpos))

end LisiSabatini.FiniteCertificates
