module

public import Mathlib.GroupTheory.PGroup
public import Mathlib.Data.Fin.VecNotation
public import Mathlib.Data.Set.Card
public import Mathlib.Tactic.FinCases

/-!
# Certified small tail rows for symmetric double-coset checks

The rows below enumerate the trivial group on one point, the symmetric
group on two points, and the standard dihedral Sylow subgroup on four
points. The four-point rows are ordered lexicographically by their images.
All finite closure checks are proved by kernel reduction with `decide`.
-/

@[expose] public section

namespace LisiSabatini

open Equiv

/-- A subgroup specified by a finite row whose closure data are checked
separately. Its carrier is exactly the range of the row. -/
def subgroupOfClosedPermutationRows {n k : ℕ}
    (row : Fin k → Perm (Fin n))
    (hone : ∃ i, row i = 1)
    (hmul : ∀ i j, ∃ l, row l = row i * row j)
    (hinv : ∀ i, ∃ j, row j = (row i)⁻¹) : Subgroup (Perm (Fin n)) where
  carrier := Set.range row
  one_mem' := hone
  mul_mem' := by
    rintro _ _ ⟨i, rfl⟩ ⟨j, rfl⟩
    exact hmul i j
  inv_mem' := by
    rintro _ ⟨i, rfl⟩
    exact hinv i

def tailRow1 (_ : Fin 1) : Perm (Fin 1) := 1

/-- Literal images of the two permutations on two points. -/
def tailRow2Data : Fin 2 → Fin 2 → Fin 2 := ![![0, 1], ![1, 0]]

theorem tailRow2Data_involutive :
    ∀ i a, tailRow2Data i (tailRow2Data i a) = a := by decide

def tailRow2 (i : Fin 2) : Perm (Fin 2) where
  toFun := tailRow2Data i
  invFun := tailRow2Data i
  left_inv := tailRow2Data_involutive i
  right_inv := tailRow2Data_involutive i

/-- Lexicographic rows of the subgroup generated by `(0 1)` and
`(0 2)(1 3)`. -/
def tailRow4Data : Fin 8 → Fin 4 → Fin 4 :=
  ![![0, 1, 2, 3], ![0, 1, 3, 2], ![1, 0, 2, 3], ![1, 0, 3, 2],
    ![2, 3, 0, 1], ![2, 3, 1, 0], ![3, 2, 0, 1], ![3, 2, 1, 0]]

def tailRow4InverseIndex : Fin 8 → Fin 8 := ![0, 1, 2, 3, 4, 6, 5, 7]

theorem tailRow4Data_leftInverse :
    ∀ i a, tailRow4Data (tailRow4InverseIndex i) (tailRow4Data i a) = a := by decide

theorem tailRow4Data_rightInverse :
    ∀ i a, tailRow4Data i (tailRow4Data (tailRow4InverseIndex i) a) = a := by decide

def tailRow4 (i : Fin 8) : Perm (Fin 4) where
  toFun := tailRow4Data i
  invFun := tailRow4Data (tailRow4InverseIndex i)
  left_inv := tailRow4Data_leftInverse i
  right_inv := tailRow4Data_rightInverse i

@[simp] theorem tailRow1_apply (i : Fin 1) (a : Fin 1) : tailRow1 i a = a := rfl
@[simp] theorem tailRow2_apply (i : Fin 2) (a : Fin 2) :
    tailRow2 i a = tailRow2Data i a := rfl
@[simp] theorem tailRow4_apply (i : Fin 8) (a : Fin 4) :
    tailRow4 i a = tailRow4Data i a := rfl

theorem tailRow1_injective : Function.Injective tailRow1 := by decide
theorem tailRow2_injective : Function.Injective tailRow2 := by decide
theorem tailRow4_injective : Function.Injective tailRow4 := by decide

theorem tailRow1_one : tailRow1 0 = 1 := rfl
theorem tailRow2_one : tailRow2 0 = 1 := by decide
theorem tailRow4_one : tailRow4 0 = 1 := by decide

theorem tailRow1_mul_closed : ∀ i j, ∃ l, tailRow1 l = tailRow1 i * tailRow1 j := by decide
theorem tailRow2_mul_closed : ∀ i j, ∃ l, tailRow2 l = tailRow2 i * tailRow2 j := by decide
theorem tailRow4_mul_closed : ∀ i j, ∃ l, tailRow4 l = tailRow4 i * tailRow4 j := by decide

theorem tailRow1_inv_closed : ∀ i, ∃ j, tailRow1 j = (tailRow1 i)⁻¹ := by decide
theorem tailRow2_inv_closed : ∀ i, ∃ j, tailRow2 j = (tailRow2 i)⁻¹ := by decide
theorem tailRow4_inv_closed : ∀ i, ∃ j, tailRow4 j = (tailRow4 i)⁻¹ := by decide

def tailSubgroup1 : Subgroup (Perm (Fin 1)) :=
  subgroupOfClosedPermutationRows tailRow1 ⟨0, tailRow1_one⟩
    tailRow1_mul_closed tailRow1_inv_closed

def tailSubgroup2 : Subgroup (Perm (Fin 2)) :=
  subgroupOfClosedPermutationRows tailRow2 ⟨0, tailRow2_one⟩
    tailRow2_mul_closed tailRow2_inv_closed

def tailSubgroup4 : Subgroup (Perm (Fin 4)) :=
  subgroupOfClosedPermutationRows tailRow4 ⟨0, tailRow4_one⟩
    tailRow4_mul_closed tailRow4_inv_closed

@[simp] theorem mem_tailSubgroup1_iff (g : Perm (Fin 1)) :
    g ∈ tailSubgroup1 ↔ ∃ i, tailRow1 i = g := Iff.rfl
@[simp] theorem mem_tailSubgroup2_iff (g : Perm (Fin 2)) :
    g ∈ tailSubgroup2 ↔ ∃ i, tailRow2 i = g := Iff.rfl
@[simp] theorem mem_tailSubgroup4_iff (g : Perm (Fin 4)) :
    g ∈ tailSubgroup4 ↔ ∃ i, tailRow4 i = g := Iff.rfl

def tailRows1 : Finset (Perm (Fin 1)) := Finset.univ.image tailRow1
def tailRows2 : Finset (Perm (Fin 2)) := Finset.univ.image tailRow2
def tailRows4 : Finset (Perm (Fin 4)) := Finset.univ.image tailRow4

@[simp] theorem mem_tailRows1_iff (g : Perm (Fin 1)) :
    g ∈ tailRows1 ↔ g ∈ tailSubgroup1 := by simp [tailRows1, eq_comm]
@[simp] theorem mem_tailRows2_iff (g : Perm (Fin 2)) :
    g ∈ tailRows2 ↔ g ∈ tailSubgroup2 := by simp [tailRows2]
@[simp] theorem mem_tailRows4_iff (g : Perm (Fin 4)) :
    g ∈ tailRows4 ↔ g ∈ tailSubgroup4 := by simp [tailRows4]

theorem card_tailRows1 : tailRows1.card = 1 := by decide
theorem card_tailRows2 : tailRows2.card = 2 := by decide
theorem card_tailRows4 : tailRows4.card = 8 := by decide

theorem natCard_tailSubgroup1 : Nat.card tailSubgroup1 = 1 := by
  change Nat.card (Set.range tailRow1) = 1
  rw [Nat.card_range_of_injective tailRow1_injective, Nat.card_fin]

theorem natCard_tailSubgroup2 : Nat.card tailSubgroup2 = 2 := by
  change Nat.card (Set.range tailRow2) = 2
  rw [Nat.card_range_of_injective tailRow2_injective, Nat.card_fin]

theorem natCard_tailSubgroup4 : Nat.card tailSubgroup4 = 8 := by
  change Nat.card (Set.range tailRow4) = 8
  rw [Nat.card_range_of_injective tailRow4_injective, Nat.card_fin]

theorem isPGroup_tailSubgroup1 : IsPGroup 2 tailSubgroup1 :=
  IsPGroup.of_card (n := 0) natCard_tailSubgroup1

theorem isPGroup_tailSubgroup2 : IsPGroup 2 tailSubgroup2 :=
  IsPGroup.of_card (n := 1) (by simpa using natCard_tailSubgroup2)

theorem isPGroup_tailSubgroup4 : IsPGroup 2 tailSubgroup4 :=
  IsPGroup.of_card (n := 3) (by simpa using natCard_tailSubgroup4)

theorem tailSubgroup1_eq_top : tailSubgroup1 = ⊤ := by
  apply top_unique
  intro g _
  exact ⟨0, Subsingleton.elim _ _⟩

theorem tailSubgroup2_eq_top : tailSubgroup2 = ⊤ := by
  apply top_unique
  intro g _
  change ∃ i, tailRow2 i = g
  have h : ∀ g : Perm (Fin 2), ∃ i, tailRow2 i = g := by decide
  exact h g

theorem tailRow4_generator_swap : tailRow4 2 = swap 0 1 := by decide

theorem tailRow4_generator_doubleSwap : tailRow4 4 = swap 0 2 * swap 1 3 := by decide

private theorem tailRow4_eq_generator_words :
    tailRow4 =
      let a : Perm (Fin 4) := swap 0 1
      let b : Perm (Fin 4) := swap 0 2 * swap 1 3
      ![1, b * a * b, a, a * b * a * b, b, a * b, b * a, a * b * a] := by decide

/-- The explicit eight rows are exactly the standard dihedral group
generated by an edge flip and the exchange of the two pairs. -/
theorem tailSubgroup4_eq_closure_generators :
    tailSubgroup4 = Subgroup.closure
      ({swap (0 : Fin 4) 1, swap 0 2 * swap 1 3} : Set (Perm (Fin 4))) := by
  let H := Subgroup.closure
    ({swap (0 : Fin 4) 1, swap 0 2 * swap 1 3} : Set (Perm (Fin 4)))
  have ha : swap (0 : Fin 4) 1 ∈ H := Subgroup.subset_closure (by simp)
  have hb : swap (0 : Fin 4) 2 * swap 1 3 ∈ H := Subgroup.subset_closure (by simp)
  have hrow (i : Fin 8) : tailRow4 i ∈ H := by
    rw [tailRow4_eq_generator_words]
    fin_cases i
    · exact H.one_mem
    · exact H.mul_mem (H.mul_mem hb ha) hb
    · exact ha
    · exact H.mul_mem (H.mul_mem (H.mul_mem ha hb) ha) hb
    · exact hb
    · exact H.mul_mem ha hb
    · exact H.mul_mem hb ha
    · exact H.mul_mem (H.mul_mem ha hb) ha
  apply le_antisymm
  · rintro g ⟨i, rfl⟩
    exact hrow i
  · apply (Subgroup.closure_le _).mpr
    intro g hg
    rcases Set.mem_insert_iff.mp hg with rfl | hg
    · exact ⟨2, tailRow4_generator_swap⟩
    · have hg' : g = swap 0 2 * swap 1 3 := Set.mem_singleton_iff.mp hg
      exact ⟨4, tailRow4_generator_doubleSwap.trans hg'.symm⟩

end LisiSabatini
