module

public import Mathlib.GroupTheory.Perm.ClosureSwap

/-!
# Matching flips and common transpositions

An involution, with fixed points permitted, specifies a matching. Its flip
subgroup independently exchanges the two endpoints of any of its edges.
A nontrivial intersection of two such subgroups contains a transposition:
any point moved by a common element identifies a common matching edge.

The structural statements do not require finiteness. Finiteness is needed
only to express every matching flip as a product of edge transpositions.
-/

@[expose] public section

noncomputable section

namespace LisiSabatini

open Equiv

variable {α : Type*}

/-- The subgroup whose elements independently flip edges of the matching
specified by the involution `τ`. Fixed points of `τ` are fixed by this subgroup. -/
def matchingFlipSubgroup (τ : Perm α) (hτ : Function.Involutive τ) :
    Subgroup (Perm α) where
  carrier := {g | ∀ a, g a = a ∨ g a = τ a}
  one_mem' a := Or.inl rfl
  mul_mem' {g h} hg hh a := by
    change g (h a) = a ∨ g (h a) = τ a
    rcases hh a with ha | ha
    · simpa only [ha] using hg a
    · rw [ha]
      rcases hg (τ a) with hga | hga
      · exact Or.inr hga
      · exact Or.inl (hga.trans (hτ a))
  inv_mem' {g} hg a := by
    rcases hg (g⁻¹ a) with ha | ha
    · exact Or.inl (ha.symm.trans (g.apply_symm_apply a))
    · right
      have heq : a = τ (g⁻¹ a) := (g.apply_symm_apply a).symm.trans ha
      calc
        g⁻¹ a = τ (τ (g⁻¹ a)) := (hτ _).symm
        _ = τ a := congrArg τ heq.symm

@[simp]
theorem mem_matchingFlipSubgroup_iff (τ : Perm α) (hτ : Function.Involutive τ)
    (g : Perm α) :
    g ∈ matchingFlipSubgroup τ hτ ↔ ∀ a, g a = a ∨ g a = τ a := Iff.rfl

/-- Every edge transposition belongs to the matching flip subgroup. -/
theorem swap_mem_matchingFlipSubgroup [DecidableEq α]
    (τ : Perm α) (hτ : Function.Involutive τ) (a : α) :
    swap a (τ a) ∈ matchingFlipSubgroup τ hτ := by
  intro b
  by_cases hba : b = a
  · subst b
    exact Or.inr (swap_apply_left _ _)
  by_cases hbt : b = τ a
  · subst b
    exact Or.inr ((swap_apply_right _ _).trans (hτ a).symm)
  exact Or.inl (swap_apply_of_ne_of_ne hba hbt)

/-- Every matching flip is itself an involution, allowing the identity. -/
theorem involutive_of_mem_matchingFlipSubgroup
    (τ : Perm α) (hτ : Function.Involutive τ) {g : Perm α}
    (hg : g ∈ matchingFlipSubgroup τ hτ) : Function.Involutive g := by
  intro a
  rcases hg a with ha | ha
  · rw [ha, ha]
  rcases hg (τ a) with hta | hta
  · have hat : a = τ a := g.injective (ha.trans hta.symm)
    rw [ha, hta, ← hat]
  · rw [ha, hta, hτ a]

theorem sq_eq_one_of_mem_matchingFlipSubgroup
    (τ : Perm α) (hτ : Function.Involutive τ) {g : Perm α}
    (hg : g ∈ matchingFlipSubgroup τ hτ) : g ^ 2 = 1 := by
  ext a
  exact involutive_of_mem_matchingFlipSubgroup τ hτ hg a

/-- On a finite set, a permutation belongs to any subgroup containing
the transpositions from each point to its image. -/
theorem perm_mem_of_forall_swap_mem [Finite α] [DecidableEq α]
    (H : Subgroup (Perm α)) (g : Perm α)
    (hswap : ∀ a, swap a (g a) ∈ H) : g ∈ H := by
  classical
  let S : Set (Perm α) := {s | s.IsSwap ∧ s ∈ H}
  have hle : Subgroup.closure S ≤ H :=
    (Subgroup.closure_le _).mpr fun _ hs ↦ hs.2
  apply hle
  apply (mem_closure_isSwap (S := S) (fun _ hs ↦ hs.1)).mpr
  refine ⟨Set.toFinite _, fun a ↦ ?_⟩
  refine ⟨⟨swap a (g a), ?_⟩, swap_apply_left a (g a)⟩
  by_cases ha : a = g a
  · rw [← ha, swap_self]
    exact Subgroup.one_mem _
  · exact Subgroup.subset_closure ⟨⟨a, g a, ha, rfl⟩, hswap a⟩

/-- The matching flip subgroup is contained in every subgroup containing
all of its edge transpositions. -/
theorem matchingFlipSubgroup_le_of_swap_mem [Finite α] [DecidableEq α]
    (τ : Perm α) (hτ : Function.Involutive τ) (H : Subgroup (Perm α))
    (hswap : ∀ a, swap a (τ a) ∈ H) : matchingFlipSubgroup τ hτ ≤ H := by
  intro g hg
  apply perm_mem_of_forall_swap_mem H g
  intro a
  rcases hg a with ha | ha
  · rw [ha, swap_self]
    exact H.one_mem
  · rw [ha]
    exact hswap a

/-- Over a finite set the pointwise definition is exactly the subgroup
generated by the individual edge transpositions. -/
theorem matchingFlipSubgroup_eq_closure_range_swap [Finite α] [DecidableEq α]
    (τ : Perm α) (hτ : Function.Involutive τ) :
    matchingFlipSubgroup τ hτ = Subgroup.closure (Set.range (fun a ↦ swap a (τ a))) := by
  apply le_antisymm
  · apply matchingFlipSubgroup_le_of_swap_mem
    intro a
    exact Subgroup.subset_closure ⟨a, rfl⟩
  · apply (Subgroup.closure_le _).mpr
    rintro s ⟨a, rfl⟩
    exact swap_mem_matchingFlipSubgroup τ hτ a

/-- A point moved by an element of two matching flip subgroups is an
endpoint of a nontrivial edge shared by both matchings. -/
theorem common_matching_edge_of_mem_of_apply_ne
    (τ υ : Perm α) (hτ : Function.Involutive τ) (hυ : Function.Involutive υ)
    {g : Perm α} (hgτ : g ∈ matchingFlipSubgroup τ hτ)
    (hgυ : g ∈ matchingFlipSubgroup υ hυ) {a : α} (ha : g a ≠ a) :
    a ≠ τ a ∧ τ a = υ a := by
  have hgaτ : g a = τ a := (hgτ a).resolve_left ha
  have hgaυ : g a = υ a := (hgυ a).resolve_left ha
  exact ⟨fun hat ↦ ha (hgaτ.trans hat.symm), hgaτ.symm.trans hgaυ⟩

/-- A nontrivial common matching flip supplies an explicit common edge. -/
theorem exists_common_matching_edge_of_mem_of_ne_one
    (τ υ : Perm α) (hτ : Function.Involutive τ) (hυ : Function.Involutive υ)
    {g : Perm α} (hgτ : g ∈ matchingFlipSubgroup τ hτ)
    (hgυ : g ∈ matchingFlipSubgroup υ hυ) (hg : g ≠ 1) :
    ∃ a, a ≠ τ a ∧ τ a = υ a := by
  classical
  have ha : ∃ a, g a ≠ a := by
    by_contra! h
    exact hg (Equiv.ext h)
  obtain ⟨a, ha⟩ := ha
  exact ⟨a, common_matching_edge_of_mem_of_apply_ne τ υ hτ hυ hgτ hgυ ha⟩

/-- A nontrivial intersection of matching flip subgroups is witnessed by
a single transposition, rather than a product of disjoint transpositions. -/
theorem matchingFlipSubgroup_inf_ne_bot_iff_exists_isSwap [DecidableEq α]
    (τ υ : Perm α) (hτ : Function.Involutive τ) (hυ : Function.Involutive υ) :
    matchingFlipSubgroup τ hτ ⊓ matchingFlipSubgroup υ hυ ≠ ⊥ ↔
      ∃ s : Perm α, s.IsSwap ∧ s ∈ matchingFlipSubgroup τ hτ ∧
        s ∈ matchingFlipSubgroup υ hυ := by
  constructor
  · intro h
    obtain ⟨g, hg, hg1⟩ :=
      (Subgroup.nontrivial_iff_exists_ne_one _).mp
        ((Subgroup.nontrivial_iff_ne_bot _).mpr h)
    obtain ⟨a, ha, hau⟩ :=
      exists_common_matching_edge_of_mem_of_ne_one τ υ hτ hυ hg.1 hg.2 hg1
    exact ⟨swap a (τ a), ⟨a, τ a, ha, rfl⟩,
      swap_mem_matchingFlipSubgroup τ hτ a,
      hau ▸ swap_mem_matchingFlipSubgroup υ hυ a⟩
  · rintro ⟨s, ⟨a, b, hab, rfl⟩, hsτ, hsυ⟩ hbot
    have hs : swap a b = (1 : Perm α) := by
      exact Subgroup.mem_bot.mp (hbot ▸ (show swap a b ∈
        matchingFlipSubgroup τ hτ ⊓ matchingFlipSubgroup υ hυ from ⟨hsτ, hsυ⟩))
    have := congrArg (fun g : Perm α ↦ g a) hs
    exact hab (by simpa only [swap_apply_left, Perm.one_apply] using this.symm)

/-- Conjugating a matching again gives an involution. -/
theorem involutive_conj_matching (τ : Perm α) (hτ : Function.Involutive τ)
    (x : Perm α) : Function.Involutive (x * τ * x⁻¹) := by
  intro a
  change x (τ (x.symm (x (τ (x.symm a))))) = a
  rw [x.symm_apply_apply, hτ, x.apply_symm_apply]

/-- Matching flip membership is preserved by relabeling the underlying set. -/
theorem conj_mem_matchingFlipSubgroup_iff
    (τ : Perm α) (hτ : Function.Involutive τ) (x g : Perm α) :
    x * g * x⁻¹ ∈ matchingFlipSubgroup (x * τ * x⁻¹)
      (involutive_conj_matching τ hτ x) ↔ g ∈ matchingFlipSubgroup τ hτ := by
  constructor
  · intro hg a
    have ha := hg (x a)
    change x (g (x.symm (x a))) = x a ∨
      x (g (x.symm (x a))) = x (τ (x.symm (x a))) at ha
    rw [x.symm_apply_apply] at ha
    exact ha.imp (fun h ↦ x.injective h) (fun h ↦ x.injective h)
  · intro hg a
    change x (g (x.symm a)) = a ∨ x (g (x.symm a)) = x (τ (x.symm a))
    rcases hg (x.symm a) with ha | ha
    · exact Or.inl ((congrArg x ha).trans (x.apply_symm_apply a))
    · exact Or.inr (congrArg x ha)

end LisiSabatini
